# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class Site(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Name of the site
    """

    url: str = pydantic.Field()
    """
    URL of the site
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
