import uuid
from typing import Optional, Union, Dict, List, Callable
from qtpy.QtWidgets import QFrame, QVBoxLayout, QWidget, QSizePolicy
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from ..typography import Typography
from ..utils.validate_params import _validate_param
from ..box import Box
class List:
    def __init__(self, ariaLabelledby: Optional[Union[State, str, Callable]], children: Optional[Union[State, QWidget, List[Union[QWidget, str]]]], classes: Optional[Union[State, Dict]], component: Optional[Union[State, str]], dense: Union[State, bool], disablePadding: Union[State, bool], subheader: Optional[Union[State, QWidget]], sx: Optional[Union[State, List, Dict, Callable, str]], **kwargs): ...
    def _set_ariaLabelledby(self, value): ...
    def _get_ariaLabelledby(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_component(self, value): ...
    def _get_component(self): ...
    def _set_dense(self, value): ...
    def _get_dense(self): ...
    def _set_disablePadding(self, value): ...
    def _get_disablePadding(self): ...
    def _set_subheader(self, value): ...
    def _get_subheader(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _init_ui(self): ...