"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from intuned_client import errors, models, utils
from intuned_client._hooks import HookContext
from intuned_client.types import OptionalNullable, UNSET
from intuned_client.utils import get_security_from_env
from intuned_client.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Dict, Mapping, Optional


class Update(BaseSDK):
    r"""Manage the update of authentication sessions"""

    def start(
        self,
        *,
        project_name: str,
        auth_session_id: str,
        parameters: Dict[str, Any],
        proxy: OptionalNullable[str] = UNSET,
        create_attempts: Optional[int] = 3,
        check_attempts: Optional[int] = 3,
        save_trace: Optional[bool] = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateAuthSessionStartResponse:
        r"""Update Auth Session - Start

        Starts updating process of an authentication session.

        :param project_name: Your project name. It is the name you provide when creating a project.
        :param auth_session_id: Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
        :param parameters: The parameters to be passed to the API.
        :param proxy: Proxy configuration for the job
        :param create_attempts: Number of attempts to create a new auth session if the current one is invalid or expired.
        :param check_attempts: Number of attempts to check the validity of the auth session before recreating it.
        :param save_trace:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateAuthSessionStartRequest(
            project_name=project_name,
            auth_session_id=auth_session_id,
            request_body=models.UpdateAuthSessionStartRequestBody(
                parameters=parameters,
                proxy=proxy,
                create_attempts=create_attempts,
                check_attempts=check_attempts,
                save_trace=save_trace,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/{workspaceId}/projects/{projectName}/auth-sessions/{authSessionId}/update",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.UpdateAuthSessionStartGlobals(
                workspace_id=self.sdk_configuration.globals.workspace_id,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.UpdateAuthSessionStartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="UpdateAuthSessionStart",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "201", "application/json"):
            return unmarshal_json_response(
                models.UpdateAuthSessionStartResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.IntunedClientDefaultError("Unexpected response received", http_res)

    async def start_async(
        self,
        *,
        project_name: str,
        auth_session_id: str,
        parameters: Dict[str, Any],
        proxy: OptionalNullable[str] = UNSET,
        create_attempts: Optional[int] = 3,
        check_attempts: Optional[int] = 3,
        save_trace: Optional[bool] = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateAuthSessionStartResponse:
        r"""Update Auth Session - Start

        Starts updating process of an authentication session.

        :param project_name: Your project name. It is the name you provide when creating a project.
        :param auth_session_id: Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
        :param parameters: The parameters to be passed to the API.
        :param proxy: Proxy configuration for the job
        :param create_attempts: Number of attempts to create a new auth session if the current one is invalid or expired.
        :param check_attempts: Number of attempts to check the validity of the auth session before recreating it.
        :param save_trace:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateAuthSessionStartRequest(
            project_name=project_name,
            auth_session_id=auth_session_id,
            request_body=models.UpdateAuthSessionStartRequestBody(
                parameters=parameters,
                proxy=proxy,
                create_attempts=create_attempts,
                check_attempts=check_attempts,
                save_trace=save_trace,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/{workspaceId}/projects/{projectName}/auth-sessions/{authSessionId}/update",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.UpdateAuthSessionStartGlobals(
                workspace_id=self.sdk_configuration.globals.workspace_id,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.UpdateAuthSessionStartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="UpdateAuthSessionStart",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "201", "application/json"):
            return unmarshal_json_response(
                models.UpdateAuthSessionStartResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.IntunedClientDefaultError("Unexpected response received", http_res)

    def result(
        self,
        *,
        project_name: str,
        auth_session_id: str,
        operation_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateAuthSessionResultResponse:
        r"""Update Auth Session - Result

        Gets authentication session update operation result.

        :param project_name: Your project name. It is the name you provide when creating a project.
        :param auth_session_id: Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
        :param operation_id: The ID for the requested auth session creation operation. This is obtained from the start request.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateAuthSessionResultRequest(
            project_name=project_name,
            auth_session_id=auth_session_id,
            operation_id=operation_id,
        )

        req = self._build_request(
            method="GET",
            path="/{workspaceId}/projects/{projectName}/auth-sessions/{authSessionId}/update/{operationId}/result",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.UpdateAuthSessionResultGlobals(
                workspace_id=self.sdk_configuration.globals.workspace_id,
            ),
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateAuthSessionResult",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateAuthSessionResultResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.IntunedClientDefaultError("Unexpected response received", http_res)

    async def result_async(
        self,
        *,
        project_name: str,
        auth_session_id: str,
        operation_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateAuthSessionResultResponse:
        r"""Update Auth Session - Result

        Gets authentication session update operation result.

        :param project_name: Your project name. It is the name you provide when creating a project.
        :param auth_session_id: Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
        :param operation_id: The ID for the requested auth session creation operation. This is obtained from the start request.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateAuthSessionResultRequest(
            project_name=project_name,
            auth_session_id=auth_session_id,
            operation_id=operation_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/{workspaceId}/projects/{projectName}/auth-sessions/{authSessionId}/update/{operationId}/result",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.UpdateAuthSessionResultGlobals(
                workspace_id=self.sdk_configuration.globals.workspace_id,
            ),
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateAuthSessionResult",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateAuthSessionResultResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.IntunedClientDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.IntunedClientDefaultError("Unexpected response received", http_res)
