import asyncio
from typing import Callable, Optional, Union
from qtpy.QtWidgets import QCheckBox, QRadioButton
from qtpy.QtGui import QPainter, QPen, QColor
from qtpy.QtCore import Qt, Signal, QSize, QTimer
from qtmui.material.styles.create_theme.theme_reducer import ThemeState
from qtmui.material.styles.create_theme.create_palette import PaletteColor
from ..system.color_manipulator import hex_string_to_qcolor
from ..button.button import Button
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
class Radio:
    def __init__(self, id: str, checked: bool, icon: str, checkedIcon: str, color: str, name: str, onChange: Callable, text: Optional[Union[str, State, Callable]], value: object, hightLight: bool, *args, **kwargs): ...
    def __init_ui(self): ...
    def onClick(self): ...
    def checked(self): ...
    def checked(self, value: bool): ...
    def _setChecked(self, value: bool): ...
    def _set_stylesheet(self, component_styled): ...
    def paintEvent(self, event): ...