from qtpy.QtWidgets import QHBoxLayout, QVBoxLayout, QFrame, QWidget, QScrollArea, QSizePolicy, QApplication, QLabel
from qtpy.QtGui import QGuiApplication
from qtpy.QtCore import Qt, QEvent
import uuid
from qtmui.hooks import State
class MenuScrollArea:
    def __init__(self, sx: dict, maxWidth: int, defaultWidth: int, hightLight: bool, backgroundColor: str, children: list, fullWidth: bool, spacing, border: str, borderForNav: bool): ...
    def _set_stylesheet(self): ...
    def _set_background(self, background): ...
    def setFullWidth(self): ...
    def adjustWidth(self): ...