from __future__ import annotations
import warnings
from typing import TYPE_CHECKING
from qtpy.QtCore import QSize, Qt
from qtpy.QtGui import QIcon, QPainter, QPixmap
from qtpy.QtWidgets import QApplication
class Iconify:
    def __init__(self, key: str, color: Any, flip: Flip, rotate: Any, dir: Any, size: Any): ...
    def qIcon(self): ...
    def addKey(self, key: str, color: Any, flip: Any, rotate: Any, dir: Any, size: Any, mode: QIcon.Mode, state: QIcon.State): ...
    def _draw_text_fallback(self, key: tuple[str, Any]): ...