from _typeshed import Incomplete
from typing import Any

class _Param:
    name: Incomplete
    default: Incomplete
    _value: Incomplete
    def __init__(self, name: str, default: Any) -> None: ...
    def value(self) -> Any: ...
    def set(self, value: Any): ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class Params:
    _registry: dict[str, _Param]
    def __init__(self) -> None: ...
    def register(self, name_or_dict: str | dict[str, Any], default: Any = None): ...
    def _register_one(self, name: str, default: Any): ...
    def _require_param(self, name: str) -> _Param: ...
    def get(self, name: str) -> Any: ...
    def get_param(self, name: str) -> _Param: ...
    def set(self, name: str, value: Any): ...
    def __getattr__(self, name: str) -> Any: ...
    def all(self) -> dict[str, Any]: ...
    def defaults(self) -> dict[str, Any]: ...
    def copy(self) -> Params: ...
    def __repr__(self) -> str: ...
