from .feature_model import PiPrompt as PiPrompt, QueryDerivedFeature as QueryDerivedFeature
from .param_model import Params as Params
from .request_context_model import get_ctx as get_ctx
from _typeshed import Incomplete
from pydantic import BaseModel
from types import MappingProxyType
from typing import Any, Callable, Mapping, MutableMapping, Sequence

def _freeze(x: Any) -> Any: ...

class _FeaturesFacade(MutableMapping[str, Any]):
    _owner: SearchQuery
    _prompts: dict[str, PiPrompt]
    _pi_input_builder: Callable[..., str] | None
    _pi_input_builder_kwargs: dict[str, Any]
    _overwrite: bool
    def __init__(self, owner: SearchQuery) -> None: ...
    def __getitem__(self, k: str) -> Any: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __delitem__(self, k: str) -> None: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def declared(self) -> dict[str, PiPrompt]: ...
    async def add(self, features: Mapping[str, Callable[[SearchQuery], Any]] | Sequence[QueryDerivedFeature] = (), *, overwrite: bool = True, **named_features: Callable[[SearchQuery], Any]) -> SearchQuery: ...
    def update_sync(self, mapping: Mapping[str, Any]) -> None: ...
    async def populate(self, *, pi_input_builder: Callable[..., str] | None = None, pi_input_builder_kwargs: dict[str, Any] | None = None, overwrite: bool | None = None) -> SearchQuery: ...

class QueryClassificationPrompt(BaseModel):
    name: str
    prompt: str

class SearchQuery(BaseModel):
    query: str
    limit: int
    query_params: Mapping[str, Any]
    _features_facade: _FeaturesFacade | None
    incoming_features: Mapping[str, Any] | None
    _features_store: Mapping[str, Any]
    model_config: Incomplete
    @property
    def features(self) -> _FeaturesFacade: ...
    @property
    def classification_signals(self) -> Mapping[str, Any]: ...
    def model_post_init(self, /, __context: Any) -> None: ...
    @classmethod
    def _ensure_mapping_proxy(cls, value: Any) -> MappingProxyType: ...
    def _serialize_mapping_proxy(self, value: Mapping[str, Any]) -> dict[str, Any]: ...
    def _serialize_features(self, handler): ...
    def populate_params(self, params: Params) -> None: ...
    async def classify(self, query_classification_prompts: list[QueryClassificationPrompt]) -> SearchQuery: ...
    async def fanout_queries(self, *, instruction_prompt: str | None = None) -> list['SearchQuery']: ...
    async def add_features(self, features: Sequence[QueryDerivedFeature] | Mapping[str, Callable[[SearchQuery], Any]] = (), *, overwrite: bool = True, **named_features: Callable[[SearchQuery], Any]) -> SearchQuery: ...
    def _key(self) -> tuple[Any, ...]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
