import uuid
from typing import Callable, Optional
from qtpy.QtWidgets import QFrame, QPushButton, QMenu
from qtpy.QtCore import QPoint, Qt, QEvent, QSize, QCoreApplication, QTimer
from qtpy.QtGui import QMouseEvent, QIcon, QCursor
from ...common.icon import FluentIconBase
from .button import Button
class MenuButton:
    def __init__(self, context, menu: Optional[any], icon: str, aboutToHide: Callable, *args, **kwargs): ...
    def updateUiOnMenuHide(self): ...
    def update_state(self, is_open): ...
    def open_context_menu(self, point): ...
    def get_menu_height(self): ...