# Generated by Django 5.2.4 on 2025-07-31 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country where the observation was made.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filtered_on', to='data.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='filter',
            name='county',
            field=models.ForeignKey(blank=True, help_text='The county where the observation was made.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filtered_on', to='data.county', verbose_name='county'),
        ),
        migrations.AddField(
            model_name='filter',
            name='state',
            field=models.ForeignKey(blank=True, help_text='The state where the observation was made.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filtered_on', to='data.state', verbose_name='state'),
        ),
    ]
