# Copyright (c) 2025 JohnScotttt
# Version 1.0.2

__version__ = "1.0.2"

K2_TARGET_VID = 0x0716
K2_TARGET_PID = 0x5060


class metadata:
    def raw(): ...
    def bit_loc(): ...
    def field(): ...
    def value(): ...


class WITRN_DEV:
    def __init__(self, **kwargs): ...

    def open(self, *args, **kwargs): ...

    def read_data() -> list: ...

    def general_unpack(self, data: list = None) -> tuple[str, metadata]: ...

    def pd_unpack(self,
                  data: list = None,
                  last_pdo: metadata = None,
                  last_ext: metadata = None,
                  last_rdo: metadata = None) -> tuple[str, metadata]: ...

    def auto_unpack(self,
                    data: list = None,
                    last_pdo: metadata = None,
                    last_ext: metadata = None,
                    last_rdo: metadata = None) -> tuple[str, metadata]: ...

    def close(self): ...


def is_pdo(msg: metadata) -> bool: ...

def is_rdo(msg: metadata) -> bool: ...

def provide_ext(msg: metadata) -> bool: ...
