
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-03T11:44:21+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "0fc41bd8bd3b7c950c1acc287659e27b811144e6",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
