# Generated by Django 5.1.7 on 2025-04-07 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitranslatorsettings',
            options={'verbose_name': 'AI Translator', 'verbose_name_plural': 'AI Translator'},
        ),
        migrations.AlterModelOptions(
            name='translationlog',
            options={'verbose_name': 'AI Translation Log', 'verbose_name_plural': 'AI Translation Logs'},
        ),
        migrations.AlterField(
            model_name='aitranslatorsettings',
            name='prompt',
            field=models.TextField(help_text='Prompt to use for translation. You can {language} and {text} as placeholders for the target language and the text to translate.', verbose_name='Prompt'),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
    ]
