"""Typed protocol for the asyncio Redis client used in MAS.

This narrows the subset of methods we rely on with precise async
signatures, avoiding the need for "Any" while remaining compatible
with redis.asyncio.client.Redis via structural typing.
"""

from __future__ import annotations

from typing import AsyncIterator, Awaitable, Protocol


class AsyncRedisProtocol(Protocol):
    # Connection
    def aclose(self) -> Awaitable[None]: ...

    # Keys
    def exists(self, key: str) -> Awaitable[int]: ...
    def delete(self, *keys: str) -> Awaitable[int]: ...
    def expire(self, key: str, seconds: int) -> Awaitable[int]: ...
    def scan(
        self, cursor: int, *, match: str, count: int
    ) -> Awaitable[tuple[int, list[str]]]: ...
    def scan_iter(self, *, match: str) -> AsyncIterator[str]: ...

    # Strings
    def get(self, key: str) -> Awaitable[str | None]: ...
    def set(self, key: str, value: str) -> Awaitable[bool | str]: ...
    def setex(self, key: str, seconds: int, value: str) -> Awaitable[bool | str]: ...

    # Hashes
    def hget(self, key: str, field: str) -> Awaitable[str | None]: ...
    def hset(self, key: str, *, mapping: dict[str, str]) -> Awaitable[int]: ...
    def hgetall(self, key: str) -> Awaitable[dict[str, str]]: ...
    def hdel(self, key: str, *fields: str) -> Awaitable[int]: ...

    # Sets
    def sadd(self, key: str, *members: str) -> Awaitable[int]: ...
    def srem(self, key: str, *members: str) -> Awaitable[int]: ...
    def smembers(self, key: str) -> Awaitable[set[str]]: ...
    def sismember(self, key: str, member: str) -> Awaitable[bool]: ...

    # Sorted sets
    def zadd(self, key: str, mapping: dict[str, float]) -> Awaitable[int]: ...
    def zcard(self, key: str) -> Awaitable[int]: ...
    def zremrangebyscore(
        self, key: str, min: float | str, max: float | str
    ) -> Awaitable[int]: ...

    # Streams
    def xadd(self, name: str, fields: dict[str, str]) -> Awaitable[str]: ...
    def xrange(
        self, name: str, min: str, max: str, count: int | None = ...
    ) -> Awaitable[list[tuple[str, dict[str, str]]]]: ...
    def xlen(self, name: str) -> Awaitable[int]: ...
