from . import group as group
from .comment import Comment as Comment
from .custom_record import CustomRecord as CustomRecord
from .edge import Edge as Edge
from .fragment import Fragment as Fragment
from .gap import Gap as Gap
from .header import Header as Header
from .line import Line as Line
from .segment import Segment as Segment
from .unknown import Unknown as Unknown
