from java.io import File as File

def get_plugins_dir() -> str: ...
def get_cache_dir() -> str: ...
def get_files_dir() -> str: ...
def get_images_dir() -> str: ...
def get_videos_dir() -> str: ...
def get_audios_dir() -> str: ...
def get_documents_dir() -> str: ...
def read_file(file_path: str) -> str: ...
def write_file(file_path: str, content: str): ...
def delete_file(file_path: str) -> bool: ...
def ensure_dir_exists(dir_path: str): ...
def list_dir(path: str, recursive: bool = False, include_files: bool = True, include_dirs: bool = False, extensions: list[str] | None = None) -> list[str]: ...
