from typing import Any

def init(plugins_dir_path: str, all_shared_prefs: dict): ...
def get_setting(plugin_id: str, key: str, default: Any) -> Any: ...
def set_setting(plugin_id: str, key: str, value: Any): ...
def clear_settings(plugin_id: str): ...
def get_all_settings(plugin_id: str) -> Any: ...
def set_all_settings(plugin_id: str, settings: dict): ...
