from _typeshed import Incomplete

class CIGAR(list):
    def complement(self): ...
    def validate(self, version: str = 'gfa1') -> None: ...
    def length_on_reference(self): ...
    def length_on_query(self): ...
    class Operation:
        CODE_GFA1_ONLY: Incomplete
        CODE_GFA1_GFA2: Incomplete
        CODE: Incomplete
        def validate(self, version: str = 'gfa1') -> None: ...
        length: Incomplete
        code: Incomplete
        def __init__(self, length, code) -> None: ...
        def __len__(self) -> int: ...
        def __eq__(self, other): ...
Operation = CIGAR.Operation
