from minjiang_host_client.utils.local import get_cache_dir as get_cache_dir

def write_terminate_signal(exp_id: int, terminate_type: str, message: str) -> None: ...
def check_terminate_signal(exp_id: int = None, direct_exp_id: int = None) -> bool: ...
def cleanup_old_ts_files() -> None: ...
def list_terminate_signal(): ...
def get_terminate_signal(exp_id: int): ...
def remove_terminate_signal(exp_id: int): ...
