"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1 (v1)
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bimdata_api_client
from bimdata_api_client.model.geometry_point import GeometryPoint
globals()['GeometryPoint'] = GeometryPoint
from bimdata_api_client.model.zone_space import ZoneSpace


class TestZoneSpace(unittest.TestCase):
    """ZoneSpace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZoneSpace(self):
        """Test ZoneSpace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ZoneSpace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
