
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-05T10:53:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "31d723c8d343b1259c3b82848dd5c6e9c2071cc1",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
