class FieldData:
    @property
    def positional_fieldnames(self): ...
    @property
    def tagnames(self): ...
    @property
    def record_type(self): ...
    def set(self, fieldname, value): ...
    def get(self, fieldname): ...
    def try_get(self, fieldname): ...
    def delete(self, tagname): ...
