class Writer:
    def to_str(self, add_virtual_commentary: bool = True): ...
    def to_list(self, add_virtual_commentary: bool = True): ...
    def field_to_s(self, fieldname, tag: bool = False): ...
    def refstr(self, maxlen: int = 10): ...
