# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.list_agents_for_project_response import ListAgentsForProjectResponse

class TestListAgentsForProjectResponse(unittest.TestCase):
    """ListAgentsForProjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAgentsForProjectResponse:
        """Test ListAgentsForProjectResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAgentsForProjectResponse`
        """
        model = ListAgentsForProjectResponse()
        if include_optional:
            return ListAgentsForProjectResponse(
                agents = odin_sdk.models.agents.Agents()
            )
        else:
            return ListAgentsForProjectResponse(
        )
        """

    def testListAgentsForProjectResponse(self):
        """Test ListAgentsForProjectResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
