from _typeshed import Incomplete

class Collections:
    @property
    def comments(self): ...
    @property
    def gaps(self): ...
    @property
    def sets(self): ...
    @property
    def segments(self): ...
    @property
    def edges(self): ...
    @property
    def dovetails(self): ...
    @property
    def containments(self): ...
    @property
    def paths(self): ...
    @property
    def fragments(self): ...
    @property
    def custom_records(self): ...
    @property
    def gap_names(self): ...
    @property
    def set_names(self): ...
    @property
    def segment_names(self): ...
    @property
    def edge_names(self): ...
    @property
    def path_names(self): ...
    @property
    def names(self): ...
    def unused_name(self): ...
    @property
    def external_names(self): ...
    GFA1_ONLY_KEYS: Incomplete
    NONCUSTOM_GFA2_KEYS: Incomplete
    @property
    def custom_record_keys(self): ...
    def custom_records_of_type(self, record_type): ...
    @property
    def lines(self): ...
