from _typeshed import Incomplete

class Finders:
    def segment(self, s): ...
    def try_get_segment(self, s): ...
    RECORDS_WITH_NAME: Incomplete
    def line(self, l): ...
    def try_get_line(self, l): ...
    def fragments_for_external(self, external_id): ...
    def select(self, dict_or_line): ...
