V4_SIGNATURE_SALT = 'ots'
V4_SIGNATURE_PRODUCT = 'ots'
V4_SIGNATURE_SEED = 'aliyun'
V4_SIGNATURE_PREFIX = V4_SIGNATURE_SEED + '_v4'
V4_SIGNATURE_CONSTANT = V4_SIGNATURE_SEED + '_v4_request'

V4_SIGNATURE_SIGN_DATE_FORMAT = '%Y%m%d'

OTS_HEADER_PREFIX = 'x-ots-'
OTS_HEADER_SIGNATURE = 'x-ots-signature'
OTS_HEADER_SIGNATURE_V4 = 'x-ots-signaturev4'
OTS_HEADER_SIGN_DATE = 'x-ots-signdate'
OTS_HEADER_SIGN_REGION = 'x-ots-signregion'
