class VersionConversion:
    @property
    def version(self): ...
    @property
    def dialect(self): ...
    def to_version_s(self, version): ...
    def to_version(self, version, raise_on_failure: bool = True): ...
