class FieldArray:
    def __init__(self, datatype, data=None) -> None: ...
    @property
    def datatype(self): ...
    def validate(self, fieldname: str | None = None) -> None: ...
    def __eq__(self, other): ...
    def __add__(self, other) -> None: ...
    def __iter__(self): ...
    def __getattr__(self, name): ...
