from typing import Literal

class OrientedLine:
    def __new__(cls, *args): ...
    def __init__(self, *args) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, line) -> None: ...
    @property
    def orient(self) -> Literal["+", "-"]: ...
    @orient.setter
    def orient(self, orient: Literal["+", "-"]) -> None: ...
    @property
    def name(self) -> str: ...
    def validate(self) -> None: ...
    def inverted(self): ...
    def invert(self) -> None: ...
    def __eq__(self, other): ...
    def __getattr__(self, name): ...
