class SegmentEnd:
    def __new__(cls, *args): ...
    def __init__(self, *args) -> None: ...
    def validate(self) -> None: ...
    @property
    def segment(self): ...
    @segment.setter
    def segment(self, value) -> None: ...
    @property
    def name(self): ...
    @property
    def end_type(self): ...
    @end_type.setter
    def end_type(self, value) -> None: ...
    def inverted(self): ...
    def __eq__(self, other): ...
    def __getattr__(self, name): ...
