# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.avxcelerate.sensors.v1.ground_truth_access import camera_ground_truth_pb2 as ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_camera__ground__truth__pb2
from ansys.api.avxcelerate.sensors.v1.ground_truth_access import contribution_dictionary_pb2 as ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GroundTruthDataHelperStub(object):
    """Ground Truth Data Helper Service

    This service provides the procedures to acquire ground truth auxiliary 
    information.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContributionDictionary = channel.unary_unary(
                '/ansys.api.avxcelerate.sensors.v1.ground_truth_access.GroundTruthDataHelper/GetContributionDictionary',
                request_serializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.SensorIdentifier.SerializeToString,
                response_deserializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.ContributionDictionary.FromString,
                )
        self.GetPixelSegmentationTagColorMap = channel.unary_unary(
                '/ansys.api.avxcelerate.sensors.v1.ground_truth_access.GroundTruthDataHelper/GetPixelSegmentationTagColorMap',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_camera__ground__truth__pb2.PixelSegmentationTagColorMap.FromString,
                )


class GroundTruthDataHelperServicer(object):
    """Ground Truth Data Helper Service

    This service provides the procedures to acquire ground truth auxiliary 
    information.

    """

    def GetContributionDictionary(self, request, context):
        """Requests a dictionary which offers the possibility to relate IDs 
        in the contribution output of the lidar specified in the request message 
        to the asset information.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPixelSegmentationTagColorMap(self, request, context):
        """Requests the mapping table of tags and colors used in the simulation
        for the pixel segmentation camera output.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroundTruthDataHelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContributionDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContributionDictionary,
                    request_deserializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.SensorIdentifier.FromString,
                    response_serializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.ContributionDictionary.SerializeToString,
            ),
            'GetPixelSegmentationTagColorMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPixelSegmentationTagColorMap,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_camera__ground__truth__pb2.PixelSegmentationTagColorMap.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.avxcelerate.sensors.v1.ground_truth_access.GroundTruthDataHelper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GroundTruthDataHelper(object):
    """Ground Truth Data Helper Service

    This service provides the procedures to acquire ground truth auxiliary 
    information.

    """

    @staticmethod
    def GetContributionDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.avxcelerate.sensors.v1.ground_truth_access.GroundTruthDataHelper/GetContributionDictionary',
            ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.SensorIdentifier.SerializeToString,
            ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_contribution__dictionary__pb2.ContributionDictionary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPixelSegmentationTagColorMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.avxcelerate.sensors.v1.ground_truth_access.GroundTruthDataHelper/GetPixelSegmentationTagColorMap',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_ground__truth__access_dot_camera__ground__truth__pb2.PixelSegmentationTagColorMap.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
