# coding: utf-8

"""
HaploHub API

The HaploHub is a turnkey solution to securely store and interpret biomarkers, genetics, and 'omics data. Our customers use the HaploHub to:  * Store WGS, WES, low-pass, and array data with uniform REST interfaces to access variants  * Interpret genomic variants  * Generate risk scores for an individual  * Run the typical algorithms (phasing, imputation, etc.)  * Calculate 'biological age' or 'organ age' biomarkers  * Generate custom reports  The HaploHub platform is continually updated to remain at the forefront of scientific understanding.

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, constr

from haplohub.models.id import Id
from haplohub.models.member_id1 import MemberId1
from haplohub.models.result_id import ResultId
from haplohub.models.sample_id1 import SampleId1


class ScoreSchema(BaseModel):
    """
    ScoreSchema
    """

    id: Id = Field(...)
    member_id: MemberId1 = Field(...)
    sample_id: SampleId1 = Field(...)
    result_id: ResultId = Field(...)
    pgs_model_id: constr(strict=True, max_length=255) = Field(...)
    adjusted_z_score: Union[StrictFloat, StrictInt] = Field(...)
    percentile: Union[StrictFloat, StrictInt] = Field(...)
    population_id: constr(strict=True, max_length=255) = Field(...)
    population_percentile: Union[StrictFloat, StrictInt] = Field(...)
    population_z_score: Union[StrictFloat, StrictInt] = Field(...)
    modified: Optional[datetime] = None
    created: Optional[datetime] = None
    __properties = [
        "id",
        "member_id",
        "sample_id",
        "result_id",
        "pgs_model_id",
        "adjusted_z_score",
        "percentile",
        "population_id",
        "population_percentile",
        "population_z_score",
        "modified",
        "created",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ScoreSchema:
        """Create an instance of ScoreSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict["id"] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of member_id
        if self.member_id:
            _dict["member_id"] = self.member_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sample_id
        if self.sample_id:
            _dict["sample_id"] = self.sample_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of result_id
        if self.result_id:
            _dict["result_id"] = self.result_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ScoreSchema:
        """Create an instance of ScoreSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ScoreSchema.parse_obj(obj)

        _obj = ScoreSchema.parse_obj(
            {
                "id": Id.from_dict(obj.get("id")) if obj.get("id") is not None else None,
                "member_id": MemberId1.from_dict(obj.get("member_id")) if obj.get("member_id") is not None else None,
                "sample_id": SampleId1.from_dict(obj.get("sample_id")) if obj.get("sample_id") is not None else None,
                "result_id": ResultId.from_dict(obj.get("result_id")) if obj.get("result_id") is not None else None,
                "pgs_model_id": obj.get("pgs_model_id"),
                "adjusted_z_score": obj.get("adjusted_z_score"),
                "percentile": obj.get("percentile"),
                "population_id": obj.get("population_id"),
                "population_percentile": obj.get("population_percentile"),
                "population_z_score": obj.get("population_z_score"),
                "modified": obj.get("modified"),
                "created": obj.get("created"),
            }
        )
        return _obj
