"""Create solveit in Fasthtml for course"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_app_xtras.ipynb.

# %% auto 0
__all__ = ['exception_handlers', 'custom_theme_fp', 'hxrh', 'log_error', 'server_error', 'not_found', 'custom_theme_enabled',
           'has_custom_theme']

# %% ../nbs/06_app_xtras.ipynb
from fasthtml.common import *
from fastcore.utils import *
from monsterui.all import *
from datetime import datetime
from starlette.requests import ClientDisconnect

import json, httpx, traceback

import solveit
from .db import *
from .gateway import *
from .aimsg import *

# %% ../nbs/06_app_xtras.ipynb
def hxrh(cmd:str, id_:str):
    "HTMX response headers for selection mode."
    return HtmxResponseHeaders(trigger_after_settle=json.dumps({"smode:afterSettle":{"cmd":cmd,"id":id_}}))

# %% ../nbs/06_app_xtras.ipynb
def log_error(req, exc):
    "Log error to Discord."
    st = ''.join(traceback.format_exception(type(exc), exc, exc.__traceback__))
    embed = {
        "embeds": [{
            "title": f"🚨`{type(exc).__name__} {str(exc)}`",
            "description": f"**v{solveit.__version__}**",
            "color": 15158332,
            "fields": [
                {"name": "User", "value": os.environ.get('AAI_USER_KEY','Unknown').split(":")[0], "inline": True},
                {"name": "Ref", "value": str(req.headers.get('referer')) if req else "task", "inline": True},
                {"name": "Route", "value": f"{req.url.path}?{req.url.query or ''}" if req else "task", "inline": True},
            ],
            "footer": {"text": datetime.now().strftime('%b %d at %H:%M')}
        }]
    }
    data = {'payload_json': (None, json.dumps(embed)), 'file': ('trace.txt', st, 'text/plain')}
    try: return httpx.post(cfg_solveit['logger_url'], files=data)
    except: pass

# %% ../nbs/06_app_xtras.ipynb
def _err_toast(msg):
    "Toast displayed when an error occurs."
    return Div(
            Div(f"Whoops! {msg}",
            cls="fixed top-4 inset-x-0 mx-auto w-fit bg-red-500 text-white px-4 py-2 rounded",
            hx_on__load="setTimeout(() => this.remove(), 10000)"
        ),
        hx_swap_oob="afterbegin:body"
    )

# %% ../nbs/06_app_xtras.ipynb
@flexicache(time_policy(60*60), maxsize=1)
def _latest_solveit_version():
    "Fetch the latest solveit version number from solve-lp (e.g. 0.0.8)."
    url = cfg_solveit["solvelp_url"]
    if not url: return "unknown"
    try: return httpx.get(f"{url}/solveit_version").text
    except (httpx.HTTPError, AttributeError): return "unknown"

# %% ../nbs/06_app_xtras.ipynb
def _err_msg():
    "Message embedded in the error toast displayed to the user."
    def is_valid(v): return bool(re.match(r'^\d+\.\d+\.\d+$', v))
    lsv = _latest_solveit_version()
    if is_valid(lsv) and lsv > solveit.__version__: return "An error occurred. Please restart Solveit."
    return "An error occurred. We've been notified and are working on a fix."

# %% ../nbs/06_app_xtras.ipynb
def server_error(req, exc):
    "Log the error and inform the user that an error has occurred."
    if not cfg_solveit['logger_url']:
        st = ''.join(traceback.format_exception(type(exc), exc, exc.__traceback__))
        return print(st)
    if req and not req.url.path.endswith('_'): return
    if isinstance(exc, (ClientDisconnect,)):   return
    log_error(req, exc)
    msg = _err_msg()
    if not req: return _err_toast(msg) # task error
    if req.headers.get('HX-Request'): return FtResponse(_err_toast(msg))
    elif req.headers.get("Content-Type") == "application/json": return JSONResponse(msg, status_code=500)
    return Titled(Strong("Whoops!"), P(msg), cls='mx-auto inset-x-0 w-fit')

# %% ../nbs/06_app_xtras.ipynb
def not_found(request: Request, exc):
#     print(request.__dict__, '\n---\n', exc)
    stat = getattr(exc, 'status_code', 404)
    return HTMLResponse(content="not found", status_code=stat)

exception_handlers = { 400:server_error, 404: not_found, 500: server_error }

# %% ../nbs/06_app_xtras.ipynb
custom_theme_fp = Path(cfg_solveit['static_dir']) / "solveit-theme.css"

def custom_theme_enabled(): return feature_enabled('USE_CUSTOM_THEME')
def has_custom_theme(): return custom_theme_enabled() and custom_theme_fp.exists()
