# coding: utf-8

"""
    vivnfm/vi-vnfm.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypeVirtualNic(str, Enum):
    """
    Type of network interface. The type allows for defining how such interface is to be realized, e.g. normal virtual NIC, with direct PCI pass-through, SR-IOV, etc. Note(dmalovan): typeVirtualNic should define how the VM nic should be connected to the host network.   - BRIDGE: In the simple mode VM's are connected to the network backend through a linux \"bridge\".  In masquerade mode, kubevirt allocates internal IP address to the virtual machines and hide them behind NAT.  All egress treaffic is \"SNAT'ed\".  Note(dmalovan): actually don't think that is needed for NFV usecases.  MASQUERADE = 1;  - PATHTHROUGH: PCI Path-through allows a compute instance to have a direct and exclusive access to the physical PCI devices.  - SRIOV: Extension of PCIe that allows a single PCI device (NIC) to be shared among multiple VMs.
    """

    """
    allowed enum values
    """
    BRIDGE = 'BRIDGE'
    PATHTHROUGH = 'PATHTHROUGH'
    SRIOV = 'SRIOV'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypeVirtualNic from a JSON string"""
        return cls(json.loads(json_str))


