import sys
from qtpy.QtWidgets import QWidget, QSizeGrip, QFrame
from qtpy.QtCore import QRect, QSize, Qt
from qtpy.QtGui import QCursor
class Grips:
    def __init__(self, parent, position, disable_color): ...
    def mouseReleaseEvent(self, event): ...
    def resizeEvent(self, event): ...
class Widgets:
    def top_left(self, form): ...
    def top_right(self, form): ...
    def bottom_left(self, form): ...
    def bottom_right(self, form): ...
    def top(self, form): ...
    def bottom(self, form): ...
    def left(self, form): ...
    def right(self, form): ...