# coding: utf-8

"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces. Please note that the Python client library follows Python's naming convention of snake casing for fields, even though they may appear in camel case in the API specification. <p><b>By default this api documentation targets the koverse production server at 'api.app.koverse.com' You can provide the hostname of your koverse instance to this documentation page via the 'host' query param.</p> <p><b>For example providing host - https://koverse-docs.saic.com/api?host=api.myHost.com, will update requests to target the provided host.</b></p> <p><b>Authentication request example with provided host - https://api.myHost.com/authentication</b></p>

    The version of the OpenAPI document: 4.177.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kdp_api.models.ingest_create_request import IngestCreateRequest

class TestIngestCreateRequest(unittest.TestCase):
    """IngestCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestCreateRequest:
        """Test IngestCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestCreateRequest`
        """
        model = IngestCreateRequest()
        if include_optional:
            return IngestCreateRequest(
                dataset_id = '',
                data_source_params = kdp_api.models.data_source_params.Data Source Params(
                    type = 'URL', 
                    connection_info = kdp_api.models.connection_info.Connection Info(
                        urls = - "https://kisp-test.s3-us-west-2.amazonaws.com/nightly_tests/test.csv"
- "https://kisp-test.s3-us-west-2.amazonaws.com/nightly_tests/test.xls"
, 
                        process_as_document = True, 
                        process_with_ocr = True, ), 
                    security_label_info = kdp_api.models.security_label_info.Security Label Info(
                        fields = [
                            ''
                            ], 
                        label = '', 
                        label_handling_policy = 'replace', 
                        parser_class_name = 'simple-parser', 
                        replacement_string = '', ), 
                    security_labeled = True, )
            )
        else:
            return IngestCreateRequest(
        )
        """

    def testIngestCreateRequest(self):
        """Test IngestCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
