DOCSTRING = """\
mfoutparser
by Arthur G. Palmer, III and Michelle L. Gill

A series of python subroutines to read and extract information from the 
STAR format mfout file generated by the program ModelFree.

Unlike the BMRB STAR format, the format used by ModelFree 
uses the data_name field, rather than the save_name field 
and also allows nested loops (the mfout file has loops nested to 
a depth of two only).

`mfoutparser` has been tested on python 3.12. It requires the 
Numpy (tested on version 1.26.4) and Pandas (tested on version 2.2.2) 
libraries. IPython notebook (tested on version 8.27.0) is required to run the
demonstration notebook located in the `examples` directory. Matplotlib 
is required if plotting of the data is desired.

See the `examples` directory in the installation for a demonstration or
run the following from the command line:

python -c 'import mfoutparser as mf; mf.copy_examples()'
"""
