from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class FlagCode(_message.Message):
    __slots__ = ("timestamp", "flag_code")
    class FlagCode(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NOT_AVAILABLE: _ClassVar[FlagCode.FlagCode]
        AF: _ClassVar[FlagCode.FlagCode]
        AL: _ClassVar[FlagCode.FlagCode]
        DZ: _ClassVar[FlagCode.FlagCode]
        AS: _ClassVar[FlagCode.FlagCode]
        AD: _ClassVar[FlagCode.FlagCode]
        AO: _ClassVar[FlagCode.FlagCode]
        AI: _ClassVar[FlagCode.FlagCode]
        AQ: _ClassVar[FlagCode.FlagCode]
        AG: _ClassVar[FlagCode.FlagCode]
        AR: _ClassVar[FlagCode.FlagCode]
        AM: _ClassVar[FlagCode.FlagCode]
        AW: _ClassVar[FlagCode.FlagCode]
        AU: _ClassVar[FlagCode.FlagCode]
        AT: _ClassVar[FlagCode.FlagCode]
        AZ: _ClassVar[FlagCode.FlagCode]
        BS: _ClassVar[FlagCode.FlagCode]
        BH: _ClassVar[FlagCode.FlagCode]
        BD: _ClassVar[FlagCode.FlagCode]
        BB: _ClassVar[FlagCode.FlagCode]
        BY: _ClassVar[FlagCode.FlagCode]
        BE: _ClassVar[FlagCode.FlagCode]
        BZ: _ClassVar[FlagCode.FlagCode]
        BJ: _ClassVar[FlagCode.FlagCode]
        BM: _ClassVar[FlagCode.FlagCode]
        BT: _ClassVar[FlagCode.FlagCode]
        BO: _ClassVar[FlagCode.FlagCode]
        BQ: _ClassVar[FlagCode.FlagCode]
        BA: _ClassVar[FlagCode.FlagCode]
        BW: _ClassVar[FlagCode.FlagCode]
        BV: _ClassVar[FlagCode.FlagCode]
        BR: _ClassVar[FlagCode.FlagCode]
        IO: _ClassVar[FlagCode.FlagCode]
        BN: _ClassVar[FlagCode.FlagCode]
        BG: _ClassVar[FlagCode.FlagCode]
        BF: _ClassVar[FlagCode.FlagCode]
        BI: _ClassVar[FlagCode.FlagCode]
        CV: _ClassVar[FlagCode.FlagCode]
        KH: _ClassVar[FlagCode.FlagCode]
        CM: _ClassVar[FlagCode.FlagCode]
        CA: _ClassVar[FlagCode.FlagCode]
        KY: _ClassVar[FlagCode.FlagCode]
        CF: _ClassVar[FlagCode.FlagCode]
        TD: _ClassVar[FlagCode.FlagCode]
        CL: _ClassVar[FlagCode.FlagCode]
        CN: _ClassVar[FlagCode.FlagCode]
        CX: _ClassVar[FlagCode.FlagCode]
        CC: _ClassVar[FlagCode.FlagCode]
        CO: _ClassVar[FlagCode.FlagCode]
        KM: _ClassVar[FlagCode.FlagCode]
        CD: _ClassVar[FlagCode.FlagCode]
        CG: _ClassVar[FlagCode.FlagCode]
        CK: _ClassVar[FlagCode.FlagCode]
        CR: _ClassVar[FlagCode.FlagCode]
        HR: _ClassVar[FlagCode.FlagCode]
        CU: _ClassVar[FlagCode.FlagCode]
        CW: _ClassVar[FlagCode.FlagCode]
        CY: _ClassVar[FlagCode.FlagCode]
        CZ: _ClassVar[FlagCode.FlagCode]
        CI: _ClassVar[FlagCode.FlagCode]
        DK: _ClassVar[FlagCode.FlagCode]
        DJ: _ClassVar[FlagCode.FlagCode]
        DM: _ClassVar[FlagCode.FlagCode]
        DO: _ClassVar[FlagCode.FlagCode]
        EC: _ClassVar[FlagCode.FlagCode]
        EG: _ClassVar[FlagCode.FlagCode]
        SV: _ClassVar[FlagCode.FlagCode]
        GQ: _ClassVar[FlagCode.FlagCode]
        ER: _ClassVar[FlagCode.FlagCode]
        EE: _ClassVar[FlagCode.FlagCode]
        SZ: _ClassVar[FlagCode.FlagCode]
        ET: _ClassVar[FlagCode.FlagCode]
        FK: _ClassVar[FlagCode.FlagCode]
        FO: _ClassVar[FlagCode.FlagCode]
        FJ: _ClassVar[FlagCode.FlagCode]
        FI: _ClassVar[FlagCode.FlagCode]
        FR: _ClassVar[FlagCode.FlagCode]
        GF: _ClassVar[FlagCode.FlagCode]
        PF: _ClassVar[FlagCode.FlagCode]
        TF: _ClassVar[FlagCode.FlagCode]
        GA: _ClassVar[FlagCode.FlagCode]
        GM: _ClassVar[FlagCode.FlagCode]
        GE: _ClassVar[FlagCode.FlagCode]
        DE: _ClassVar[FlagCode.FlagCode]
        GH: _ClassVar[FlagCode.FlagCode]
        GI: _ClassVar[FlagCode.FlagCode]
        GR: _ClassVar[FlagCode.FlagCode]
        GL: _ClassVar[FlagCode.FlagCode]
        GD: _ClassVar[FlagCode.FlagCode]
        GP: _ClassVar[FlagCode.FlagCode]
        GU: _ClassVar[FlagCode.FlagCode]
        GT: _ClassVar[FlagCode.FlagCode]
        GG: _ClassVar[FlagCode.FlagCode]
        GN: _ClassVar[FlagCode.FlagCode]
        GW: _ClassVar[FlagCode.FlagCode]
        GY: _ClassVar[FlagCode.FlagCode]
        HT: _ClassVar[FlagCode.FlagCode]
        HM: _ClassVar[FlagCode.FlagCode]
        VA: _ClassVar[FlagCode.FlagCode]
        HN: _ClassVar[FlagCode.FlagCode]
        HK: _ClassVar[FlagCode.FlagCode]
        HU: _ClassVar[FlagCode.FlagCode]
        IS: _ClassVar[FlagCode.FlagCode]
        IN: _ClassVar[FlagCode.FlagCode]
        ID: _ClassVar[FlagCode.FlagCode]
        IR: _ClassVar[FlagCode.FlagCode]
        IQ: _ClassVar[FlagCode.FlagCode]
        IE: _ClassVar[FlagCode.FlagCode]
        IM: _ClassVar[FlagCode.FlagCode]
        IL: _ClassVar[FlagCode.FlagCode]
        IT: _ClassVar[FlagCode.FlagCode]
        JM: _ClassVar[FlagCode.FlagCode]
        JP: _ClassVar[FlagCode.FlagCode]
        JE: _ClassVar[FlagCode.FlagCode]
        JO: _ClassVar[FlagCode.FlagCode]
        KZ: _ClassVar[FlagCode.FlagCode]
        KE: _ClassVar[FlagCode.FlagCode]
        KI: _ClassVar[FlagCode.FlagCode]
        KP: _ClassVar[FlagCode.FlagCode]
        KR: _ClassVar[FlagCode.FlagCode]
        KW: _ClassVar[FlagCode.FlagCode]
        KG: _ClassVar[FlagCode.FlagCode]
        LA: _ClassVar[FlagCode.FlagCode]
        LV: _ClassVar[FlagCode.FlagCode]
        LB: _ClassVar[FlagCode.FlagCode]
        LS: _ClassVar[FlagCode.FlagCode]
        LR: _ClassVar[FlagCode.FlagCode]
        LY: _ClassVar[FlagCode.FlagCode]
        LI: _ClassVar[FlagCode.FlagCode]
        LT: _ClassVar[FlagCode.FlagCode]
        LU: _ClassVar[FlagCode.FlagCode]
        MO: _ClassVar[FlagCode.FlagCode]
        MG: _ClassVar[FlagCode.FlagCode]
        MW: _ClassVar[FlagCode.FlagCode]
        MY: _ClassVar[FlagCode.FlagCode]
        MV: _ClassVar[FlagCode.FlagCode]
        ML: _ClassVar[FlagCode.FlagCode]
        MT: _ClassVar[FlagCode.FlagCode]
        MH: _ClassVar[FlagCode.FlagCode]
        MQ: _ClassVar[FlagCode.FlagCode]
        MR: _ClassVar[FlagCode.FlagCode]
        MU: _ClassVar[FlagCode.FlagCode]
        YT: _ClassVar[FlagCode.FlagCode]
        MX: _ClassVar[FlagCode.FlagCode]
        FM: _ClassVar[FlagCode.FlagCode]
        MD: _ClassVar[FlagCode.FlagCode]
        MC: _ClassVar[FlagCode.FlagCode]
        MN: _ClassVar[FlagCode.FlagCode]
        ME: _ClassVar[FlagCode.FlagCode]
        MS: _ClassVar[FlagCode.FlagCode]
        MA: _ClassVar[FlagCode.FlagCode]
        MZ: _ClassVar[FlagCode.FlagCode]
        MM: _ClassVar[FlagCode.FlagCode]
        NA: _ClassVar[FlagCode.FlagCode]
        NR: _ClassVar[FlagCode.FlagCode]
        NP: _ClassVar[FlagCode.FlagCode]
        NL: _ClassVar[FlagCode.FlagCode]
        NC: _ClassVar[FlagCode.FlagCode]
        NZ: _ClassVar[FlagCode.FlagCode]
        NI: _ClassVar[FlagCode.FlagCode]
        NE: _ClassVar[FlagCode.FlagCode]
        NG: _ClassVar[FlagCode.FlagCode]
        NU: _ClassVar[FlagCode.FlagCode]
        NF: _ClassVar[FlagCode.FlagCode]
        MK: _ClassVar[FlagCode.FlagCode]
        MP: _ClassVar[FlagCode.FlagCode]
        NO: _ClassVar[FlagCode.FlagCode]
        OM: _ClassVar[FlagCode.FlagCode]
        PK: _ClassVar[FlagCode.FlagCode]
        PW: _ClassVar[FlagCode.FlagCode]
        PS: _ClassVar[FlagCode.FlagCode]
        PA: _ClassVar[FlagCode.FlagCode]
        PG: _ClassVar[FlagCode.FlagCode]
        PY: _ClassVar[FlagCode.FlagCode]
        PE: _ClassVar[FlagCode.FlagCode]
        PH: _ClassVar[FlagCode.FlagCode]
        PN: _ClassVar[FlagCode.FlagCode]
        PL: _ClassVar[FlagCode.FlagCode]
        PT: _ClassVar[FlagCode.FlagCode]
        PR: _ClassVar[FlagCode.FlagCode]
        QA: _ClassVar[FlagCode.FlagCode]
        RE: _ClassVar[FlagCode.FlagCode]
        RO: _ClassVar[FlagCode.FlagCode]
        RU: _ClassVar[FlagCode.FlagCode]
        RW: _ClassVar[FlagCode.FlagCode]
        BL: _ClassVar[FlagCode.FlagCode]
        SH: _ClassVar[FlagCode.FlagCode]
        KN: _ClassVar[FlagCode.FlagCode]
        LC: _ClassVar[FlagCode.FlagCode]
        MF: _ClassVar[FlagCode.FlagCode]
        PM: _ClassVar[FlagCode.FlagCode]
        VC: _ClassVar[FlagCode.FlagCode]
        WS: _ClassVar[FlagCode.FlagCode]
        SM: _ClassVar[FlagCode.FlagCode]
        ST: _ClassVar[FlagCode.FlagCode]
        SA: _ClassVar[FlagCode.FlagCode]
        SN: _ClassVar[FlagCode.FlagCode]
        RS: _ClassVar[FlagCode.FlagCode]
        SC: _ClassVar[FlagCode.FlagCode]
        SL: _ClassVar[FlagCode.FlagCode]
        SG: _ClassVar[FlagCode.FlagCode]
        SX: _ClassVar[FlagCode.FlagCode]
        SK: _ClassVar[FlagCode.FlagCode]
        SI: _ClassVar[FlagCode.FlagCode]
        SB: _ClassVar[FlagCode.FlagCode]
        SO: _ClassVar[FlagCode.FlagCode]
        ZA: _ClassVar[FlagCode.FlagCode]
        GS: _ClassVar[FlagCode.FlagCode]
        SS: _ClassVar[FlagCode.FlagCode]
        ES: _ClassVar[FlagCode.FlagCode]
        LK: _ClassVar[FlagCode.FlagCode]
        SD: _ClassVar[FlagCode.FlagCode]
        SR: _ClassVar[FlagCode.FlagCode]
        SJ: _ClassVar[FlagCode.FlagCode]
        SE: _ClassVar[FlagCode.FlagCode]
        CH: _ClassVar[FlagCode.FlagCode]
        SY: _ClassVar[FlagCode.FlagCode]
        TW: _ClassVar[FlagCode.FlagCode]
        TJ: _ClassVar[FlagCode.FlagCode]
        TZ: _ClassVar[FlagCode.FlagCode]
        TH: _ClassVar[FlagCode.FlagCode]
        TL: _ClassVar[FlagCode.FlagCode]
        TG: _ClassVar[FlagCode.FlagCode]
        TK: _ClassVar[FlagCode.FlagCode]
        TO: _ClassVar[FlagCode.FlagCode]
        TT: _ClassVar[FlagCode.FlagCode]
        TN: _ClassVar[FlagCode.FlagCode]
        TR: _ClassVar[FlagCode.FlagCode]
        TM: _ClassVar[FlagCode.FlagCode]
        TC: _ClassVar[FlagCode.FlagCode]
        TV: _ClassVar[FlagCode.FlagCode]
        UG: _ClassVar[FlagCode.FlagCode]
        UA: _ClassVar[FlagCode.FlagCode]
        AE: _ClassVar[FlagCode.FlagCode]
        GB: _ClassVar[FlagCode.FlagCode]
        US: _ClassVar[FlagCode.FlagCode]
        UM: _ClassVar[FlagCode.FlagCode]
        UY: _ClassVar[FlagCode.FlagCode]
        UZ: _ClassVar[FlagCode.FlagCode]
        VU: _ClassVar[FlagCode.FlagCode]
        VE: _ClassVar[FlagCode.FlagCode]
        VN: _ClassVar[FlagCode.FlagCode]
        VG: _ClassVar[FlagCode.FlagCode]
        VI: _ClassVar[FlagCode.FlagCode]
        WF: _ClassVar[FlagCode.FlagCode]
        EH: _ClassVar[FlagCode.FlagCode]
        YE: _ClassVar[FlagCode.FlagCode]
        ZM: _ClassVar[FlagCode.FlagCode]
        ZW: _ClassVar[FlagCode.FlagCode]
        AX: _ClassVar[FlagCode.FlagCode]
        XK: _ClassVar[FlagCode.FlagCode]
    NOT_AVAILABLE: FlagCode.FlagCode
    AF: FlagCode.FlagCode
    AL: FlagCode.FlagCode
    DZ: FlagCode.FlagCode
    AS: FlagCode.FlagCode
    AD: FlagCode.FlagCode
    AO: FlagCode.FlagCode
    AI: FlagCode.FlagCode
    AQ: FlagCode.FlagCode
    AG: FlagCode.FlagCode
    AR: FlagCode.FlagCode
    AM: FlagCode.FlagCode
    AW: FlagCode.FlagCode
    AU: FlagCode.FlagCode
    AT: FlagCode.FlagCode
    AZ: FlagCode.FlagCode
    BS: FlagCode.FlagCode
    BH: FlagCode.FlagCode
    BD: FlagCode.FlagCode
    BB: FlagCode.FlagCode
    BY: FlagCode.FlagCode
    BE: FlagCode.FlagCode
    BZ: FlagCode.FlagCode
    BJ: FlagCode.FlagCode
    BM: FlagCode.FlagCode
    BT: FlagCode.FlagCode
    BO: FlagCode.FlagCode
    BQ: FlagCode.FlagCode
    BA: FlagCode.FlagCode
    BW: FlagCode.FlagCode
    BV: FlagCode.FlagCode
    BR: FlagCode.FlagCode
    IO: FlagCode.FlagCode
    BN: FlagCode.FlagCode
    BG: FlagCode.FlagCode
    BF: FlagCode.FlagCode
    BI: FlagCode.FlagCode
    CV: FlagCode.FlagCode
    KH: FlagCode.FlagCode
    CM: FlagCode.FlagCode
    CA: FlagCode.FlagCode
    KY: FlagCode.FlagCode
    CF: FlagCode.FlagCode
    TD: FlagCode.FlagCode
    CL: FlagCode.FlagCode
    CN: FlagCode.FlagCode
    CX: FlagCode.FlagCode
    CC: FlagCode.FlagCode
    CO: FlagCode.FlagCode
    KM: FlagCode.FlagCode
    CD: FlagCode.FlagCode
    CG: FlagCode.FlagCode
    CK: FlagCode.FlagCode
    CR: FlagCode.FlagCode
    HR: FlagCode.FlagCode
    CU: FlagCode.FlagCode
    CW: FlagCode.FlagCode
    CY: FlagCode.FlagCode
    CZ: FlagCode.FlagCode
    CI: FlagCode.FlagCode
    DK: FlagCode.FlagCode
    DJ: FlagCode.FlagCode
    DM: FlagCode.FlagCode
    DO: FlagCode.FlagCode
    EC: FlagCode.FlagCode
    EG: FlagCode.FlagCode
    SV: FlagCode.FlagCode
    GQ: FlagCode.FlagCode
    ER: FlagCode.FlagCode
    EE: FlagCode.FlagCode
    SZ: FlagCode.FlagCode
    ET: FlagCode.FlagCode
    FK: FlagCode.FlagCode
    FO: FlagCode.FlagCode
    FJ: FlagCode.FlagCode
    FI: FlagCode.FlagCode
    FR: FlagCode.FlagCode
    GF: FlagCode.FlagCode
    PF: FlagCode.FlagCode
    TF: FlagCode.FlagCode
    GA: FlagCode.FlagCode
    GM: FlagCode.FlagCode
    GE: FlagCode.FlagCode
    DE: FlagCode.FlagCode
    GH: FlagCode.FlagCode
    GI: FlagCode.FlagCode
    GR: FlagCode.FlagCode
    GL: FlagCode.FlagCode
    GD: FlagCode.FlagCode
    GP: FlagCode.FlagCode
    GU: FlagCode.FlagCode
    GT: FlagCode.FlagCode
    GG: FlagCode.FlagCode
    GN: FlagCode.FlagCode
    GW: FlagCode.FlagCode
    GY: FlagCode.FlagCode
    HT: FlagCode.FlagCode
    HM: FlagCode.FlagCode
    VA: FlagCode.FlagCode
    HN: FlagCode.FlagCode
    HK: FlagCode.FlagCode
    HU: FlagCode.FlagCode
    IS: FlagCode.FlagCode
    IN: FlagCode.FlagCode
    ID: FlagCode.FlagCode
    IR: FlagCode.FlagCode
    IQ: FlagCode.FlagCode
    IE: FlagCode.FlagCode
    IM: FlagCode.FlagCode
    IL: FlagCode.FlagCode
    IT: FlagCode.FlagCode
    JM: FlagCode.FlagCode
    JP: FlagCode.FlagCode
    JE: FlagCode.FlagCode
    JO: FlagCode.FlagCode
    KZ: FlagCode.FlagCode
    KE: FlagCode.FlagCode
    KI: FlagCode.FlagCode
    KP: FlagCode.FlagCode
    KR: FlagCode.FlagCode
    KW: FlagCode.FlagCode
    KG: FlagCode.FlagCode
    LA: FlagCode.FlagCode
    LV: FlagCode.FlagCode
    LB: FlagCode.FlagCode
    LS: FlagCode.FlagCode
    LR: FlagCode.FlagCode
    LY: FlagCode.FlagCode
    LI: FlagCode.FlagCode
    LT: FlagCode.FlagCode
    LU: FlagCode.FlagCode
    MO: FlagCode.FlagCode
    MG: FlagCode.FlagCode
    MW: FlagCode.FlagCode
    MY: FlagCode.FlagCode
    MV: FlagCode.FlagCode
    ML: FlagCode.FlagCode
    MT: FlagCode.FlagCode
    MH: FlagCode.FlagCode
    MQ: FlagCode.FlagCode
    MR: FlagCode.FlagCode
    MU: FlagCode.FlagCode
    YT: FlagCode.FlagCode
    MX: FlagCode.FlagCode
    FM: FlagCode.FlagCode
    MD: FlagCode.FlagCode
    MC: FlagCode.FlagCode
    MN: FlagCode.FlagCode
    ME: FlagCode.FlagCode
    MS: FlagCode.FlagCode
    MA: FlagCode.FlagCode
    MZ: FlagCode.FlagCode
    MM: FlagCode.FlagCode
    NA: FlagCode.FlagCode
    NR: FlagCode.FlagCode
    NP: FlagCode.FlagCode
    NL: FlagCode.FlagCode
    NC: FlagCode.FlagCode
    NZ: FlagCode.FlagCode
    NI: FlagCode.FlagCode
    NE: FlagCode.FlagCode
    NG: FlagCode.FlagCode
    NU: FlagCode.FlagCode
    NF: FlagCode.FlagCode
    MK: FlagCode.FlagCode
    MP: FlagCode.FlagCode
    NO: FlagCode.FlagCode
    OM: FlagCode.FlagCode
    PK: FlagCode.FlagCode
    PW: FlagCode.FlagCode
    PS: FlagCode.FlagCode
    PA: FlagCode.FlagCode
    PG: FlagCode.FlagCode
    PY: FlagCode.FlagCode
    PE: FlagCode.FlagCode
    PH: FlagCode.FlagCode
    PN: FlagCode.FlagCode
    PL: FlagCode.FlagCode
    PT: FlagCode.FlagCode
    PR: FlagCode.FlagCode
    QA: FlagCode.FlagCode
    RE: FlagCode.FlagCode
    RO: FlagCode.FlagCode
    RU: FlagCode.FlagCode
    RW: FlagCode.FlagCode
    BL: FlagCode.FlagCode
    SH: FlagCode.FlagCode
    KN: FlagCode.FlagCode
    LC: FlagCode.FlagCode
    MF: FlagCode.FlagCode
    PM: FlagCode.FlagCode
    VC: FlagCode.FlagCode
    WS: FlagCode.FlagCode
    SM: FlagCode.FlagCode
    ST: FlagCode.FlagCode
    SA: FlagCode.FlagCode
    SN: FlagCode.FlagCode
    RS: FlagCode.FlagCode
    SC: FlagCode.FlagCode
    SL: FlagCode.FlagCode
    SG: FlagCode.FlagCode
    SX: FlagCode.FlagCode
    SK: FlagCode.FlagCode
    SI: FlagCode.FlagCode
    SB: FlagCode.FlagCode
    SO: FlagCode.FlagCode
    ZA: FlagCode.FlagCode
    GS: FlagCode.FlagCode
    SS: FlagCode.FlagCode
    ES: FlagCode.FlagCode
    LK: FlagCode.FlagCode
    SD: FlagCode.FlagCode
    SR: FlagCode.FlagCode
    SJ: FlagCode.FlagCode
    SE: FlagCode.FlagCode
    CH: FlagCode.FlagCode
    SY: FlagCode.FlagCode
    TW: FlagCode.FlagCode
    TJ: FlagCode.FlagCode
    TZ: FlagCode.FlagCode
    TH: FlagCode.FlagCode
    TL: FlagCode.FlagCode
    TG: FlagCode.FlagCode
    TK: FlagCode.FlagCode
    TO: FlagCode.FlagCode
    TT: FlagCode.FlagCode
    TN: FlagCode.FlagCode
    TR: FlagCode.FlagCode
    TM: FlagCode.FlagCode
    TC: FlagCode.FlagCode
    TV: FlagCode.FlagCode
    UG: FlagCode.FlagCode
    UA: FlagCode.FlagCode
    AE: FlagCode.FlagCode
    GB: FlagCode.FlagCode
    US: FlagCode.FlagCode
    UM: FlagCode.FlagCode
    UY: FlagCode.FlagCode
    UZ: FlagCode.FlagCode
    VU: FlagCode.FlagCode
    VE: FlagCode.FlagCode
    VN: FlagCode.FlagCode
    VG: FlagCode.FlagCode
    VI: FlagCode.FlagCode
    WF: FlagCode.FlagCode
    EH: FlagCode.FlagCode
    YE: FlagCode.FlagCode
    ZM: FlagCode.FlagCode
    ZW: FlagCode.FlagCode
    AX: FlagCode.FlagCode
    XK: FlagCode.FlagCode
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    FLAG_CODE_FIELD_NUMBER: _ClassVar[int]
    timestamp: _timestamp_pb2.Timestamp
    flag_code: FlagCode.FlagCode
    def __init__(self, timestamp: _Optional[_Union[_timestamp_pb2.Timestamp, _Mapping]] = ..., flag_code: _Optional[_Union[FlagCode.FlagCode, str]] = ...) -> None: ...
