from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class VesselType(_message.Message):
    __slots__ = ("timestamp", "vessel_type")
    class VesselType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NOT_AVAILABLE: _ClassVar[VesselType.VesselType]
        RESERVED_1: _ClassVar[VesselType.VesselType]
        RESERVED_2: _ClassVar[VesselType.VesselType]
        RESERVED_3: _ClassVar[VesselType.VesselType]
        RESERVED_4: _ClassVar[VesselType.VesselType]
        RESERVED_5: _ClassVar[VesselType.VesselType]
        RESERVED_6: _ClassVar[VesselType.VesselType]
        RESERVED_7: _ClassVar[VesselType.VesselType]
        RESERVED_8: _ClassVar[VesselType.VesselType]
        RESERVED_9: _ClassVar[VesselType.VesselType]
        RESERVED_10: _ClassVar[VesselType.VesselType]
        RESERVED_11: _ClassVar[VesselType.VesselType]
        RESERVED_12: _ClassVar[VesselType.VesselType]
        RESERVED_13: _ClassVar[VesselType.VesselType]
        RESERVED_14: _ClassVar[VesselType.VesselType]
        RESERVED_15: _ClassVar[VesselType.VesselType]
        RESERVED_16: _ClassVar[VesselType.VesselType]
        RESERVED_17: _ClassVar[VesselType.VesselType]
        RESERVED_18: _ClassVar[VesselType.VesselType]
        RESERVED_19: _ClassVar[VesselType.VesselType]
        WIG_ALL: _ClassVar[VesselType.VesselType]
        WIG_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        WIG_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        WIG_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        WIG_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        WIG_RESERVED_25: _ClassVar[VesselType.VesselType]
        WIG_RESERVED_26: _ClassVar[VesselType.VesselType]
        WIG_RESERVED_27: _ClassVar[VesselType.VesselType]
        WIG_RESERVED_28: _ClassVar[VesselType.VesselType]
        WIG_RESERVED_29: _ClassVar[VesselType.VesselType]
        FISHING: _ClassVar[VesselType.VesselType]
        TOWING: _ClassVar[VesselType.VesselType]
        TOWING_LARGE: _ClassVar[VesselType.VesselType]
        DREDGING_UNDERWATER_OPS: _ClassVar[VesselType.VesselType]
        DIVING_OPS: _ClassVar[VesselType.VesselType]
        MILITARY_OPS: _ClassVar[VesselType.VesselType]
        SAILING: _ClassVar[VesselType.VesselType]
        PLEASURE_CRAFT: _ClassVar[VesselType.VesselType]
        RESERVED_38: _ClassVar[VesselType.VesselType]
        RESERVED_39: _ClassVar[VesselType.VesselType]
        HSC_ALL: _ClassVar[VesselType.VesselType]
        HSC_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        HSC_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        HSC_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        HSC_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        HSC_RESERVED_45: _ClassVar[VesselType.VesselType]
        HSC_RESERVED_46: _ClassVar[VesselType.VesselType]
        HSC_RESERVED_47: _ClassVar[VesselType.VesselType]
        HSC_RESERVED_48: _ClassVar[VesselType.VesselType]
        HSC_NO_INFO: _ClassVar[VesselType.VesselType]
        PILOT: _ClassVar[VesselType.VesselType]
        SEARCH_RESCUE: _ClassVar[VesselType.VesselType]
        TUG: _ClassVar[VesselType.VesselType]
        PORT_TENDER: _ClassVar[VesselType.VesselType]
        ANTI_POLLUTION: _ClassVar[VesselType.VesselType]
        LAW_ENFORCEMENT: _ClassVar[VesselType.VesselType]
        SPARE_LOCAL_56: _ClassVar[VesselType.VesselType]
        SPARE_LOCAL_57: _ClassVar[VesselType.VesselType]
        MEDICAL_TRANSPORT: _ClassVar[VesselType.VesselType]
        NONCOMBATANT: _ClassVar[VesselType.VesselType]
        PASSENGER_ALL: _ClassVar[VesselType.VesselType]
        PASSENGER_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        PASSENGER_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        PASSENGER_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        PASSENGER_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        PASSENGER_RESERVED_65: _ClassVar[VesselType.VesselType]
        PASSENGER_RESERVED_66: _ClassVar[VesselType.VesselType]
        PASSENGER_RESERVED_67: _ClassVar[VesselType.VesselType]
        PASSENGER_RESERVED_68: _ClassVar[VesselType.VesselType]
        PASSENGER_NO_INFO: _ClassVar[VesselType.VesselType]
        CARGO_ALL: _ClassVar[VesselType.VesselType]
        CARGO_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        CARGO_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        CARGO_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        CARGO_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        CARGO_RESERVED_75: _ClassVar[VesselType.VesselType]
        CARGO_RESERVED_76: _ClassVar[VesselType.VesselType]
        CARGO_RESERVED_77: _ClassVar[VesselType.VesselType]
        CARGO_RESERVED_78: _ClassVar[VesselType.VesselType]
        CARGO_NO_INFO: _ClassVar[VesselType.VesselType]
        TANKER_ALL: _ClassVar[VesselType.VesselType]
        TANKER_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        TANKER_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        TANKER_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        TANKER_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        TANKER_RESERVED_85: _ClassVar[VesselType.VesselType]
        TANKER_RESERVED_86: _ClassVar[VesselType.VesselType]
        TANKER_RESERVED_87: _ClassVar[VesselType.VesselType]
        TANKER_RESERVED_88: _ClassVar[VesselType.VesselType]
        TANKER_NO_INFO: _ClassVar[VesselType.VesselType]
        OTHER_ALL: _ClassVar[VesselType.VesselType]
        OTHER_HAZARDOUS_A: _ClassVar[VesselType.VesselType]
        OTHER_HAZARDOUS_B: _ClassVar[VesselType.VesselType]
        OTHER_HAZARDOUS_C: _ClassVar[VesselType.VesselType]
        OTHER_HAZARDOUS_D: _ClassVar[VesselType.VesselType]
        OTHER_RESERVED_95: _ClassVar[VesselType.VesselType]
        OTHER_RESERVED_96: _ClassVar[VesselType.VesselType]
        OTHER_RESERVED_97: _ClassVar[VesselType.VesselType]
        OTHER_RESERVED_98: _ClassVar[VesselType.VesselType]
        OTHER_NO_INFO: _ClassVar[VesselType.VesselType]
    NOT_AVAILABLE: VesselType.VesselType
    RESERVED_1: VesselType.VesselType
    RESERVED_2: VesselType.VesselType
    RESERVED_3: VesselType.VesselType
    RESERVED_4: VesselType.VesselType
    RESERVED_5: VesselType.VesselType
    RESERVED_6: VesselType.VesselType
    RESERVED_7: VesselType.VesselType
    RESERVED_8: VesselType.VesselType
    RESERVED_9: VesselType.VesselType
    RESERVED_10: VesselType.VesselType
    RESERVED_11: VesselType.VesselType
    RESERVED_12: VesselType.VesselType
    RESERVED_13: VesselType.VesselType
    RESERVED_14: VesselType.VesselType
    RESERVED_15: VesselType.VesselType
    RESERVED_16: VesselType.VesselType
    RESERVED_17: VesselType.VesselType
    RESERVED_18: VesselType.VesselType
    RESERVED_19: VesselType.VesselType
    WIG_ALL: VesselType.VesselType
    WIG_HAZARDOUS_A: VesselType.VesselType
    WIG_HAZARDOUS_B: VesselType.VesselType
    WIG_HAZARDOUS_C: VesselType.VesselType
    WIG_HAZARDOUS_D: VesselType.VesselType
    WIG_RESERVED_25: VesselType.VesselType
    WIG_RESERVED_26: VesselType.VesselType
    WIG_RESERVED_27: VesselType.VesselType
    WIG_RESERVED_28: VesselType.VesselType
    WIG_RESERVED_29: VesselType.VesselType
    FISHING: VesselType.VesselType
    TOWING: VesselType.VesselType
    TOWING_LARGE: VesselType.VesselType
    DREDGING_UNDERWATER_OPS: VesselType.VesselType
    DIVING_OPS: VesselType.VesselType
    MILITARY_OPS: VesselType.VesselType
    SAILING: VesselType.VesselType
    PLEASURE_CRAFT: VesselType.VesselType
    RESERVED_38: VesselType.VesselType
    RESERVED_39: VesselType.VesselType
    HSC_ALL: VesselType.VesselType
    HSC_HAZARDOUS_A: VesselType.VesselType
    HSC_HAZARDOUS_B: VesselType.VesselType
    HSC_HAZARDOUS_C: VesselType.VesselType
    HSC_HAZARDOUS_D: VesselType.VesselType
    HSC_RESERVED_45: VesselType.VesselType
    HSC_RESERVED_46: VesselType.VesselType
    HSC_RESERVED_47: VesselType.VesselType
    HSC_RESERVED_48: VesselType.VesselType
    HSC_NO_INFO: VesselType.VesselType
    PILOT: VesselType.VesselType
    SEARCH_RESCUE: VesselType.VesselType
    TUG: VesselType.VesselType
    PORT_TENDER: VesselType.VesselType
    ANTI_POLLUTION: VesselType.VesselType
    LAW_ENFORCEMENT: VesselType.VesselType
    SPARE_LOCAL_56: VesselType.VesselType
    SPARE_LOCAL_57: VesselType.VesselType
    MEDICAL_TRANSPORT: VesselType.VesselType
    NONCOMBATANT: VesselType.VesselType
    PASSENGER_ALL: VesselType.VesselType
    PASSENGER_HAZARDOUS_A: VesselType.VesselType
    PASSENGER_HAZARDOUS_B: VesselType.VesselType
    PASSENGER_HAZARDOUS_C: VesselType.VesselType
    PASSENGER_HAZARDOUS_D: VesselType.VesselType
    PASSENGER_RESERVED_65: VesselType.VesselType
    PASSENGER_RESERVED_66: VesselType.VesselType
    PASSENGER_RESERVED_67: VesselType.VesselType
    PASSENGER_RESERVED_68: VesselType.VesselType
    PASSENGER_NO_INFO: VesselType.VesselType
    CARGO_ALL: VesselType.VesselType
    CARGO_HAZARDOUS_A: VesselType.VesselType
    CARGO_HAZARDOUS_B: VesselType.VesselType
    CARGO_HAZARDOUS_C: VesselType.VesselType
    CARGO_HAZARDOUS_D: VesselType.VesselType
    CARGO_RESERVED_75: VesselType.VesselType
    CARGO_RESERVED_76: VesselType.VesselType
    CARGO_RESERVED_77: VesselType.VesselType
    CARGO_RESERVED_78: VesselType.VesselType
    CARGO_NO_INFO: VesselType.VesselType
    TANKER_ALL: VesselType.VesselType
    TANKER_HAZARDOUS_A: VesselType.VesselType
    TANKER_HAZARDOUS_B: VesselType.VesselType
    TANKER_HAZARDOUS_C: VesselType.VesselType
    TANKER_HAZARDOUS_D: VesselType.VesselType
    TANKER_RESERVED_85: VesselType.VesselType
    TANKER_RESERVED_86: VesselType.VesselType
    TANKER_RESERVED_87: VesselType.VesselType
    TANKER_RESERVED_88: VesselType.VesselType
    TANKER_NO_INFO: VesselType.VesselType
    OTHER_ALL: VesselType.VesselType
    OTHER_HAZARDOUS_A: VesselType.VesselType
    OTHER_HAZARDOUS_B: VesselType.VesselType
    OTHER_HAZARDOUS_C: VesselType.VesselType
    OTHER_HAZARDOUS_D: VesselType.VesselType
    OTHER_RESERVED_95: VesselType.VesselType
    OTHER_RESERVED_96: VesselType.VesselType
    OTHER_RESERVED_97: VesselType.VesselType
    OTHER_RESERVED_98: VesselType.VesselType
    OTHER_NO_INFO: VesselType.VesselType
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    VESSEL_TYPE_FIELD_NUMBER: _ClassVar[int]
    timestamp: _timestamp_pb2.Timestamp
    vessel_type: VesselType.VesselType
    def __init__(self, timestamp: _Optional[_Union[_timestamp_pb2.Timestamp, _Mapping]] = ..., vessel_type: _Optional[_Union[VesselType.VesselType, str]] = ...) -> None: ...
