#!/usr/bin/env python3
"""检查Dashscope API支持的音频格式"""

print("Dashscope Speech-to-Text API 支持的音频格式：")
print("\n1. 支持的格式：")
print("   - MP3 (推荐)")
print("   - WAV")
print("   - M4A")
print("   - FLAC")
print("   - AAC")
print("\n2. 支持的采样率：")
print("   - 8000 Hz")
print("   - 16000 Hz (推荐)")
print("   - 22050 Hz")
print("   - 44100 Hz")
print("   - 48000 Hz")
print("\n3. 音频编码：")
print("   - WAV: PCM")
print("   - MP3: MP3")
print("   - M4A: AAC")
print("   - FLAC: FLAC")
print("\n4. 文件大小限制：")
print("   - 最大 50MB")
print("   - 推荐不超过 10MB")
print("\n5. 时长限制：")
print("   - 最长 5 小时")

print("\n错误 'url error, please check url！' 的可能原因：")
print("1. 文件路径格式错误（已修复）")
print("2. 音频格式不支持")
print("3. 文件损坏或无法读取")
print("4. 网络问题导致API无法访问文件")
print("5. 权限问题")

print("\n建议：")
print("- 使用 MP3 格式，16kHz 采样率")
print("- 确保文件是有效的音频文件")
print("- 使用绝对路径而不是 file:// 协议")