editable_parameters_2024 = [
    # DF
    "dotation_forfaitaire.montant_minimum_par_habitant",
    "dotation_forfaitaire.montant_maximum_par_habitant",
    "dotation_forfaitaire.ecretement.seuil_rapport_potentiel_fiscal",
    "dotation_forfaitaire.ecretement.plafond_pourcentage_recettes_max",

    # DSR
    "dotation_solidarite_rurale.seuil_nombre_habitants",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.seuil_nombre_habitants_chef_lieu",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.seuil_part_population_canton",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.exclusion.seuil_part_population_dgf_agglomeration_departement",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.exclusion.seuil_population_dgf_agglomeration",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.exclusion.seuil_population_dgf_maximum_commune_agglomeration",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.exclusion.seuil_population_dgf_chef_lieu_de_canton",
    "dotation_solidarite_rurale.bourg_centre.eligibilite.exclusion.seuil_rapport_pfi_10000",
    "dotation_solidarite_rurale.bourg_centre.attribution.plafond_population",
    "dotation_solidarite_rurale.bourg_centre.attribution.plafond_effort_fiscal",
    "dotation_solidarite_rurale.bourg_centre.attribution.coefficient_zrr",
    "dotation_solidarite_rurale.perequation.seuil_rapport_potentiel_financier",
    "dotation_solidarite_rurale.attribution.poids_potentiel_financier_par_habitant",
    "dotation_solidarite_rurale.attribution.poids_longueur_voirie",
    "dotation_solidarite_rurale.attribution.poids_enfants",
    "dotation_solidarite_rurale.attribution.poids_potentiel_financier_par_hectare",
    "dotation_solidarite_rurale.attribution.plafond_effort_fiscal",
    "dotation_solidarite_rurale.cible.eligibilite.seuil_classement",
    "dotation_solidarite_rurale.cible.eligibilite.indice_synthetique.poids_potentiel_financier",
    "dotation_solidarite_rurale.cible.eligibilite.indice_synthetique.poids_revenu",
    "dotation_solidarite_rurale.perequation.attribution.plancher_ratio_progression",
    "dotation_solidarite_rurale.perequation.attribution.plancher_ratio_progression",
    "dotation_solidarite_rurale.bourg_centre.attribution.plancher_ratio_progression",
    "dotation_solidarite_rurale.bourg_centre.attribution.plafond_ratio_progression",
    "dotation_solidarite_rurale.augmentation_montant",

    # DSU
    "dotation_solidarite_urbaine.eligibilite.seuil_bas_nombre_habitants",
    "dotation_solidarite_urbaine.eligibilite.seuil_haut_nombre_habitants",
    "dotation_solidarite_urbaine.eligibilite.seuil_rapport_potentiel_financier",
    "dotation_solidarite_urbaine.eligibilite.part_eligible_seuil_bas",
    "dotation_solidarite_urbaine.eligibilite.part_eligible_seuil_haut",
    "dotation_solidarite_urbaine.eligibilite.indice_synthetique.poids_potentiel_financier",
    "dotation_solidarite_urbaine.eligibilite.indice_synthetique.poids_logements_sociaux",
    "dotation_solidarite_urbaine.eligibilite.indice_synthetique.poids_aides_au_logement",
    "dotation_solidarite_urbaine.eligibilite.indice_synthetique.poids_revenu",
    "dotation_solidarite_urbaine.attribution.plafond_effort_fiscal",
    "dotation_solidarite_urbaine.attribution.facteur_classement_max",
    "dotation_solidarite_urbaine.attribution.facteur_classement_min",
    "dotation_solidarite_urbaine.attribution.poids_quartiers_prioritaires_ville",
    "dotation_solidarite_urbaine.attribution.poids_zone_franche_urbaine",
    "dotation_solidarite_urbaine.attribution.augmentation_max",
    "dotation_solidarite_urbaine.augmentation_montant",

    # Critères généraux
    "population.plafond_dgf",
]
