import threading
from qtpy.QtCore import Signal, QCoreApplication, Qt
from qtpy.QtWidgets import QDialog, QVBoxLayout
from ..button.loading_icon import LoadingIcon
class LoadingDialog:
    def __init__(self, parent, setVisibleSignal: Signal): ...
    def reTranslate(self): ...
    def set_visible(self, is_show): ...
    def show_dialog(self): ...
    def hide_dialog(self): ...
    def execute(self): ...
    def accept(self): ...
    def reject(self): ...