from typing import Union, Optional

from ..serial import Serial

class ObjectId(Serial):
    def __init__(self, value: Union[str, int]) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def value(self) -> Union[str, int]: ...

class DBTag(Serial):
    def __init__(self, tag: str, value: Union[str, int, ObjectId]) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def db(self) -> str: ...
    @property
    def tag(self) -> ObjectId: ...
    def url(self, taxonomy: Optional[int] = None) -> Optional[str]: ...