from _typeshed import Incomplete

class WorkerMonitor:
    worker_name: Incomplete
    worker_type: Incomplete
    start_time: Incomplete
    last_activity: Incomplete
    task_count: int
    error_count: int
    status: str
    direct_link_port: int
    status_report_thread: Incomplete
    current_tasks: Incomplete
    task_history: Incomplete
    queue_info: Incomplete
    resource_usage: Incomplete
    performance_metrics: Incomplete
    experiment_progress: Incomplete
    experiment_lifecycle: Incomplete
    debug_info: Incomplete
    def __init__(self, worker_name: str, worker_type: str) -> None: ...
    def update_activity(self) -> None: ...
    def increment_step_count(self, exp_id: int = None, direct_exp_id: int = None): ...
    def increment_error_count(self, exp_id: int = None, direct_exp_id: int = None): ...
    def add_current_task(self, task_id: str, task_type: str, exp_id: int = None, direct_exp_id: int = None): ...
    def remove_current_task(self, task_id: str): ...
    def update_queue_info(self, queue_name: str, size: int, details: dict = None): ...
    def update_resource_usage(self, cpu_percent: float, memory_mb: float, disk_usage_mb: float = 0.0): ...
    def update_performance_metrics(self, avg_duration: float, max_duration: float, throughput: float): ...
    def update_experiment_progress(self, exp_id: int = None, direct_exp_id: int = None, steps: int = None, total_steps: int = None, percentage: float = None, progress: str = None): ...
    def get_experiment_progress(self, exp_id: int = None, direct_exp_id: int = None): ...
    def get_all_experiment_progress(self): ...

class PullerMonitor(WorkerMonitor):
    direct_link_task_count: int
    cloud_task_count: int
    def __init__(self, worker_name: str = 'puller') -> None: ...
    def increment_direct_link_task(self) -> None: ...
    def increment_cloud_task(self) -> None: ...
    def record_experiment_title(self, exp_id: int = None, direct_exp_id: int = None, title: str = 'NO TITLE'): ...

class CompilerMonitor(WorkerMonitor):
    compilation_count: int
    compilation_errors: int
    def __init__(self, worker_name: str = 'compiler') -> None: ...
    def increment_compilation(self) -> None: ...
    def increment_compilation_error(self) -> None: ...

class QHALMonitor(WorkerMonitor):
    execution_count: int
    execution_errors: int
    def __init__(self, worker_name: str = 'qhal') -> None: ...
    def increment_execution(self) -> None: ...
    def increment_execution_error(self) -> None: ...

class PostProcessMonitor(WorkerMonitor):
    processing_count: int
    processing_errors: int
    def __init__(self, worker_name: str = 'post_process') -> None: ...
    def increment_processing(self) -> None: ...
    def increment_processing_error(self) -> None: ...

class PusherMonitor(WorkerMonitor):
    push_count: int
    push_errors: int
    def __init__(self, worker_name: str = 'pusher') -> None: ...
    def increment_push(self) -> None: ...
    def increment_push_error(self) -> None: ...
