import sys
from qtpy.QtWidgets import QMainWindow, QVBoxLayout, QApplication, QWidget
from qtpy.QtCore import Qt, QVariantAnimation, QEasingCurve, QSequentialAnimationGroup
from qtpy.QtGui import QPen, QPainter, QColor
from qtmui.material.styles import theme
def get_color_from_label(color): ...
class LinearProgressQuery:
    def __init__(self, key: str, color: str): ...
    def initUI(self): ...
    def startAnime(self): ...
    def updateProgress(self, value): ...
    def paintEvent(self, event): ...
class MyWindow:
    def __init__(self): ...