var FuncNodesPlugin=function(g,w){"use strict";function j(e){const t=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(e){for(const o in e)if(o!=="default"){const c=Object.getOwnPropertyDescriptor(e,o);Object.defineProperty(t,o,c.get?c:{enumerable:!0,get:()=>e[o]})}}return t.default=e,Object.freeze(t)}const s=j(g);var R={exports:{}},f={};/**
 * @license React
 * react-jsx-runtime.production.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var p;function v(){if(p)return f;p=1;var e=Symbol.for("react.transitional.element"),t=Symbol.for("react.fragment");function o(c,r,i){var u=null;if(i!==void 0&&(u=""+i),r.key!==void 0&&(u=""+r.key),"key"in r){i={};for(var a in r)a!=="key"&&(i[a]=r[a])}else i=r;return r=i.ref,{$$typeof:e,type:c,key:u,ref:r!==void 0?r:null,props:i}}return f.Fragment=t,f.jsx=o,f.jsxs=o,f}var m;function _(){return m||(m=1,R.exports=v()),R.exports}var n=_();const E=1e3;function T(e){const t={...e};return t.autosize=!0,t.font={...t.font||{},family:"Arial, Helvetica, sans-serif"},t}function P({value:e,staticMode:t}){const o=s.useRef(null),c=s.useRef(e),r=s.useRef(null),i=s.useRef(0),u=s.useRef(null),a=s.useRef(!1),y=s.useCallback(()=>{r.current&&clearTimeout(r.current);const x=Date.now()-i.current,k=Math.max(0,E-x);r.current=window.setTimeout(async()=>{if(!a.current)return;const d=c.current;if(!d||typeof d!="object"||!("data"in d)||!("layout"in d))return;const D=d.data||[],M=T(d.layout),S={staticPlot:t,displayModeBar:!t,responsive:!0,scrollZoom:!1,doubleClick:!1},h=o.current;if(!(!h||typeof window>"u"||!window.Plotly)){try{await window.Plotly.react(h,D,M,S)}catch(z){console.error("Plotly.react failed:",z)}i.current=Date.now(),r.current=null}},k)},[t]);return s.useEffect(()=>{a.current=!0;const l=o.current;return(()=>{l&&(u.current=new ResizeObserver(()=>{if(l&&window.Plotly)try{window.Plotly.Plots.resize(l)}catch{}}),u.current.observe(l))})(),y(),()=>{if(a.current=!1,r.current&&clearTimeout(r.current),u.current&&u.current.disconnect(),l&&window.Plotly)try{window.Plotly.purge(l)}catch{}}},[]),s.useEffect(()=>{c.current=e,y()},[e,y]),o}const F=({value:e})=>{const t=P({value:e,staticMode:!0});return typeof window>"u"?n.jsx(n.Fragment,{}):!e||typeof e!="object"||!("data"in e)||!("layout"in e)?n.jsx(n.Fragment,{}):n.jsx("div",{className:"funcnodes_plotly_container",style:{width:"100%",height:"100%",pointerEvents:"none"},children:n.jsx("div",{ref:t,style:{width:"100%",height:"100%"}})})},b=({value:e})=>{const t=P({value:e,staticMode:!1});return typeof window>"u"?n.jsx(n.Fragment,{}):!e||typeof e!="object"||!("data"in e)||!("layout"in e)?n.jsx(n.Fragment,{}):n.jsx("div",{className:"funcnodes_plotly_container",style:{width:"100%",height:"100%"},children:n.jsx("div",{ref:t,style:{width:"100%",height:"100%"}})})};return{renderpluginfactory:({})=>({data_preview_renderers:{"plotly.Figure":w.DataViewRendererToDataPreviewViewRenderer(F)},data_view_renderers:{"plotly.Figure":b}}),v:w.LATEST_VERSION}}(React,FuncNodesReactFlow);
