from setuptools import setup, find_packages
from viggocorev2._version import version

with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

REQUIRED_PACKAGES = [
    'alembic==1.16.5',
    'amqp==5.3.1',
    'APScheduler==3.7.0',
    'attrs==21.2.0',
    'backports-datetime-fromisoformat==2.0.3',
    'billiard==4.2.1',
    'blinker==1.9.0',
    'celery==5.3.4',
    'certifi==2021.10.8',
    'chardet==4.0.0',
    'click==8.2.1',
    'click-didyoumean==0.3.1',
    'click-plugins==1.1.1',
    'click-repl==0.3.0',
    'colorama==0.4.4',
    'decorator==5.0.8',
    'et_xmlfile==2.0.0',
    'Flask==3.0.1',
    'Flask-JWT-Extended==4.6.0',
    'Flask-Migrate==4.0.5',
    'Flask-RBAC==0.5.0',
    'Flask-SQLAlchemy==3.1.1',
    'gabbi==2.2.0',
    'greenlet==3.2.4',
    'idna==2.10',
    'iniconfig==1.1.1',
    'itsdangerous==2.2.0',
    'Jinja2==3.1.6',
    'jsonpath-rw==1.4.0',
    'jsonpath-rw-ext==1.2.2',
    'kombu==5.3.7',
    'Mako==1.3.10',
    'MarkupSafe==3.0.2',
    'marshmallow==4.0.0',
    'marshmallow-sqlalchemy==0.30.0',
    'openpyxl==3.0.7',
    'packaging==25.0',
    'pbr==5.6.0',
    'pika==1.2.0',
    'Pillow==9.1.0',
    'pluggy==0.13.1',
    'ply==3.11',
    'prompt_toolkit==3.0.52',
    'py==1.10.0',
    'pyparsing==2.4.7',
    'pytest==6.2.4',
    'python-dateutil==2.9.0.post0',
    'python-editor==1.0.4',
    'pytz==2021.1',
    'PyYAML==6.0',
    'requests==2.25.1',
    'six==1.16.0',
    'sparkpost==1.3.9',
    'SQLAlchemy==2.0.43',
    # 'toml==0.10.2',
    'tomli==2.2.1',
    'typing_extensions==4.15.0',
    'tzdata==2025.2',
    'tzlocal==2.1',
    'urllib3==1.26.5',
    'vine==5.0.0',
    'wcwidth==0.2.5',
    'Werkzeug==3.1.3',
    'wsgi-intercept==1.9.2',
]

setup(
    name="viggocorev2",
    version=version,
    description="ViggocoreV2 Framework",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/viggosistemas/viggocorev2-backend",
    author="Jorge Júnio da Silva",
    author_email="jorgejunioufrn@gmail.com",
    license="Apache-2.0",
    packages=find_packages(exclude=["tests"]),
    include_package_data=True,
    install_requires=REQUIRED_PACKAGES,
    python_requires=">=3.8",
    classifiers=[],
)
