# Copyright (c) 2024 Huawei Technologies Co., Ltd.
#
# openMind is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

from .version import __version__

__all__ = [
    "OM_HOME",
    "OM_HUB_CACHE",
    "REGEX_COMMIT_HASH",
    "default_cache_path",
    "_CACHED_NO_EXIST",
    "ENDPOINT",
    "upload_file",
    "upload_folder",
    "create_commit",
    "om_hub_download",
    "snapshot_download",
    "get_om_file_metadata",
    "om_hub_url",
    "http_get",
    "try_to_load_from_cache",
    "create_repo",
    "delete_repo",
    "repo_info",
    "model_info",
    "list_models",
    "dataset_info",
    "list_datasets",
    "list_metrics",
    "space_info",
    "list_spaces",
    "restart_space",
    "list_repo_tree",
    "whoami",
    "create_branch",
    "delete_branch",
    "get_full_repo_name",
    "get_model_ci_info",
    "OmApi",
    "RepoUrl",
    "RepoFile",
    "RepoFolder",
    "ModelInfo",
    "ModelCiInfo",
    "ModelFilter",
    "DatasetInfo",
    "CommitOperationAdd",
    "CommitOperationDelete",
    "Repository",
    "DatasetCard",
    "DatasetCardData",
    "metadata_update",
    "OmFileSystem",
    "OmHubHTTPError",
    "GatedRepoError",
    "OMValidationError",
    "EntryNotFoundError",
    "AccessWhiteListError",
    "RevisionNotFoundError",
    "LocalEntryNotFoundError",
    "RepositoryNotFoundError",
    "om_raise_for_status",
    "build_om_headers",
    "get_logger",
    "set_verbosity",
    "set_verbosity_info",
    "set_verbosity_error",
    "set_verbosity_debug",
    "set_verbosity_warning",
    "replace_invalid_characters",
]


from openmind_hub.plugins.utils.platform_adapter import (
    OM_HOME,
    OM_HUB_CACHE,
    REGEX_COMMIT_HASH,
    default_cache_path,
    _CACHED_NO_EXIST,
    ENDPOINT,
    om_hub_download,
    get_om_file_metadata,
    om_hub_url,
    http_get,
    try_to_load_from_cache,
    snapshot_download,
    CommitOperationAdd,
    CommitOperationDelete,
    Repository,
    create_repo,
    delete_repo,
    create_commit,
    create_branch,
    delete_branch,
    get_full_repo_name,
    upload_file,
    upload_folder,
    repo_info,
    model_info,
    list_models,
    dataset_info,
    list_datasets,
    list_metrics,
    space_info,
    list_spaces,
    restart_space,
    list_repo_tree,
    whoami,
    OmApi,
    RepoUrl,
    RepoFile,
    RepoFolder,
    ModelInfo,
    ModelFilter,
    DatasetInfo,
    DatasetCard,
    metadata_update,
    DatasetCardData,
    OmFileSystem,
    build_om_headers,
    om_raise_for_status,
    OmHubHTTPError,
    GatedRepoError,
    OMValidationError,
    EntryNotFoundError,
    AccessWhiteListError,
    RevisionNotFoundError,
    LocalEntryNotFoundError,
    RepositoryNotFoundError,
)

from openmind_hub.plugins.openmind.utils.logging import (
    get_logger,
    set_verbosity,
    set_verbosity_info,
    set_verbosity_error,
    set_verbosity_debug,
    set_verbosity_warning,
    replace_invalid_characters,
)

from openmind_hub.plugins.openmind.om_api import (
    get_model_ci_info,
    ModelCiInfo,
)
