from __future__ import annotations
import warnings
from typing import TYPE_CHECKING
import re
from qtpy.QtCore import QSize, Qt
from qtpy.QtGui import QIcon, QPainter, QPixmap
from qtpy.QtWidgets import QApplication
from qtmui.material.styles import useTheme
class PyIconify:
    def __init__(self, key: str, color: Any, flip: Flip, rotate: Any, dir: Any, size: QSize): ...
    def addKey(self, key: str, color: Any, flip: Any, rotate: Any, dir: Any, size: Any, mode: QIcon.Mode, state: QIcon.State): ...
    def _get_theme_color(self, value): ...
    def _is_resource_key(self, key: str): ...
    def _draw_text_fallback(self, key: tuple[str, Any]): ...