{
    "name": "SomConnexio application",
    "version": "16.0.1.0.0",
    "summary": """
        Som Connexió's application with custom Odoo addons as dependencies
        that fulfill the cooperative requirements.
    """,
    "author": "Som Connexió SCCL, Coopdevs Treball SCCL",
    "website": "https://coopdevs.org",
    "license": "AGPL-3",
    "category": "Cooperative Management",
    "depends": [
        "base_rest_somconnexio",
        "contract_api_somconnexio",
        "contract_group_somconnexio",
        "cooperator_api_somconnexio",
        "cooperator_somconnexio",
        "cooperator_sponsorship",
        "correos_somconnexio",
        "crm_lead_api_somconnexio",
        "delivery_somconnexio",
        "filmin_somconnexio",
        "hide_sequence_gaps_warning",
        "hr_assistance_somconnexio",
        "invoice_somconnexio",
        "marginalized_groups_somconnexio",
        "mass_mailing_somconnexio",
        "multimedia_api_somconnexio",
        "multimedia_somconnexio",
        "oficinavirtual_somconnexio",
        "opencell_somconnexio",
        "otrs_somconnexio",
        "product_product_sale_subscription_template",
        "res_partner_api_somconnexio",
        "somconnexio",
        "switchboard_somconnexio",
    ],
    "data": [],
    "demo": [],
    "application": True,
    "installable": True,
}
