
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-03T14:06:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a656bcd3109fa00d05a2df9846c6795c656992eb",
 "version": "0.73.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
