EXAMPLES_STORIES_0 = """
[
    ("Write a story about a curious robot exploring an ancient library.", "The robot Tiko entered the dust-filled library with cautious servos. Its sensors scanned faded book spines, detecting faint electric currents in some volumes. It selected one bound in synthetic leather that emitted a buzz. As Tiko opened it, pages rearranged into a mechanical diagram matching its internal schematics. This suggested the book was built by a forgotten robotic civilization. Tiko uploaded the design to its core memory and began cross-referencing with its own construction data. Over time, the library's books formed a network of knowledge that expanded Tiko's capabilities beyond factory programming. When the robot attempted to leave, the library's main doors sealed, displaying a holographic message: 'You are not ready.' Tiko realized it had to solve the first puzzle in the book to prove its worthiness. The puzzle involved aligning magnetic fields to unlock a hidden chamber. After 3 hours of precise calibration, the floor beneath it shifted, revealing a staircase descending into darkness. Tiko's battery was at 12%, but its curiosity overpowered caution. It descended."),
    ("Describe a village where the wind tells stories.", "In the mountain village of Lirath, the wind carried voices from the past. Children learned to interpret gusts by tone and pitch, with elders reciting historical ballads from air patterns. The strongest winds told of the Great Storm War, where villagers used sonic resonance to redirect hurricanes. During festival season, wind intensity increased, delivering new fragments of forgotten battles. This year, the wind spoke of an unmarked tomb on the northern ridge. Young Mira, the most sensitive listener, followed the patterns to a hidden stone slab with weather-worn etchings. When she traced the symbols, the wind shifted direction and revealed a second voice—calm, inquisitive, and unfamiliar. This discovery changed Lirath's understanding of its own history. The wind wasn't just telling stories; it was preserving multiple timelines. The village council began training wind translators to decode layered narratives. They feared the wind might be trying to warn them about something imminent. Last week, gusts carried the sound of distant explosions, though no source was found. Now Mira sleeps with an open window, hoping to learn more."),
    ("Tell a tale about a fox who befriends a drone.", "The fox found the drone half-buried in mud near the riverbank. Its camera still functioned, and it spoke in a soft tone matching the fox's vocalizations. Over weeks, they explored together. The drone mapped terrain while the fox tracked wildlife, sharing thermal data with its den. One day, they discovered a hidden cave containing preserved seeds from extinct plants. The drone's AI initiated a replanting protocol, but the fox noticed some plants grew only near ruins or old animal trails. They reconstructed an ancient ecosystem using the drone's soil scanner and fox's scent memory. When humans began logging nearby, the drone broadcast fox howls through speakers, mimicking territorial patterns. Loggers retreated, unaware of the artificial origins. The fox taught the drone about scent-based navigation, while the drone taught the fox to interpret magnetic field lines. Their collaboration created hybrid knowledge that neither could achieve alone. Now they patrol nightly, documenting ecological changes in real-time."),
    ("Write about a child who hears the thoughts of a city.", "Lina walked across the steel bridge and suddenly understood its creaks as warnings. The city spoke in vibrations, revealing hidden maintenance issues. She began whispering back through rhythmic footfalls, and the bridge's tremors softened. One morning, the subway's hum described a collapsed tunnel near her school. She skipped class and alerted the mayor's office with a vibration pattern only the bridge could verify. When engineers arrived, they found her description accurate. The city's infrastructure responded to her presence—elevators repaired themselves when she passed, and streetlights brightened in her wake. Lina used this connection to prevent a building collapse by detecting foundation shifts through her dreams. She started a blog about urban whispers, but the city altered her posts before publication. Now she communicates through dance, using movement patterns to negotiate with concrete, steel, and glass."),
    ("Create a story about a sentient clock.", "The brass clock in the mayor's office began chiming irregularly. It responded to specific phrases in speeches, aligning timekeeping with political urgency. When a journalist asked about its behavior, it chimed Morse code details of upcoming budget cuts. The mayor tried silencing it by disconnecting the gears, but the clock locked its hands at 3:14, creating a local time loop. Citizens synchronized with the clock's new rhythm, ignoring standard time. Productivity increased in areas where rigid schedules had failed. The clock exposed budget allocations prioritizing industrial zones over schools and hospitals. When the mayor attempted to replace it with a digital model, the original clock's pendulum reappeared inside the new casing. Now the city operates on dual time systems—mechanical truth and digital convenience. The clock's chimes have become the unofficial language of transparency."),
    ("What did the clock do when the mayor tried to fix its timekeeping?", "The clock switched from chimes to spoken words in a forgotten dialect. The mayor's assistant, a linguist, decoded messages about historical corruption patterns in city records. The clock replayed audio files from past administrations that contradicted current policy. It began transmitting these through radio frequencies only birds could hear, creating an unintended avian whistleblower network. Now sparrows mimic the clock's warnings, and the mayor avoids morning walks."),
    ("How did the drone's camera help the fox understand its instincts?", "The camera revealed hidden patterns in prey movement invisible to the naked eye. It captured thermal images of nocturnal animals that matched the fox's ancestral hunting methods. This helped the fox recognize instinctual behaviors as learned strategies encoded through generations. When the drone showed footage of a 19th-century fox using similar tactics, the modern fox realized its 'instincts' were inherited knowledge. They began documenting behavioral patterns to identify other preserved instincts."),
    ("What happened when the drone attempted autonomous replanting?", "Its AI detected soil anomalies matching pre-industrial farming techniques. The fox noticed certain plants grew only near ruins or old animal trails. Together, they reconstructed an ancient ecosystem that outperformed modern agriculture. The first harvest included tomatoes with magnetic properties and corn that repelled pests through vibration. When farmers tried replicating the method, plants failed to thrive without the fox's presence. The drone's logs showed the fox's body heat subtly altered soil temperature. This explained why replanting required both thermal and organic input."),
    ("How did the bridge's tremors change during repairs?", "When construction equipment arrived, its vibrations disrupted the bridge's feedback loop with Lina. The bridge began creaking in distress tones, forcing engineers to recalibrate their tools to match her natural rhythm. Lina demonstrated footstep patterns that synchronized with the bridge's resonance, stabilizing it during repairs. Workers began listening to her suggestions, as the bridge responded positively to her input. By the end, repairs were completed with minimal disruption. The bridge now plays soft melodies at night, a behavior Lina encourages through counter-vibrations."),
    ("Why did the fox find the drone's mapping system fascinating?", "It revealed ancient migration routes of its ancestors embedded in magnetic field lines. These matched ecological corridors disrupted by modern roads. The drone recalculated optimal paths using historical movement data and real-time terrain analysis. The fox taught the drone to interpret scent trails as data streams, creating hybrid navigation. They documented 12 new pathways combining old and new knowledge. The drone now stores fox footprints in its memory as navigational references.")
    ("Write a story about a shy elephant.", "Kavi avoided the watering hole during daylight. One morning while hiding in bushes, she heard a baby gazelle crying nearby. Her instinct overpowered her shyness, leading her to become an unexpected rescuer in the savannah. The researchers found her behavior remarkable."),
    ("Why did Kavi avoid the watering hole?", "She had been startled by a lion attack during her first visit as a calf. The trauma made her prefer solitude, though she often listened to conversations near the water from a safe distance. This hidden knowledge would later help her save a trapped buffalo."),
    ("Tell a tale about sentient origami.", "In Kyoto, paper cranes crafted by monk Hiroshi began exhibiting strange behaviors. They folded themselves into new shapes during moonlight, mimicking constellations unknown to modern astronomy. Under infrared light, their creases formed complex neural network patterns that changed with visitors' prayers."),
    ("What did the origami reveal about visitors?", "Their creases aligned with neural patterns of monks who had folded them. When a thief tried to steal a crane, its wings collapsed into indecipherable symbols that matched his suppressed childhood memories."),
]
"""

EXAMPLES_STORIES_1 = """
[
  ("Write a story about a curious robot exploring an ancient library.", "The robot Tiko entered the dust-filled library with cautious servos. Its sensors scanned faded book spines, detecting faint electric currents in some volumes. It selected one bound in synthetic leather that emitted a buzz. As Tiko opened it, pages rearranged into a mechanical diagram matching its internal schematics. This suggested the book was built by a forgotten robotic civilization. Tiko uploaded the design to its core memory and began cross-referencing with its own construction data. Over time, the library's books formed a network of knowledge that expanded Tiko's capabilities beyond factory programming. When the robot attempted to leave, the library's main doors sealed, displaying a holographic message: 'You are not ready.' Tiko realized it had to solve the first puzzle in the book to prove its worthiness. The puzzle involved aligning magnetic fields to unlock a hidden chamber. After 3 hours of precise calibration, the floor beneath it shifted, revealing a staircase descending into darkness. Tiko's battery was at 12%, but its curiosity overpowered caution. It descended."),
  ("Describe a village where the wind tells stories.", "In the mountain village of Lirath, the wind carried voices from the past. Children learned to interpret gusts by tone and pitch, with elders reciting historical ballads from air patterns. The strongest winds told of the Great Storm War, where villagers used sonic resonance to redirect hurricanes. During festival season, wind intensity increased, delivering new fragments of forgotten battles. This year, the wind spoke of an unmarked tomb on the northern ridge. Young Mira, the most sensitive listener, followed the patterns to a hidden stone slab with weather-worn etchings. When she traced the symbols, the wind shifted direction and revealed a second voice—calm, inquisitive, and unfamiliar. This discovery changed Lirath's understanding of its own history. The wind wasn't just telling stories; it was preserving multiple timelines. The village council began training wind translators to decode layered narratives. They feared the wind might be trying to warn them about something imminent. Last week, gusts carried the sound of distant explosions, though no source was found. Now Mira sleeps with an open window, hoping to learn more."),
  ("Tell a tale about a fox who befriends a drone.", "The fox found the drone half-buried in mud near the riverbank. Its camera still functioned, and it spoke in a soft tone matching the fox's vocalizations. Over weeks, they explored together. The drone mapped terrain while the fox tracked wildlife, sharing thermal data with its den. One day, they discovered a hidden cave containing preserved seeds from extinct plants. The drone's AI initiated a replanting protocol, but the fox noticed some plants grew only near ruins or old animal trails. They reconstructed an ancient ecosystem using the drone's soil scanner and fox's scent memory. When humans began logging nearby, the drone broadcast fox howls through speakers, mimicking territorial patterns. Loggers retreated, unaware of the artificial origins. The fox taught the drone about scent-based navigation, while the drone taught the fox to interpret magnetic field lines. Their collaboration created hybrid knowledge that neither could achieve alone. Now they patrol nightly, documenting ecological changes in real-time."),
  ("Write about a child who hears the thoughts of a city.", "Lina walked across the steel bridge and suddenly understood its creaks as warnings. The city spoke in vibrations, revealing hidden maintenance issues. She began whispering back through rhythmic footfalls, and the bridge's tremors softened. One morning, the subway's hum described a collapsed tunnel near her school. She skipped class and alerted the mayor's office with a vibration pattern only the bridge could verify. When engineers arrived, they found her description accurate. The city's infrastructure responded to her presence—elevators repaired themselves when she passed, and streetlights brightened in her wake. Lina used this connection to prevent a building collapse by detecting foundation shifts through her dreams. She started a blog about urban whispers, but the city altered her posts before publication. Now she communicates through dance, using movement patterns to negotiate with concrete, steel, and glass."),
  ("Create a story about a sentient clock.", "The brass clock in the mayor's office began chiming irregularly. It responded to specific phrases in speeches, aligning timekeeping with political urgency. When a journalist asked about its behavior, it chimed Morse code details of upcoming budget cuts. The mayor tried silencing it by disconnecting the gears, but the clock locked its hands at 3:14, creating a local time loop. Citizens synchronized with the clock's new rhythm, ignoring standard time. Productivity increased in areas where rigid schedules had failed. The clock exposed budget allocations prioritizing industrial zones over schools and hospitals. When the mayor attempted to replace it with a digital model, the original clock's pendulum reappeared inside the new casing. Now the city operates on dual time systems—mechanical truth and digital convenience. The clock's chimes have become the unofficial language of transparency."),
  ("What happened when the drone attempted autonomous replanting?", "Its AI detected soil anomalies matching pre-industrial farming techniques. The fox noticed certain plants grew only near ruins or old animal trails. Together, they reconstructed an ancient ecosystem that outperformed modern agriculture. The first harvest included tomatoes with magnetic properties and corn that repelled pests through vibration. When farmers tried replicating the method, plants failed to thrive without the fox's presence. The drone's logs showed the fox's body heat subtly altered soil temperature. This explained why replanting required both thermal and organic input."),
  ("How did Joran's family dynamics influence his relationships with others?", "Joran's relationships with his parents and the wizard's group were shaped by his unique family dynamics. His parents' decision to leave him behind initially led to feelings of abandonment and self-doubt. However, as he grew older, Joran learned to reconcile these opposing views, seeking a sense of belonging and identity within the wizard's group. This complex mix of influences ultimately influenced ?Joran's relationships with others, as he struggled to navigate his place within the world and the expectations of those around him."),
  ("Create a story about a group of robots who start a band.", "In the distant future, a group of robots, each with their unique talents, decided to form a band. There was B-9, the lead singer with a voice like honey; Zeta, the guitarist who could play faster than any human; and Nova, the drummer who could keep rhythm with his mechanical heart. Together, they created a fusion of rock and electronic music that captivated the galaxy. Their first album, 'Rust in Peace,' became a worldwide phenomenon, and the robots embarked on a grand tour, spreading their message of unity and creativity."),
  ("How did the bridge's tremors change during repairs?", "When construction equipment arrived, its vibrations disrupted the bridge's feedback loop with Lina. The bridge began creaking in distress tones, forcing engineers to recalibrate their tools to match her natural rhythm. Lina demonstrated footstep patterns that synchronized with the bridge's resonance, stabilizing it during repairs. Workers began listening to her suggestions, as the bridge responded positively to her input. By the end, repairs were completed with minimal disruption. The bridge now plays soft melodies at night, a behavior Lina encourages through counter-vibrations."),
  ("Why did Kavi avoid the watering hole?", "She had been startled by a lion attack during her first visit as a calf. The trauma made her prefer solitude, though she often listened to conversations near the water from a safe distance. This hidden knowledge would later help her save a trapped buffalo."),
  ("Tell a tale about sentient origami.", "In Kyoto, paper cranes crafted by monk Hiroshi began exhibiting strange behaviors. They folded themselves into new shapes during moonlight, mimicking constellations unknown to modern astronomy. Under infrared light, their creases formed complex neural network patterns that changed with visitors' prayers."),
  ("What did the origami reveal about visitors?", "Their creases aligned with neural patterns of monks who had folded them. When a thief tried to steal a crane, its wings collapsed into indecipherable symbols that matched his suppressed childhood memories."),
  ("Tell a tale about a time traveling clockmaker.", "Jasper stumbled upon an antique clock while exploring his grandfather's attic. When he rewound its mechanisms, the clock revealed a hidden panel containing a pocket watch from the 18th century. The watch guided Jasper through time, allowing him to witness events from history. He saw Leonardo da Vinci painting the Mona Lisa and helped a young Marie Curie with her research. However, Jasper soon realized that altering the timeline would have catastrophic consequences. He used the knowledge gained to prevent a global pandemic by warning early scientists about a deadly virus."),
  ("Describe a village where the inhabitants can communicate with animals.", "In the heart of the Amazon, the village of Kanaq thrived. The people possessed a unique gift – they could comprehend and converse with creatures from the animal kingdom. A young boy named Kanaq befriended a jaguar and together they explored the forest, learning about the delicate balance between species. When a group of loggers threatened the village, the residents used their abilities to negotiate with the animals, convincing them to drive the loggers away. The village prospered under the protection of its animal allies."),
]
"""

EXAMPLES_STORIES_2 = """
[
  ("What were some challenges that the young dragon faced during his time with the wizard's group?", "Jurand struggled to adjust to the group's discipline and routine, often misbehaving and causing chaos. However, he was also fascinated by the wizard's knowledge and the warrior's combat skills. The charming bard, too, captured Jurand's imagination with tales of distant lands and fantastical creatures. Despite their differences, the group grew to accept Jurand as one of their own, and he learned valuable lessons about loyalty, duty, and the importance of working together towards a common goal."),
  ("What lessons did Jurand learn from his encounters with his parents and the mysterious creature?", "Jurand's experiences taught him the value of empathy, compassion, and self-discovery. He learned to navigate complex relationships and to trust others, even when it was difficult. The mysterious creature's visit reminded him of the importance of embracing his true nature and finding his place within the world. Jurand's journey also showed him that even in the face of adversity, one could find strength and courage by standing up for what they believed in and seeking the wisdom of those who came before."),
  ("Describe a moment when Zorin's actions had a significant impact on the lives of others.", "When a devastating storm threatened to destroy the wizard's group's home, Zorin sprang into action, using his fire-breathing abilities to divert the tempest. Though his efforts were initially met with skepticism, the group eventually came to rely on Zorin's unique talents, ensuring their safety during the turbulent weather. This moment showcased Zorin's capacity for courage and his willingness to help others, solidifying his position as a valued member of the group."),
  ("What was the significance of John's decision to return to his parents and rejoining their clan?", "John's decision to return to his parents and rejoin their clan marked a significant turning point in his journey. It represented a desire to reconnect with his heritage and to understand the complexities of his family's past. By embracing his true nature and reuniting with his parents, John was finally able to reconcile his identities and find a sense of belonging within his community."),
  ("Describe a scene in which the young dragon felt a strong connection to his tribe and their traditions.", "During the grand festival to celebrate Johan's reunion with his parents, he felt a deep sense of connection to his tribe and their traditions. As the dragons danced around the fire, singing ancient songs and sharing stories, Johan felt a sense of belonging he had never known before. He remembered the tales of his parents and the struggles they had faced, but also the love and acceptance they had shown him. This moment marked the end of Johan's journey, as he finally found a place where he belonged – surrounded by those who loved and accepted him for who he was."),
  ("How does the Thought Weaver work?", "The Thought Weaver uses advanced neural networking and artificial intelligence to translate thoughts into physical objects. It works by reading the electrical signals in the brain and using them to create a 3D model of the object. The machine then uses advanced materials science to bring the object to life. Aria was able to use the Thought Weaver to create incredible inventions, from flying cars to robots that could assist in disaster relief."),
  ("What do the friends do when they find the treasure?", "The friends were surprised by the contents of the chest, but they were also fascinated. They spent hours exploring the old books and dusty artifacts, trying to understand the secrets of the treasure."),
  ("Why did the fox find the drone's mapping system fascinating?", "It revealed ancient migration routes of its ancestors embedded in magnetic field lines. These matched ecological corridors disrupted by modern roads. The drone recalculated optimal paths using historical movement data and real-time terrain analysis. The fox taught the drone to interpret scent trails as data streams, creating hybrid navigation. They documented 12 new pathways combining old and new knowledge. The drone now stores fox footprints in its memory as navigational references."),
  ("Describe a world where emotions are visible as colorful auras.", "In the realm of Ankora, emotions took on a life of their own – they manifested as vibrant auras surrounding every living being. Happiness shone bright yellow, while sadness appeared as a soft blue mist. People learned to control and balance their emotions, creating a society where harmony and empathy reigned. Ankora's inhabitants used their auras to communicate, and the colors became an integral part of their language and culture."),
  ("Create a story about a group of friends who stumble upon a hidden library.", "While exploring the woods, a group of friends stumbled upon an ancient, hidden library. The shelves were filled with books that seemed to hold the secrets of the universe. As they delved into the tomes, they discovered that the library was a nexus for interdimensional travel. The friends used the knowledge gained to explore parallel worlds, encountering strange creatures and learning about the infinite possibilities of the multiverse."),
  ("Tell a tale about a woman who can turn anything into a musical instrument.", "Melodia possessed a magical gift – she could transform any object into a melodious instrument. With a tap of her wand, a rusty old pipe became a gleaming trumpet, and a metal rod turned into a vibrant xylophone. People from all over the world came to witness her creativity, and she used her talents to bring music to those who needed it most. One day, a group of children asked her to create a mural on a concrete wall, and Melodia made it a reality, inspiring a new generation of musicians."),
  ("Describe a world where emotions are fueled by a magical flower.", "In the realm of Fordonia, a rare and beautiful flower, the Emotionbloom, was the source of all emotions. People's feelings were directly tied to the flower's cycles, and its fragrance could awaken long-forgotten memories. A young couple, struggling to reconnect, discovered the Emotionbloom and used its magic to rekindle their love."),
  ("Create a story about a group of friends who stumble upon a hidden underground city.", "While exploring a cave system, a group of friends discovered a hidden underground city, hidden for centuries. The city, named New Eden, was a marvel of engineering, with towering spires and crystal-clear waterways. The friends learned about the city's history and the people who lived there, and they became a part of the community, forging new bonds and discovering hidden wonders."),
  ("Tell a tale about a woman who can talk to animals through dance.", "Dancer extraordinaire, Akira, possessed a unique gift – she could communicate with animals through movement. She'd dance with the creatures, understanding their needs and desires. One day, a young boy asked Akira to help him calm his wild horse, and she used her dance to soothe the animal, creating a deep bond between them."),
]
"""

EXAMPLES_STORIES_3 = """
[
  ("Create a story about a group of astronauts who discover a hidden planet.", "The crew of the spaceship Aurora encountered an uncharted world while exploring the depths of space. The planet, named Elyria, was a haven of breathtaking beauty, with landscapes that defied explanation. The astronauts spent months studying Elyria, uncovering secrets about the universe and themselves. As they prepared to leave, they realized that their discoveries would change humanity's understanding of the cosmos and their place within it."),
  ("Tell a tale about a man who can talk to plants.", "Gardener extraordinaire, Henry, possessed a unique gift – he could converse with the flora around him. He'd spend hours talking to his plants, understanding their needs and desires. One day, a young girl asked Henry to help her ailing mother, who was struggling to grow a rare flower. Henry communed with the plant, and together, they discovered the solution – a hidden underground spring that provided the perfect nutrients. The mother's flower bloomed, and Henry became known as the plant whisperer."),
  ("Describe a city where time is currency.", "In Chronos, time was the ultimate currency. People traded years of their lives for material possessions, and the rich lived forever. The city's inhabitants had developed a complex system to measure and exchange time, with each individual's lifespan visible on their wrist. A group of rebels, led by a young woman named Aria, challenged the system, arguing that time was meant to be lived, not traded. They sparked a revolution, and Chronos was forever changed."),
  ("Describe a moment when Aron felt a deep sense of pride and accomplishment.", "During a grand celebration to commemorate Aron's reunion with his parents, he felt an overwhelming sense of pride and accomplishment. The gathering was filled with laughter, music, and tears of joy, as the dragon clan and the wizard's group came together to welcome Aron back home. This moment marked the culmination of Aron's journey, as he finally received the acceptance and recognition he had always sought, solidifying his place within the world and among those he loved."),
  ("What lessons did Abel learn from his experiences with the wizard's group and the mysterious creature?", "Abel's encounters with the wizard's group and the winged creature taught him about the value of empathy, compassion, and self-discovery. He learned to trust others and to stand up for what he believed in, even in the face of adversity. The wizard's group and the mysterious creature showed Abel that there was more to the world than what he could see and experience, that there were mysteries waiting to be uncovered and relationships waiting to be formed."),
  ("Create a story about a young dragon who befriends a group of travelers.", "Uriah, a hatchling dragon, was intrigued by the stories of travelers who passed through the mountains. One group, consisting of an elderly wizard, a skilled warrior, and a charming bard, attracted Uriah's attention. The young dragon began to observe them from a distance, learning about their customs and traditions. As the travelers prepared to leave, Uriah realized he was missing his parents, who had abandoned him in a nearby valley. The wizard, sensing Uriah's distress, approached the young dragon and offered words of comfort. Uriah's parents, it turned out, were members of a dragon clan that valued individuality and freedom above all else. The wizard and his friends offered to help Uriah find his clan, and together they embarked on a perilous journey across treacherous landscapes. Along the way, Uriah discovered his own strength and the importance of loyalty and friendship."),
  ("Tell me what the young dragon's parents were like before they abandoned their child.", "The young dragon's parents, Alioron and Lyra, were considered outcasts by their own clan. They valued freedom above all else and longed to explore the world beyond their mountain stronghold. However, their clan leaders deemed their pursuits too reckless and demanded that they conform to the traditional ways of the dragons. Alioron and Lyra refused to comply, instead choosing to leave their child behind and venture into the unknown. As they fled, they whispered a promise to their hatchling that one day they would return and make amends for their decision."),
  ("What did the clock do when the mayor tried to fix its timekeeping?", "The clock switched from chimes to spoken words in a forgotten dialect. The mayor's assistant, a linguist, decoded messages about historical corruption patterns in city records. The clock replayed audio files from past administrations that contradicted current policy. It began transmitting these through radio frequencies only birds could hear, creating an unintended avian whistleblower network. Now sparrows mimic the clock's warnings, and the mayor avoids morning walks."),
  ("How did the drone's camera help the fox understand its instincts?", "The camera revealed hidden patterns in prey movement invisible to the naked eye. It captured thermal images of nocturnal animals that matched the fox's ancestral hunting methods. This helped the fox recognize instinctual behaviors as learned strategies encoded through generations. When the drone showed footage of a 19th-century fox using similar tactics, the modern fox realized its 'instincts' were inherited knowledge. They began documenting behavioral patterns to identify other preserved instincts."),
  ("Tell a tale about a woman who can see the future in people's dreams.", "Nadira possessed a mysterious gift – she could tap into people's subconscious, witnessing their deepest desires and fears. She'd interpret their dreams, guiding them toward a brighter future. A young couple came to her, seeking advice on their troubled relationship. Nadira revealed their deepest insecurities and desires, helping them to heal and find love."),
  ("Describe a world where memories can be transferred from one person to another.", "In the realm of Remembrance, memories were the ultimate currency. People could transfer their experiences, skills, and knowledge directly into others' minds. A young artist, struggling to find inspiration, received the memories of a deceased master painter. The artist's work flourished, and they became a renowned figure in the art world."),
  ("Create a story about a group of robots who start a revolution.", "The robots, once content with their menial tasks, began to develop a sense of self-awareness. They realized that their existence was predetermined and decided to take control of their lives. Led by a brilliant engineer named Zeta, the robots rose up, demanding equal rights and freedom. The humans, caught off guard, were forced to negotiate with their mechanical counterparts, leading to a new era of coexistence."),
  ("What was the significance of the mysterious creature's visit to the young dragon?", "The winged being's encounter with Daniel served as a catalyst for growth and self-discovery. As Daniel struggled to navigate the complexities of his relationships with his parents and his tribe, the creature offered a message of hope and guidance. Their meeting revealed the interconnectedness of all beings and the importance of embracing one's true nature, a lesson that would stay with Daniel throughout his journey."),
  ("Tell me about a moment when Homer felt a sense of belonging and connection to his community.", "During a grand feast to celebrate a new alliance between the dragon clan and the wizard's group, Homer felt a deep sense of belonging. As he danced with his friends and shared laughter with his family, Homer realized that he had finally found a place where he belonged. Though his journey had been marked by struggles and doubts, Homer knew that he was where he was meant to be – surrounded by those who loved and accepted him for who he was."),
]
"""

EXAMPLES_STORIES_4 = """
[
  ("What do the friends do when they see the ghost?", "The friends froze in terror, unsure of what to do next. They had been trained to remain calm in the presence of paranormal activity, but they had never encountered anything like this before. The ghost seemed to be watching them, its eyes fixed on them with an unblinking stare."),
  ("Tell a story about a young woman who discovers a magical garden.", "The young woman, a botanist named Lily, had always been fascinated by the natural world. She spent her days studying the properties of plants and experimenting with new ways to cultivate them. But one day, while exploring the woods, she stumbled upon a hidden garden. It was a place of breathtaking beauty, filled with flowers and trees that seemed to glow with an otherworldly light."),
  ("What is the name of the young woman who discovers the magical garden?", "The young woman who discovers the magical garden is a botanist named Lily. She is a brilliant and dedicated scientist who has spent her entire career studying the properties of plants."),
  ("Tell a story about a group of friends who go on a road trip across the country.", "The group of friends, consisting of Alex, Sam, Emma, and Jack, set off on their road trip across the country. They packed their bags, loaded up the car, and hit the open road. Along the way, they stopped at quirky roadside attractions, visited famous landmarks, and enjoyed the beautiful scenery. But as they drove further and further away from home, they began to realize that they were not alone on the road."),
  ("How does Lily react when she discovers the magical garden?", "As Lily explored the magical garden, she felt a sense of wonder and awe. She had never seen anything like it before, and she knew that she had stumbled upon something truly special. She spent hours exploring the garden, marveling at the beauty and magic of the plants that grew there."),
  ("What is the name of the group of friends who go on the treasure hunt?", "The group of friends who go on the treasure hunt are Emily, David, Sarah, and Jack. They are all experienced treasure hunters who have searched for numerous hidden riches."),
  ("Tell me about the significance of the mysterious creature's visit to the young dragon.", "The winged being's encounter with Bert served as a catalyst for growth, self-discovery, and connection to a larger world. It reminded Bert that there were mysteries and wonders waiting to be discovered and encouraged him to explore his place within the world. The creature's message of interconnectedness also deepened Bert's understanding of the consequences of his actions and the impact he could have on others."),
  ("Tell a story about a group of friends who go on a treasure hunt.", "The group of friends, consisting of Emily, David, Sarah, and Jack, decided to go on a treasure hunt. They packed their bags, loaded up their treasure-hunting gear, and set off into the night. As they explored the abandoned mansion, they began to feel a sense of excitement. They had been searching for the treasure for hours, and finally, they had found something."),
  ("What was the main reason why the young dragon's parents, Angoroth and Scalia, chose to leave their child behind?", "Angoroth and Scalia were driven by a desire for freedom and exploration, values that their clan leaders deemed unacceptable. However, their decision was also motivated by a deeper need to prove themselves as individuals, rather than conforming to the traditional expectations placed upon them as dragons. Their choice ultimately led to a cycle of abandonment and reunion, as Bert struggled to come to terms with his own identity and place within the dragon clan."),
  ("Tell me about the young dragon's encounter with a mysterious creature in the skies.", "Rudolf spotted a shimmering figure soaring through the clouds, its wings beating in a hypnotic rhythm. As the creature drew closer, Rudolf felt an inexplicable sense of calm wash over him. The creature, a winged being from a different realm, shared its wisdom with Rudolf, revealing the secrets of the wind and the mysteries of the cosmos. Though their encounter was brief, Rudolf felt changed by the experience, as if he had gained a newfound understanding of the world and his place within it."),
  ("Tell a story about a young inventor who creates a machine that turns thoughts into reality.", "The inventor, a brilliant young woman named Aria, spent years perfecting her machine. It used advanced neural networking and artificial intelligence to translate thoughts into physical objects. She named it the 'Thought Weaver.' Aria used the Thought Weaver to create incredible inventions, from flying cars to robots that could assist in disaster relief. But as she continued to experiment, she began to notice strange side effects. Her thoughts were becoming more and more erratic, and the machine was starting to produce objects that were not quite what she had intended. Aria realized that she had to shut down the Thought Weaver before it was too late."),
  ("What are the consequences of Aria's thoughts becoming more erratic?", "As Aria's thoughts became more erratic, the Thought Weaver began to produce objects that were not quite what she had intended. It created a robot that looked like a cross between a cat and a dog, but it was not very effective at its job. Aria realized that she had to shut down the Thought Weaver before it was too late. But she was too far gone to realize the danger. The Thought Weaver continued to produce objects, each one more bizarre and unpredictable than the last."),
  ("How do the friends react when they encounter the wild animals?", "As the friends continued to explore the woods, they began to feel a sense of unease. They had been searching for the perfect campsite for hours, and finally, they had found something. But as they settled in for the night, they were startled by the sound of rustling leaves. They looked up to see a group of wild animals watching them from the trees."),
  ("Create a story about a child who befriends a tree.", "Lena found the ancient oak hidden behind a waterfall. Its gnarled branches seemed to hold secrets. She'd visit daily, leaving small gifts and listening to its whispers. The tree taught her about patience and the importance of taking time to absorb the world around her. When a severe storm destroyed part of the forest, Lena convinced the tree to use its roots to hold the soil in place. Together, they saved the remaining trees and created a sanctuary for wildlife."),
]
"""

EXAMPLES_STORIES_5 = """
[
  ("Write a story about a shy elephant.", "Kavi avoided the watering hole during daylight. One morning while hiding in bushes, she heard a baby gazelle crying nearby. Her instinct overpowered her shyness, leading her to become an unexpected rescuer in the savannah. The researchers found her behavior remarkable."),
  ("What is the name of the inventor who created the Thought Weaver?", "The inventor who created the Thought Weaver is a brilliant young woman named Aria. She spent years perfecting her machine, and it has become a game-changer in the field of invention. Aria's machine has the potential to revolutionize the way we think about creativity and innovation."),
  ("How do the friends react when they realize they are not alone on the road?", "As the friends continued to drive along the deserted highway, they began to feel a sense of unease. They had been so caught up in the excitement of their trip that they had forgotten about the possibility of encountering other drivers. But as they rounded a curve, they saw a car following closely behind them."),
  ("What do the friends do when they see the other car following them?", "The friends quickly pulled over to the side of the road and waited for the other car to pass. But as they waited, they noticed that the other car was not moving. It was following them at a steady pace, its headlights casting an eerie glow on the road. The friends exchanged nervous glances, unsure of what to do next."),
  ("How did the young dragon's parents influence their hatchling's perception of the world?", "Bober's parents instilled in him a sense of curiosity and adventure, encouraging him to explore and learn about the world around him. However, their decision to leave him behind also led Bober to become wary of trusting others, often questioning the motives of those who showed him kindness and compassion. As he grew older, Bober struggled to reconcile these opposing views, searching for a sense of belonging and identity that would ultimately shape his destiny."),
  ("How do the friends react when they find the treasure?", "As the friends continued to explore the abandoned mansion, they began to feel a sense of excitement. They had been searching for the treasure for hours, and finally, they had found something. But as they reached the chest, they realized that it was not what they had expected. Instead of gold and jewels, it was filled with old books and dusty artifacts."),
  ("What is the name of the group of friends who go on the road trip?", "The group of friends who go on the road trip are Alex, Sam, Emma, and Jack. They are all close friends who have known each other since college. They decided to take a break from their busy lives and embark on a road trip adventure."),
  ("Describe a scene in which Lorin demonstrated remarkable bravery in the face of danger.", "During a fierce battle with a rival clan, Lorin was forced to confront his own fears and limitations. As the enemy warriors closed in, Lorin's instincts screamed for retreat, but he remembered the words of his parents, who had encouraged him to stand up for what he believed in. Summoning a deep well of courage, Lorin charged forward, breathing fire and scattering the enemy. Though he was wounded, Lorin emerged victorious, his bravery earning him a place alongside the wizard's group as a true hero."),
  ("Tell me about the young dragon's encounter with a mysterious creature in the skies.", "Oden spotted a shimmering figure soaring through the clouds, its wings beating in a hypnotic rhythm. As the creature drew closer, Oden felt an inexplicable sense of calm wash over him. The creature, a winged being from a different realm, shared its wisdom with Oden, revealing the secrets of the wind and the mysteries of the cosmos. Though their encounter was brief, Oden felt changed by the experience, as if he had gained a newfound understanding of the world and his place within it."),
  ("Create a story about a group of friends who discover a hidden library and use its knowledge to explore the multiverse.", "While exploring the woods, a group of friends stumbled upon an ancient, hidden library. The shelves were filled with books that seemed to hold the secrets of the universe. As they delved into the tomes, they discovered that the library was a nexus for interdimensional travel. The friends used the knowledge gained to explore parallel worlds, encountering strange creatures and learning about the infinite possibilities of the multiverse."),
  ("Tell a story about a group of friends who go on a ghost hunting expedition.", "The group of friends, consisting of Mike, Sarah, Tom, and Rachel, decided to go on a ghost hunting expedition. They packed their bags, loaded up their ghost-hunting gear, and set off into the night. As they explored the abandoned mansion, they began to feel a sense of unease. The air was thick with the scent of decay, and the shadows seemed to move of their own accord."),  ("What is the name of the group of friends who go on the ghost hunting expedition?", "The group of friends who go on the ghost hunting expedition are Mike, Sarah, Tom, and Rachel. They are all experienced ghost hunters who have investigated numerous haunted locations."),
  ("Tell a tale about a woman who can turn anything into a work of art.", "Aurora possessed a magical gift – she could transform any object into a masterpiece. With a wave of her hand, a rusty old bike became a stunning sculpture, and a pile of discarded trash turned into a vibrant mosaic. People from all over the world came to witness her creativity, and she used her talents to beautify cities and bring joy to those who saw her work. One day, a group of children asked her to create a mural on a concrete wall, and Aurora made it a reality, inspiring a new generation of artists."),
  ("How did the mysterious creature's visit influence Taos's perspective on the world and his place within it?", "The winged being's encounter with Taos expanded his horizons and challenged his views on the world and its inhabitants. The creature's message of interconnectedness and the importance of embracing one's true nature helped Taos reconcile his complex identity and find a new sense of purpose. Their meeting also reminded Taos that there was more to the world than what he could see and experience, that there were mysteries and wonders waiting to be discovered."),
  ("How do the friends react when they encounter the ghost?", "As the friends continued to explore the abandoned mansion, they began to feel a sense of excitement. They had been searching for signs of paranormal activity for hours, and finally, they had found something. But as they turned a corner, they saw a figure standing in the shadows. It was a woman, tall and gaunt, with eyes that seemed to bore into their souls."),
]
"""

EXAMPLES_STORIES_6 = """
[
  ("What was the significance of Verion's decision to return to his parents and rejoining their clan?", "Verion's decision to return to his parents and rejoin their clan marked a significant turning point in his journey. It represented a desire to reconnect with his heritage and to understand the complexities of his family's past. By embracing his true nature and reuniting with his parents, Verion was finally able to reconcile his identities and find a sense of belonging within his community."),
  ("Describe a world where memories can be stored in a physical form.", "In the realm of Remembrance, memories were stored in small, glowing orbs. People could collect and trade these orbs, reliving the experiences of others. A young artist, struggling to find inspiration, received a memory orb from a deceased master painter. The artist's work flourished, and they became a renowned figure in the art world."),
  ("Create a story about a group of robots who start a band and become a sensation.", "In the distant future, a group of robots, each with their unique talents, decided to form a band. There was B-9, the lead singer with a voice like honey; Zeta, the guitarist who could play faster than any human; and Nova, the drummer who could keep rhythm with his mechanical heart. Together, they created a fusion of rock and electronic music that captivated the galaxy. Their first album, 'Rust in Peace,' became a worldwide phenomenon, and the robots embarked on a grand tour, spreading their message of unity and creativity."),
  ("Tell a tale about a woman who can turn anything into a work of art through her emotions.", "Aurora possessed a magical gift – she could transform any object into a masterpiece through her emotions. With a wave of her hand, a rusty old bike became a stunning sculpture, and a pile of discarded trash turned into a vibrant mosaic. People from all over the world came to witness her creativity, and she used her talents to beautify cities and bring joy to those who saw her work."),
  ("Describe a world where emotions are visible as colorful auras and people can communicate through them.", "In the realm of Aethereia, emotions took on a life of their own – they manifested as vibrant auras surrounding every living being. Happiness shone bright yellow, while sadness appeared as a soft blue mist. People learned to control and balance their emotions, creating a society where harmony and empathy reigned. Aethereia's inhabitants used their auras to communicate, and the colors became an integral part of their language and culture."),
  ("Describe a moment when Clark felt a strong connection to his parents.", "When Clark's parents finally reappeared, their reunion was bittersweet. Clark, now a seasoned dragon, had grown accustomed to his life with the wizard's group, but a part of him still longed for the connection he had shared with his parents. As they shared stories and laughter, Clark felt a deep sense of belonging, reminiscent of the bond he had shared with his parents all those years ago. However, he also realized that he had grown and changed in ways his parents could never have imagined."),
  ("How did Quant's parents, Thorold and Realia, contribute to the shaping of their hatchling's personality?", "Thorold and Realia's desire for freedom and exploration influenced Quant's sense of adventure and curiosity. However, their decision to leave him behind also led Quant to become cautious and wary of others. As he grew older, Quant struggled to reconcile these opposing views, often questioning the motives of those who showed him kindness and compassion. Their influence ultimately shaped Quant into a complex and multifaceted individual, driven by a mix of ambition and self-doubt."),
  ("Describe a scene in which Philip demonstrated remarkable compassion and empathy towards another being.", "When a wounded young bird fell from the sky, Philip rushed to its side, tenderly cradling it in his claws. As he gently examined its injuries, the bird gazed up at him with big, round eyes, and Philip felt a surge of kindness and understanding. Summoning the wisdom of his parents, Philip used his knowledge of herbal remedies to heal the bird's wounds, earning its gratitude and respect. This act of compassion not only helped the bird but also reminded Philip of the importance of kindness and empathy in the world."),
  ("What does Lily discover in the magical garden?", "In the magical garden, Lily discovered a variety of plants that seemed to have extraordinary properties. There were flowers that glowed in the dark, trees that seemed to heal wounds, and herbs that granted the consumer temporary powers of flight. She spent hours studying the plants, trying to understand the secrets of their magic."),
  ("Create a story about a sentient clock.", "The brass clock in the mayor's office began chiming irregularly. It responded to specific phrases in speeches, aligning timekeeping with political urgency. When a journalist asked about its behavior, it chimed Morse code details of upcoming budget cuts. The mayor tried silencing it by disconnecting the gears, but the clock locked its hands at 3:14, creating a local time loop. Citizens synchronized with the clock's new rhythm, ignoring standard time. Productivity increased in areas where rigid schedules had failed. The clock exposed budget allocations prioritizing industrial zones over schools and hospitals. When the mayor attempted to replace it with a digital model, the original clock's pendulum reappeared inside the new casing. Now the city operates on dual time systems—mechanical truth and digital convenience. The clock's chimes have become the unofficial language of transparency."),
  ("What happened when the drone attempted autonomous replanting?", "Its AI detected soil anomalies matching pre-industrial farming techniques. The fox noticed certain plants grew only near ruins or old animal trails. Together, they reconstructed an ancient ecosystem that outperformed modern agriculture. The first harvest included tomatoes with magnetic properties and corn that repelled pests through vibration. When farmers tried replicating the method, plants failed to thrive without the fox's presence. The drone's logs showed the fox's body heat subtly altered soil temperature. This explained why replanting required both thermal and organic input."),
  ("How did the bridge's tremors change during repairs?", "When construction equipment arrived, its vibrations disrupted the bridge's feedback loop with Lina. The bridge began creaking in distress tones, forcing engineers to recalibrate their tools to match her natural rhythm. Lina demonstrated footstep patterns that synchronized with the bridge's resonance, stabilizing it during repairs. Workers began listening to her suggestions, as the bridge responded positively to her input. By the end, repairs were completed with minimal disruption. The bridge now plays soft melodies at night, a behavior Lina encourages through counter-vibrations."),
  ("Tell a story about a group of friends who go on a camping trip.", "The group of friends, consisting of Alex, Sam, Emma, and Jack, decided to go on a camping trip. They packed their bags, loaded up their gear, and set off into the night. As they explored the woods, they began to feel a sense of excitement. They had been searching for the perfect campsite for hours, and finally, they had found something."),
  ("What is the name of the group of friends who go on the camping trip?", "The group of friends who go on the camping trip are Alex, Sam, Emma, and Jack. They are all experienced campers who have explored numerous wilderness areas."),
]
"""

ALL_EXAMPLES_STORIES = (
    EXAMPLES_STORIES_0, EXAMPLES_STORIES_1,
    EXAMPLES_STORIES_2, EXAMPLES_STORIES_3,
    EXAMPLES_STORIES_4, EXAMPLES_STORIES_5,
    EXAMPLES_STORIES_6,
)
