# coding: utf-8

"""
Public API

This is an API that exposes public api functionality

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SchemasCheckType(str, Enum):
    """
    SchemasCheckType
    """

    """
    allowed enum values
    """
    THROTTLEDCPU = "throttledCPU"
    REQUESTSLIMITSRATIO = "requestsLimitsRatio"
    DEPRECATEDAPIS = "deprecatedApis"
    KUBERNETESENDOFLIFE = "kubernetesEndOfLife"
    NOISYNEIGHBOR = "noisyNeighbor"
    KUBERNETESVERSIONDEPRECATED = "kubernetesVersionDeprecated"
    NODETERMINATIONAUTOSCALING = "nodeTerminationAutoScaling"
    NODETERMINATIONSPOTINSTANCE = "nodeTerminationSpotInstance"
    RESTARTINGCONTAINERS = "restartingContainers"
    HPAMAX = "HPAMax"
    UNDERPROVISIONEDWORKLOADS = "underProvisionedWorkloads"
    SINGLEPOINTOFFAILURE = "singlePointOfFailure"
    DEPLOYMENTMISSINGREPLICAS = "deploymentMissingReplicas"
    MISSINGPDB = "missingPDB"
    MISSINGTOPOLOGYSPREADCONSTRAINT = "missingTopologySpreadConstraint"
    HPAMINAVAILABILITY = "HPAMinAvailability"
    MISSINGHPA = "missingHPA"
    PRIORITYCLASSNOTSET = "priorityClassNotSet"
    CPUREQUESTSMISSING = "cpuRequestsMissing"
    CPULIMITSMISSING = "cpuLimitsMissing"
    MEMORYREQUESTSMISSING = "memoryRequestsMissing"
    MEMORYLIMITSMISSING = "memoryLimitsMissing"
    LIVENESSPROBEMISSING = "livenessProbeMissing"
    READINESSPROBEMISSING = "readinessProbeMissing"
    CERTIFICATEEXPIRATION = "certificateExpiration"
    IDLEGPU = "idleGpu"
    SYNTHETICDEGRADEDSERVICE = "syntheticDegradedService"
    SYNTHETICNODEPRESSURE = "syntheticNodePressure"
    SYNTHETICEOLDEPRECATIONOUTDATED = "syntheticEOLDeprecationOutdated"
    CASCADINGFAILURE = "cascadingFailure"
    UNHEALTHYSERVICE = "unhealthyService"
    UNHEALTHYWORKFLOW = "unhealthyWorkflow"
    FAILEDJOB = "failedJob"
    FAILEDCRONJOB = "failedCronJob"
    UNHEALTHYNODE = "unhealthyNode"
    UNHEALTHYPVC = "unhealthyPVC"
    EXTERNALDNSNOTSYNCED = "externalDNSNotSynced"
    OVERPROVISIONEDCLUSTER = "overProvisionedCluster"
    UNSCHEDULABLEPODS = "unschedulablePods"
    SCALEDOWNIMPACT = "scaleDownImpact"
    DISKPRESSURENODETERMINATIONIMPACT = "diskPressureNodeTerminationImpact"
    MEMORYPRESSURENODETERMINATIONIMPACT = "memoryPressureNodeTerminationImpact"
    NOTREADYNODETERMINATIONIMPACT = "notReadyNodeTerminationImpact"
    UNREACHABLENODETERMINATIONIMPACT = "unreachableNodeTerminationImpact"
    SHUTDOWNNODETERMINATIONIMPACT = "shutdownNodeTerminationImpact"
    FARGATESHUTDOWNNODETERMINATIONIMPACT = "fargateShutdownNodeTerminationImpact"
    SPOTINTERRUPTIONNODETERMINATIONIMPACT = "spotInterruptionNodeTerminationImpact"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SchemasCheckType from a JSON string"""
        return cls(json.loads(json_str))
