from enum import Enum


class IOGPTypeEnum(str, Enum):
    BENTHIC_SAMPLE = "BENTHIC_SAMPLE"
    BOX_CORE = "BOX_CORE"
    CAMERA_TRANSECT = "CAMERA_TRANSECT"
    COMPOSITE = "COMPOSITE"
    CPT = "CPT"
    GEOCHEMICAL_SAMPLE = "GEOCHEMICAL_SAMPLE"
    GEOTECHNICAL_SAMPLE = "GEOTECHNICAL_SAMPLE"
    GRAB_SAMPLE = "GRAB_SAMPLE"
    GRAVITY_CORE = "GRAVITY_CORE"
    HEAT_FLOW_MEASUREMENT = "HEAT_FLOW_MEASUREMENT"
    HYDRAULIC_FRACTURE = "HYDRAULIC_FRACTURE"
    JUMBO_CORE = "JUMBO_CORE"
    MULTI_CORE = "MULTI_CORE"
    PCPT = "PCPT"
    PILOT = "PILOT"
    PISTON_CORE = "PISTON_CORE"
    SAMPLING = "SAMPLING"
    SEABED_CPT = "SEABED_CPT"
    SEABED_PCPT = "SEABED_PCPT"
    SEISMIC_PCPT = "SEISMIC_PCPT"
    SOIL_OR_SEDIMENT_SAMPLE = "SOIL_OR_SEDIMENT_SAMPLE"
    SPI_SEDIMENT_PROFILE_INDEX = "SPI_SEDIMENT_PROFILE_INDEX"
    TSDIP = "TSDIP"
    VELO_VELOCIMETER = "VELO_VELOCIMETER"
    VIBRO_CORE = "VIBRO_CORE"
    VIDEO_SAMPLE = "VIDEO_SAMPLE"
    WATER_SAMPLE = "WATER_SAMPLE"

    def __str__(self) -> str:
        return str(self.value)
