"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.additive.v0.additive_domain_pb2
import ansys.api.additive.v0.additive_materials_pb2
import google.protobuf.empty_pb2
import grpc

class MaterialsServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    AddMaterial: grpc.UnaryUnaryMultiCallable[
        ansys.api.additive.v0.additive_materials_pb2.AddMaterialRequest,
        ansys.api.additive.v0.additive_materials_pb2.AddMaterialResponse] = ...

    RemoveMaterial: grpc.UnaryUnaryMultiCallable[
        ansys.api.additive.v0.additive_materials_pb2.RemoveMaterialRequest,
        google.protobuf.empty_pb2.Empty] = ...

    GetMaterialsList: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        ansys.api.additive.v0.additive_materials_pb2.GetMaterialsListResponse] = ...

    GetMaterial: grpc.UnaryUnaryMultiCallable[
        ansys.api.additive.v0.additive_materials_pb2.GetMaterialRequest,
        ansys.api.additive.v0.additive_domain_pb2.AdditiveMaterial] = ...


class MaterialsServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def AddMaterial(self,
        request: ansys.api.additive.v0.additive_materials_pb2.AddMaterialRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.additive.v0.additive_materials_pb2.AddMaterialResponse: ...

    @abc.abstractmethod
    def RemoveMaterial(self,
        request: ansys.api.additive.v0.additive_materials_pb2.RemoveMaterialRequest,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def GetMaterialsList(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> ansys.api.additive.v0.additive_materials_pb2.GetMaterialsListResponse: ...

    @abc.abstractmethod
    def GetMaterial(self,
        request: ansys.api.additive.v0.additive_materials_pb2.GetMaterialRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.additive.v0.additive_domain_pb2.AdditiveMaterial: ...


def add_MaterialsServiceServicer_to_server(servicer: MaterialsServiceServicer, server: grpc.Server) -> None: ...
