from typing import Union
from qtpy.QtCore import Property, QRectF, Qt, QPoint
from qtpy.QtGui import QIcon, QPainter, QColor
from qtpy.QtWidgets import QWidget
from qtpy.QtSvg import QSvgRenderer
from ...common.icon import FluentIconBase, drawIcon, toQIcon
from ...common.overload import singledispatchmethod
class IconWidget:
    def __init__(self, parent): ...
    def _(self, icon: FluentIconBase, parent: QWidget): ...
    def _(self, icon: QIcon, parent: QWidget): ...
    def _(self, icon: str, parent: QWidget): ...
    def getIcon(self): ...
    def setIcon(self, icon: Union[str, QIcon, FluentIconBase]): ...
    def paintEvent(self, e): ...