from __future__ import annotations
from typing import Optional, Union
from math import pi, cos, sin
from qtpy.QtCore import Qt, QPointF, QRectF
from qtpy.QtWidgets import QWidget, QVBoxLayout, QLabel, QHBoxLayout
from qtpy.QtGui import QGradient, QLinearGradient, QPainter, QColor, QBrush, QFont, QPen, QPainterPath
from qtmui.material.styles import useTheme
class ChartRadialBar:
    def __init__(self, series: list, total: int, options: dict, width: Optional[Union[str, int]], height: Optional[Union[str, int]], *args, **kwargs): ...
    def _init_widget(self): ...
    def upd(self, data: list): ...
    def paintEvent(self, e): ...
    def _add_center_label(self): ...
    def _update_center_label_position(self, center_widget): ...
    def _set_stylesheet(self): ...