# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/avxcelerate/sensors/v1/data_access/sensor_data_output_notification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.avxcelerate.sensors.v1.data_access import sensor_data_description_pb2 as ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_data__access_dot_sensor__data__description__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRansys/api/avxcelerate/sensors/v1/data_access/sensor_data_output_notification.proto\x12,ansys.api.avxcelerate.sensors.v1.data_access\x1aJansys/api/avxcelerate/sensors/v1/data_access/sensor_data_description.proto\x1a\x1bgoogle/protobuf/empty.proto2\x82\x01\n\x12SensorDataNotifier\x12l\n\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x43.ansys.api.avxcelerate.sensors.v1.data_access.SensorDataDescription\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.avxcelerate.sensors.v1.data_access.sensor_data_output_notification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATANOTIFIER._serialized_start=238
  _SENSORDATANOTIFIER._serialized_end=368
# @@protoc_insertion_point(module_scope)
