def unsafe_decode(string): ...
def decode(string): ...
def validate_encoded(string) -> None: ...
def validate_decoded(obj) -> None: ...
def unsafe_encode(obj): ...
def encode(obj): ...
def validate_all_printable(string) -> None: ...
