RESISTANCE = {
    "bluebell jar": 2,
    "bluebell grown": 1,
    "brick": 1,
    "brick floor": 1,
    "burner drill": 2,
    "clay": 1,
    "coal": 1,
    "coal block": 1,
    "coal ore": 2,
    "composter": 1,
    "copper anvil": 2,
    "copper block": 2,
    "copper boiler": 2,
    "copper brick": 3,
    "copper brick floor": 3,
    "copper constructor": 2,
    "copper door": 3,
    "copper door open": 3,
    "copper gear": 2,
    "copper ingot": 2,
    "copper ore": 2,
    "copper pipe": 2,
    "copper pit grown": 2,
    "copper press": 2,
    "copper pump": 2,
    "copper shaft": 2,
    "copper sheet": 2,
    "copper tank": 2,
    "furnace": 3,
    "ice": 1,
    "life crystal": 1,
    "manual press": 1,
    "masonry bench": 1,
    "moist dirt": 1,
    "mushroom block": 1,
    "mushroom door": 1,
    "mushroom door open": 1,
    "mushroom floor": 1,
    "mushroom shaper": 2,
    "mushroom table": 1,
    "pebble": 1,
    "potato": 1,
    "potato grown": 1,
    "rabbit adult": 1,
    "raw copper": 2,
    "raw tin": 2,
    "rock": 1,
    "sawbench": 1,
    "sewbench": 1,
    "skeleton": 1,
    "slife crystal": 1,
    "slime block": 1,
    "slime crystal": 1,
    "slime door": 1,
    "slime door open": 1,
    "slime floor": 1,
    "slime prince": 1,
    "slime shaper": 1,
    "slime table": 1,
    "stone": 1,
    "stone brick": 1,
    "stone brick floor": 1,
    "stone floor": 1,
    "thread": 2,
    "tin ingot": 2,
    "tin ore": 3,
    "tree": 1,
    "wooden sieve": 1,
}
