from collections import deque
from enum import Enum
from math import cos, pi, ceil
from qtpy.QtCore import QDateTime, Qt, QTimer, QPoint
from qtpy.QtGui import QWheelEvent
from qtpy.QtWidgets import QApplication, QScrollArea, QAbstractScrollArea
class SmoothScroll:
    def __init__(self, widget, orient): ...
    def setSmoothMode(self, smoothMode): ...
    def wheelEvent(self, e): ...
    def __smoothMove(self): ...
    def __subDelta(self, delta, stepsLeft): ...
class SmoothMode: