from _typeshed import Incomplete

class WorkerRegistrar:
    direct_link_server_url: Incomplete
    registered: bool
    registration_thread: Incomplete
    def __init__(self, direct_link_server_url: str = 'http://localhost:6887') -> None: ...
    def register_worker(self, worker_name: str, worker_type: str, monitor_port: int): ...
    def unregister_worker(self, worker_name: str): ...
    def start_auto_register(self, worker_name: str, worker_type: str, monitor_port: int): ...

def get_global_registrar() -> WorkerRegistrar: ...
def register_worker(worker_name: str, worker_type: str, monitor_port: int): ...
def unregister_worker(worker_name: str): ...
