class ByCutoff:
    def __init__(self) -> None: ...

    def set_min_length(self, min_length: int) -> ByCutoff: ...

    def set_merge_within(self, merge_within: int) -> ByCutoff: ...

    def set_cutoff(self, cutoff: float) -> ByCutoff: ...
