# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetHttpHeaderProfileResult',
    'AwaitableGetHttpHeaderProfileResult',
    'get_http_header_profile',
    'get_http_header_profile_output',
]

@pulumi.output_type
class GetHttpHeaderProfileResult:
    """
    A collection of values returned by getHttpHeaderProfile.
    """
    def __init__(__self__, description=None, http_header_insertions=None, id=None, name=None, tfid=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if http_header_insertions and not isinstance(http_header_insertions, list):
            raise TypeError("Expected argument 'http_header_insertions' to be a list")
        pulumi.set(__self__, "http_header_insertions", http_header_insertions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if tfid and not isinstance(tfid, str):
            raise TypeError("Expected argument 'tfid' to be a str")
        pulumi.set(__self__, "tfid", tfid)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The Description param.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="httpHeaderInsertions")
    def http_header_insertions(self) -> Sequence['outputs.GetHttpHeaderProfileHttpHeaderInsertionResult']:
        """
        The HttpHeaderInsertions param.
        """
        return pulumi.get(self, "http_header_insertions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The Id param.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The Name param.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def tfid(self) -> _builtins.str:
        return pulumi.get(self, "tfid")


class AwaitableGetHttpHeaderProfileResult(GetHttpHeaderProfileResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetHttpHeaderProfileResult(
            description=self.description,
            http_header_insertions=self.http_header_insertions,
            id=self.id,
            name=self.name,
            tfid=self.tfid)


def get_http_header_profile(id: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetHttpHeaderProfileResult:
    """
    Retrieves a config item.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_scm as scm

    example = scm.get_http_header_profile(id="1234-56-789")
    ```


    :param _builtins.str id: The Id param.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('scm:index/getHttpHeaderProfile:getHttpHeaderProfile', __args__, opts=opts, typ=GetHttpHeaderProfileResult).value

    return AwaitableGetHttpHeaderProfileResult(
        description=pulumi.get(__ret__, 'description'),
        http_header_insertions=pulumi.get(__ret__, 'http_header_insertions'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        tfid=pulumi.get(__ret__, 'tfid'))
def get_http_header_profile_output(id: Optional[pulumi.Input[_builtins.str]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetHttpHeaderProfileResult]:
    """
    Retrieves a config item.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_scm as scm

    example = scm.get_http_header_profile(id="1234-56-789")
    ```


    :param _builtins.str id: The Id param.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('scm:index/getHttpHeaderProfile:getHttpHeaderProfile', __args__, opts=opts, typ=GetHttpHeaderProfileResult)
    return __ret__.apply(lambda __response__: GetHttpHeaderProfileResult(
        description=pulumi.get(__response__, 'description'),
        http_header_insertions=pulumi.get(__response__, 'http_header_insertions'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        tfid=pulumi.get(__response__, 'tfid')))
