from qtpy.QtWidgets import QFrame, QWidget, QHBoxLayout
from qtpy.QtCore import QObject
class TableRow:
    def __init__(self, children: object, data: object, hover: bool, selected: bool): ...
    def _init_ui(self): ...
    def add_children(self, children: list): ...