class FromTo:
    def is_circular(self): ...
    def is_circular_same_end(self): ...
    @property
    def from_end(self): ...
    @property
    def to_end(self): ...
    def other_end(self, segment_end, tolerant: bool = False): ...
    @property
    def from_name(self): ...
    @property
    def to_name(self): ...
