class LinearPaths:
    def linear_path(self, segment, exclude=None): ...
    def linear_paths(self, redundant_junctions: bool = False): ...
    def merge_linear_path(self, segpath, redundant_junctions: bool = False, jntag: str = 'jn', enable_tracking: bool = False, merged_name=None, cut_counts: bool = False): ...
    def merge_linear_paths(self, redundant_junctions: bool = False, jntag: str = 'jn', merged_name=None, enable_tracking: bool = False, cut_counts: bool = False): ...
