class Topology:
    def is_cut_link(self, link): ...
    def is_cut_segment(self, segment): ...
    def segment_connected_component(self, segment, visited=None): ...
    def connected_components(self): ...
    def split_connected_components(self): ...
    @property
    def n_dead_ends(self): ...
    @property
    def n_dovetails(self): ...
    @property
    def n_internals(self): ...
    @property
    def n_containments(self): ...
    def info(self, short) -> None: ...
