from qtpy.QtGui import QMovie, Qt
from qtpy.QtWidgets import QVBoxLayout, QWidget, QFrame, QHBoxLayout, QLabel, QSpacerItem, QSizePolicy
class ModalBusy:
    def __init__(self, parent): ...
    def show_busy_modal(self): ...
    def hide_busy_modal(self): ...