import sys
from qtpy import QtWidgets, QtCore, QtGui
from qtpy.QtCore import QFile, QFileInfo, Qt, QByteArray, QTextStream, QStringDecoder
from qtpy.QtGui import QStandardItem, QStandardItemModel
from qtpy.QtWidgets import QApplication, QHeaderView, QTableView, QAbstractItemView
class FreezeTableWidget:
    def __init__(self, model): ...
    def init(self): ...
    def updateSectionWidth(self, logicalIndex, oldSize, newSize): ...
    def updateSectionHeight(self, logicalIndex, oldSize, newSize): ...
    def resizeEvent(self, event): ...
    def moveCursor(self, cursorAction, modifiers): ...
    def scrollTo(self, index, hint): ...
    def updateFrozenTableGeometry(self): ...
def main(args): ...