import uuid
from typing import Callable, Optional, Union, Dict
from qtpy.QtWidgets import QVBoxLayout, QWidget, QScrollArea, QSizePolicy
from qtpy.QtCore import Qt
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.widget_base import PyWidgetBase
from ..system.color_manipulator import alpha
from ..utils.validate_params import _validate_param
class Scrollbar:
    def __init__(self, children: Optional[Union[State, list]], spacing: Union[State, int], sx: Optional[Union[State, Callable, str, Dict]]): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_sx(self, value): ...
    def _set_spacing(self, value): ...
    def _get_sx(self): ...
    def slot_set_stylesheet(self, value): ...
    def _connect_signals(self): ...
    def _init_ui(self): ...
    def _on_destroyed(self): ...
    def _set_stylesheet(self, component_styled): ...
    def paintEvent(self, arg__1): ...
    def resizeEvent(self, event): ...