from typing import Union
from qtpy.QtCore import Qt, Signal, QRectF, QDate, QPoint, Property
from qtpy.QtGui import QPainter
from qtpy.QtWidgets import QWidget, QPushButton, QApplication
from ...common.style_sheet import FluentStyleSheet
from ...common.icon import FluentIcon
from .calendar_view import CalendarView
class CalendarPicker:
    def __init__(self, parent): ...
    def getDate(self): ...
    def setDate(self, date: QDate): ...
    def reset(self): ...
    def getDateFormat(self): ...
    def setDateFormat(self, format: Union[Qt.DateFormat, str]): ...
    def _showCalendarView(self): ...
    def _onDateChanged(self, date: QDate): ...
    def paintEvent(self, e): ...