import sys
from qtpy.QtWidgets import QMainWindow, QVBoxLayout, QApplication, QWidget
from qtpy.QtCore import Qt, QVariantAnimation, QEasingCurve, QSequentialAnimationGroup
from qtpy.QtGui import QPen, QPainter, QColor
from ...widget_base import PyWidgetBase
from qtmui.material.styles import useTheme
def get_color_from_label(color): ...
class LinearProgressIndeterminate:
    def __init__(self, key: str, color: str): ...
    def initUI(self): ...
    def startAnime(self): ...
    def updateProgress(self, value): ...
    def paintEvent(self, event): ...