# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.workflow_execution_response import WorkflowExecutionResponse

class TestWorkflowExecutionResponse(unittest.TestCase):
    """WorkflowExecutionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowExecutionResponse:
        """Test WorkflowExecutionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowExecutionResponse`
        """
        model = WorkflowExecutionResponse()
        if include_optional:
            return WorkflowExecutionResponse(
                id = '',
                tool_id = '',
                project_id = '',
                user_id = '',
                status = '',
                mode = 'test',
                started_at = '',
                ended_at = '',
                execution_time_ms = 56,
                tool_config = None,
                inputs = odin_sdk.models.inputs.Inputs(),
                execution_data = None,
                error_message = '',
                correlation_id = '',
                push_ref = '',
                tool_version = ''
            )
        else:
            return WorkflowExecutionResponse(
                id = '',
                tool_id = '',
                project_id = '',
                status = '',
                mode = 'test',
                started_at = '',
        )
        """

    def testWorkflowExecutionResponse(self):
        """Test WorkflowExecutionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
