# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.deploy_bot_tool_response import DeployBotToolResponse

class TestDeployBotToolResponse(unittest.TestCase):
    """DeployBotToolResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeployBotToolResponse:
        """Test DeployBotToolResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeployBotToolResponse`
        """
        model = DeployBotToolResponse()
        if include_optional:
            return DeployBotToolResponse(
                success = True,
                message = '',
                response = None
            )
        else:
            return DeployBotToolResponse(
                success = True,
                message = '',
        )
        """

    def testDeployBotToolResponse(self):
        """Test DeployBotToolResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
