# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.stock_data_request import StockDataRequest

class TestStockDataRequest(unittest.TestCase):
    """StockDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StockDataRequest:
        """Test StockDataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StockDataRequest`
        """
        model = StockDataRequest()
        if include_optional:
            return StockDataRequest(
                symbol = '',
                metrics = [
                    ''
                    ]
            )
        else:
            return StockDataRequest(
                symbol = '',
                metrics = [
                    ''
                    ],
        )
        """

    def testStockDataRequest(self):
        """Test StockDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
