# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.avxcelerate.sensors.v1.feedback_control import feedback_control_description_pb2 as ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_feedback__control_dot_feedback__control__description__pb2
from ansys.api.avxcelerate.sensors.v1 import status_pb2 as ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_status__pb2


class FeedbackControlStub(object):
    """Feedback Control Service

    This service provides the procedures to update specific parameters of 
    sensors during the simulation. It could be used to implement an 
    auto adaptive algorithm.

    Note: The changes are not directly applied to the sensor. First, the update 
    will be sent to the sensor at the next world update (requested using 
    the `Update` method of the Simulation service). Then, the sensor will be 
    reloaded so that the updated parameter(s) are used for the next output 
    calculation. However, a sensor cannot be reloaded during an ongoing output 
    calculation, it can be reloaded only after the computation is completed.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/ansys.api.avxcelerate.sensors.v1.feedback_control.FeedbackControl/Send',
                request_serializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_feedback__control_dot_feedback__control__description__pb2.FeedbackControlDescription.SerializeToString,
                response_deserializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_status__pb2.Status.FromString,
                )


class FeedbackControlServicer(object):
    """Feedback Control Service

    This service provides the procedures to update specific parameters of 
    sensors during the simulation. It could be used to implement an 
    auto adaptive algorithm.

    Note: The changes are not directly applied to the sensor. First, the update 
    will be sent to the sensor at the next world update (requested using 
    the `Update` method of the Simulation service). Then, the sensor will be 
    reloaded so that the updated parameter(s) are used for the next output 
    calculation. However, a sensor cannot be reloaded during an ongoing output 
    calculation, it can be reloaded only after the computation is completed.

    """

    def Send(self, request, context):
        """Sends a sensor (camera, lidar, radar) feedback control.

        Returns a processing Status.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_feedback__control_dot_feedback__control__description__pb2.FeedbackControlDescription.FromString,
                    response_serializer=ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_status__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.avxcelerate.sensors.v1.feedback_control.FeedbackControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeedbackControl(object):
    """Feedback Control Service

    This service provides the procedures to update specific parameters of 
    sensors during the simulation. It could be used to implement an 
    auto adaptive algorithm.

    Note: The changes are not directly applied to the sensor. First, the update 
    will be sent to the sensor at the next world update (requested using 
    the `Update` method of the Simulation service). Then, the sensor will be 
    reloaded so that the updated parameter(s) are used for the next output 
    calculation. However, a sensor cannot be reloaded during an ongoing output 
    calculation, it can be reloaded only after the computation is completed.

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.avxcelerate.sensors.v1.feedback_control.FeedbackControl/Send',
            ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_feedback__control_dot_feedback__control__description__pb2.FeedbackControlDescription.SerializeToString,
            ansys_dot_api_dot_avxcelerate_dot_sensors_dot_v1_dot_status__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
