import numpy as np
from iode import variables as variables

def ws_sample_set(from_period: str, to_period: str) -> tuple[str, str] | None: ...
def ws_sample_get() -> tuple[str, str] | None: ...
def ws_sample_nb_periods() -> int: ...
def ws_sample_to_string() -> str | None: ...
def ws_sample_to_list(from_period: str = '', to_period: str = '', as_floats: bool = False) -> list[str] | np.ndarray | None: ...
