# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Configurable.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'Configurable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43onfigurable.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x06\n\x04JSON\"\x1d\n\x1b\x43onfigurableSuccessResponse2n\n\x0c\x43onfigurable\x12+\n\nget_config\x12\x16.google.protobuf.Empty\x1a\x05.JSON\x12\x31\n\nset_config\x12\x05.JSON\x1a\x1c.ConfigurableSuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Configurable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSON']._serialized_start=51
  _globals['_JSON']._serialized_end=57
  _globals['_CONFIGURABLESUCCESSRESPONSE']._serialized_start=59
  _globals['_CONFIGURABLESUCCESSRESPONSE']._serialized_end=88
  _globals['_CONFIGURABLE']._serialized_start=90
  _globals['_CONFIGURABLE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
