class ToGFA1:
    @property
    def overlap(self): ...
    @property
    def oriented_from(self): ...
    @property
    def oriented_to(self): ...
    @property
    def from_segment(self): ...
    @from_segment.setter
    def from_segment(self, value) -> None: ...
    @property
    def from_orient(self): ...
    @from_orient.setter
    def from_orient(self, value) -> None: ...
    @property
    def to_segment(self): ...
    @to_segment.setter
    def to_segment(self, value) -> None: ...
    @property
    def to_orient(self): ...
    @to_orient.setter
    def to_orient(self, value) -> None: ...
    @property
    def pos(self): ...
