from _typeshed import Incomplete

class References:
    def append_item(self, item) -> None: ...
    def prepend_item(self, item) -> None: ...
    items: Incomplete
    def rm_first_item(self) -> None: ...
    def rm_last_item(self) -> None: ...
