from qtpy.QtWidgets import QWidget
from qtpy.QtGui import QPixmap, QPainter, QBrush
from qtpy.QtCore import Qt
def widget_to_pixmap(widget): ...
class PixmapWidget:
    def __init__(self, widget): ...
    def paintEvent(self, event): ...