from .graph_operations import GraphOperations as GraphOperations
from .lines import Lines as Lines
from .rgfa import RGFA as RGFA

class Gfa(Lines, GraphOperations, RGFA):
    def __init__(self, *args, vlevel: int = 1, version=None, dialect: str = 'standard') -> None: ...
    @property
    def version(self): ...
    @version.setter
    def version(self, value) -> None: ...
    @property
    def dialect(self): ...
    @dialect.setter
    def dialect(self, value) -> None: ...
    @property
    def vlevel(self): ...
    @vlevel.setter
    def vlevel(self, value) -> None: ...
    def validate(self) -> None: ...
    def to_gfa1_s(self): ...
    def to_gfa1(self): ...
    def to_gfa2_s(self): ...
    def to_gfa2(self): ...
    def read_file(self, filename): ...
    @classmethod
    def from_file(cls, filename, vlevel: int = 1, version=None, dialect: str = 'standard'): ...
    def to_file(self, filename) -> None: ...
    def __eq__(self, other): ...
    def enable_progress_logging(self, part: float = 0.1, channel=...) -> None: ...
