class LastPos:
    def __new__(cls, value, valid: bool = False): ...
    def validate(self) -> None: ...
    def __int__(self) -> int: ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __sub__(self, other): ...

def posvalue(obj): ...
def islastpos(obj): ...
def isfirstpos(obj): ...
