class Logger:
    class ProgressData:
        def __init__(self, counter, units, partsize, lastpart, total, starttime, strlen) -> None: ...
    def __init__(self, verbose_level: int = 1, channel=..., prefix: str = '#') -> None: ...
    def log(self, msg, min_verbose_level: int = 1) -> None: ...
    def enable_progress(self, part: float = 0.1) -> None: ...
    def disable_progress(self) -> None: ...
    def progress_init(self, symbol, units, total, initmsg=None) -> None: ...
    def progress_log(self, symbol, progress: int = 1, **keyargs) -> None: ...
    def progress_end(self, symbol, **keyargs) -> None: ...
