class Placeholder:
    def __bool__(self) -> bool: ...
    def complement(self): ...
    def is_empty(self): ...
    def validate(self, *args, **keyargs) -> None: ...
    def rc(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, key): ...
    def __add__(self, other): ...
    def __eq__(self, other): ...

def is_placeholder(object): ...
