
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-05T11:41:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f684a92a377c69a319dbb674ac1961befb0b3b2",
 "version": "2025.11.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
