from typing import Callable
from qtpy.QtWidgets import QFrame, QPushButton
from qtpy.QtCore import QEvent, QModelIndex, Qt, QPersistentModelIndex, QTimer, Signal, QSize
from qtpy.QtWidgets import QPushButton, QHBoxLayout
from ...py_tool_button.py_tool_button import PyToolButton
from qtmui.material.styles import useTheme
class AcceptDropFrame:
    def __init__(self, depth, startIcon: PyToolButton, selected, onDrop: Callable, value): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def eventFilter(self, obj, event): ...
    def timeout(self): ...
    def left_click_event(self): ...
    def right_click_event(self): ...
    def double_click_event(self): ...
    def dragEnterEvent(self, e): ...
    def dragMoveEvent(self, event): ...
    def dropEvent(self, event): ...