from typing import Callable, Union, Optional, List
from qtpy.QtWidgets import QWidget, QHBoxLayout, QLabel, QFrame, QPushButton, QSizePolicy, QVBoxLayout, QSpacerItem
from qtpy.QtCore import Qt, QSize
from qtpy.QtGui import QIcon
from ..button.icon_button import IconButton
from ..py_iconify import PyIconify, Iconify
from ...qtmui_assets import QTMUI_ASSETS
class MultiFilePreview:
    def __init__(self, thumbnail: bool, files: Optional[List[List[Union[str, int]]]], onRemove: Optional[Callable], sx: Optional[dict], *args, **kwargs): ...
    def renderPreviews(self): ...
    def addFilePreview(self, file): ...
    def removeFilePreview(self, file): ...
    def format_size(bytes): ...