import uuid
from qtpy.QtWidgets import QWidget, QFrame, QHBoxLayout, QSizePolicy
from qtpy.QtCore import Qt
from typing import Union, List, Callable
from ..box import Box
from ..spacer import HSpacer
from .timeline_content import TimelineContent, AlignBox
from .timeline_opposite_content import TimelineOppositeContent
class TimelineItem:
    def __init__(self, children, classes: dict, position: str, key: Union[str, int], sx: Union[List[Union[Callable, dict, bool]], Callable, dict]): ...
    def _initUI(self): ...
    def _add_children(self): ...
    def _setup_layout(self): ...
    def setAlignment(self, alignment): ...