class FastDaisyAdminException(Exception): ...


class InvalidModelError(FastDaisyAdminException): ...


class NoConverterFound(FastDaisyAdminException): ...


class InvalidField(FastDaisyAdminException): ...


class InvalidAuthModelError(FastDaisyAdminException): ...
