"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dg_mol_track_client.types import BaseModel
from dg_mol_track_client.utils import FieldMetadata, MultipartFormMetadata
import io
import pydantic
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatchFileTypedDict(
    TypedDict
):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatchFile(
    BaseModel
):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatchTypedDict(
    TypedDict
):
    file: BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatchFileTypedDict


class BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatch(BaseModel):
    file: Annotated[
        BodyUpdateStandardizationConfigV1AdminUpdateStandardizationConfigPatchFile,
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ]
