from google.api import annotations_pb2 as _annotations_pb2
from kessel.inventory.v1beta2 import check_request_pb2 as _check_request_pb2
from kessel.inventory.v1beta2 import check_response_pb2 as _check_response_pb2
from kessel.inventory.v1beta2 import check_for_update_request_pb2 as _check_for_update_request_pb2
from kessel.inventory.v1beta2 import check_for_update_response_pb2 as _check_for_update_response_pb2
from kessel.inventory.v1beta2 import report_resource_request_pb2 as _report_resource_request_pb2
from kessel.inventory.v1beta2 import report_resource_response_pb2 as _report_resource_response_pb2
from kessel.inventory.v1beta2 import delete_resource_request_pb2 as _delete_resource_request_pb2
from kessel.inventory.v1beta2 import delete_resource_response_pb2 as _delete_resource_response_pb2
from kessel.inventory.v1beta2 import streamed_list_objects_request_pb2 as _streamed_list_objects_request_pb2
from kessel.inventory.v1beta2 import streamed_list_objects_response_pb2 as _streamed_list_objects_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
