# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/inventory/v1beta2/resource_representations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kessel/inventory/v1beta2/resource_representations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from kessel.inventory.v1beta2 import representation_metadata_pb2 as kessel_dot_inventory_dot_v1beta2_dot_representation__metadata__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7kessel/inventory/v1beta2/resource_representations.proto\x12\x18kessel.inventory.v1beta2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x36kessel/inventory/v1beta2/representation_metadata.proto\x1a\x1b\x62uf/validate/validate.proto\"\xf7\x01\n\x17ResourceRepresentations\x12T\n\x08metadata\x18\x01 \x01(\x0b\x32\x30.kessel.inventory.v1beta2.RepresentationMetadataB\x06\xbaH\x03\xc8\x01\x01R\x08metadata\x12\x34\n\x06\x63ommon\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x00R\x06\x63ommon\x88\x01\x01\x12\x38\n\x08reporter\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x01R\x08reporter\x88\x01\x01\x42\t\n\x07_commonB\x0b\n\t_reporterBr\n(org.project_kessel.api.inventory.v1beta2P\x01ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta2.resource_representations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.inventory.v1beta2P\001ZDgithub.com/project-kessel/inventory-api/api/kessel/inventory/v1beta2'
  _globals['_RESOURCEREPRESENTATIONS'].fields_by_name['metadata']._loaded_options = None
  _globals['_RESOURCEREPRESENTATIONS'].fields_by_name['metadata']._serialized_options = b'\272H\003\310\001\001'
  _globals['_RESOURCEREPRESENTATIONS']._serialized_start=201
  _globals['_RESOURCEREPRESENTATIONS']._serialized_end=448
# @@protoc_insertion_point(module_scope)
