# TransformFormatLib1.pyi - 自动生成的类型存根文件
# 生成时间: 2025-11-04 08:55:03
# 函数数量: 1 | 类数量: 1 | 方法数量: 9

from typing import Any, Optional

# 导入语句
from typing import Dict, Any, Tuple, Union
import numpy as np

# 模块级函数
def format_extrinsic_yaml() -> Any: ...

# 类定义
class YAMLFormatter:
    def format_value(value: Any, precision: int = 6, width: int = 15) -> Any: ...
    def format_list(values: Union[list, np.ndarray], precision: int = 6, width: int = 15) -> Any: ...
    def format_matrix(matrix: Union[list, np.ndarray], precision: int = 6, width: int = 15, indent: int = 2) -> Any: ...
    def format_rotation_matrix() -> Any: ...
    def format_quaternion() -> Any: ...
    def format_standard_euler() -> Any: ...
    def format_geosun_euler() -> Any: ...
    def format_homogeneous_matrix() -> Any: ...
    def format_axis_angle() -> Any: ...

