from collections.abc import Awaitable, Callable as Callable
from typing import Any, ParamSpec, TypeVar

P = ParamSpec('P')
T = TypeVar('T')
_PIPELINE_REGISTRY: dict[str, Callable[..., Awaitable[Any]]]
_PIPELINE_DEFAULTS: dict[str, dict[str, Any]]

def piragbox(*, params: dict[str, Any], name: str | None = None) -> Callable[[Callable[P, Awaitable[T]]], Callable[P, Awaitable[T]]]: ...
def get_pipeline(name: str) -> Callable[..., Awaitable[Any]]: ...
def get_pipeline_param_defaults(name: str) -> dict[str, Any]: ...
def list_pipelines() -> list[str]: ...
