

def get_mip_dim(mip: int, add_compressed_format_padding: bool, dim: int) -> int: ...

def get_mip_dims(mip: int, add_compressed_format_padding: bool, width: int, height: int, depth: int = 1) -> tuple[int, int, int]: ...

def get_maximum_mip_count(width: int, height: int, depth: int = 1) -> int: ...
