from pathlib import Path

from biobit.core.ngs import MatesOrientation as MatesOrientation


class Layout:
    class Single(Layout):
        file: Path

        def __init__(self, file: Path | str) -> None: ...

        def __repr__(self) -> str: ...

        def __str__(self) -> str: ...

        def __hash__(self) -> int: ...

        def __eq__(self, other: object) -> bool: ...

        def __ne__(self, other: object) -> bool: ...

        def __lt__(self, other: object) -> bool: ...

        def __le__(self, other: object) -> bool: ...

        def __gt__(self, other: object) -> bool: ...

        def __ge__(self, other: object) -> bool: ...

    class Paired(Layout):
        orientation: MatesOrientation | None
        files: tuple[Path, Path]

        def __init__(self, orientation: MatesOrientation | None, files: tuple[Path | str, Path | str]) -> None: ...

        def __repr__(self) -> str: ...

        def __str__(self) -> str: ...

        def __hash__(self) -> int: ...

        def __eq__(self, other: object) -> bool: ...

        def __ne__(self, other: object) -> bool: ...

        def __lt__(self, other: object) -> bool: ...

        def __le__(self, other: object) -> bool: ...

        def __gt__(self, other: object) -> bool: ...

        def __ge__(self, other: object) -> bool: ...
