class Equivalence:
    def __hash__(self): ...
    def is_eql(self, other): ...
    def are_tags_eql(self, other): ...
    def is_same(self, other): ...
    def is_complement(self, other): ...
    def is_compatible(self, other_oriented_from, other_oriented_to, other_overlap=None, allow_complement: bool = True): ...
    def is_compatible_direct(self, other_oriented_from, other_oriented_to, other_overlap=None): ...
    def is_compatible_complement(self, other_oriented_from, other_oriented_to, other_overlap=None): ...
