class ToGFA2:
    @property
    def eid(self): ...
    name = eid
    @property
    def sid1(self): ...
    @property
    def sid2(self): ...
    @property
    def beg1(self): ...
    @property
    def end1(self): ...
    @property
    def beg2(self): ...
    @property
    def end2(self): ...
    @property
    def alignment(self): ...
