
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-05T13:31:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b25cefe582afe85946c354c82f01c3b0d9ce4964",
 "version": "3.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
