# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class KBFileStatus(str, Enum):
    """
    KBFileStatus
    """

    """
    allowed enum values
    """
    SYNCED = 'synced'
    SYNCING = 'syncing'
    QUEUED = 'queued'
    FAILED = 'failed'
    DELETING = 'deleting'
    TIMEOUT = 'timeout'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KBFileStatus from a JSON string"""
        return cls(json.loads(json_str))


