# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.update_custom_tool_request import UpdateCustomToolRequest

class TestUpdateCustomToolRequest(unittest.TestCase):
    """UpdateCustomToolRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCustomToolRequest:
        """Test UpdateCustomToolRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomToolRequest`
        """
        model = UpdateCustomToolRequest()
        if include_optional:
            return UpdateCustomToolRequest(
                name = '',
                description = '',
                inputs = {
                    'key' : odin_sdk.models.tool_input.ToolInput(
                        id = '', 
                        type = '', 
                        value = null, 
                        manual_input = True, 
                        required = True, 
                        description = '', )
                    },
                steps = {
                    'key' : odin_sdk.models.tool_step.ToolStep(
                        id = '', 
                        tool_id = '', 
                        type = '', 
                        label = '', 
                        description = '', 
                        settings = odin_sdk.models.settings.Settings(), )
                    },
                flow_layout = None,
                is_public = True
            )
        else:
            return UpdateCustomToolRequest(
        )
        """

    def testUpdateCustomToolRequest(self):
        """Test UpdateCustomToolRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
