# This file was auto-generated by Fern from our API Definition.

import typing

UpdateFeatureRequestBodyLifecyclePhase = typing.Union[
    typing.Literal["add_on", "alpha", "beta", "deprecated", "ga", "in_plan", "inactive", "internal_testing", "legacy"],
    typing.Any,
]
