class CopyNumber:
    def set_default_count_tag(self, tag) -> None: ...
    def set_count_unit_length(self, unit_length) -> None: ...
    def delete_low_coverage_segments(self, mincov, count_tag=None, unit_length=None) -> None: ...
    def compute_copy_numbers(self, single_copy_coverage, mincov=None, count_tag=None, cn_tag: str = 'cn', unit_length=None) -> None: ...
    def apply_copy_numbers(self, count_tag: str = 'cn', distribute: str = 'auto', origin_tag: str = 'or', conserve_components: bool = True): ...
