class SuperfluousLinks:
    def enforce_segment_mandatory_links(self, segment, conserve_components: bool = True) -> None: ...
    def enforce_all_mandatory_links(self, conserve_components: bool = True) -> None: ...
    def remove_self_link(self, segment) -> None: ...
    def remove_self_links(self) -> None: ...
