"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2
import ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2
import ansys.api.avxcelerate.sensors.v1.sensor_data.radar_output_data_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SensorData(google.protobuf.message.Message):
    """Structure of the data produced by a single sensor for one simulation step.

    Time stamp and type of the produced sensor data.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIME_STAMP_FIELD_NUMBER: builtins.int
    CAMERA_DATA_FIELD_NUMBER: builtins.int
    LIDAR_DATA_FIELD_NUMBER: builtins.int
    RADAR_DATA_FIELD_NUMBER: builtins.int
    @property
    def time_stamp(self) -> google.protobuf.duration_pb2.Duration:
        """The simulation time stamp at which the data was produced."""
        pass
    @property
    def camera_data(self) -> global___CameraData:
        """The type of data produced by the camera sensor."""
        pass
    @property
    def lidar_data(self) -> global___LidarData:
        """The type of data produced by the lidar sensor."""
        pass
    @property
    def radar_data(self) -> global___RadarData:
        """The type of data produced by the radar sensor."""
        pass
    def __init__(self,
        *,
        time_stamp : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        camera_data : typing.Optional[global___CameraData] = ...,
        lidar_data : typing.Optional[global___LidarData] = ...,
        radar_data : typing.Optional[global___RadarData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["camera_data",b"camera_data","data",b"data","lidar_data",b"lidar_data","radar_data",b"radar_data","time_stamp",b"time_stamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["camera_data",b"camera_data","data",b"data","lidar_data",b"lidar_data","radar_data",b"radar_data","time_stamp",b"time_stamp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data",b"data"]) -> typing.Optional[typing_extensions.Literal["camera_data","lidar_data","radar_data"]]: ...
global___SensorData = SensorData

class CameraData(google.protobuf.message.Message):
    """Block containing a set of camera data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CameraDataEntry]:
        """List of camera data entries."""
        pass
    def __init__(self,
        *,
        entries : typing.Optional[typing.Iterable[global___CameraDataEntry]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries",b"entries"]) -> None: ...
global___CameraData = CameraData

class LidarData(google.protobuf.message.Message):
    """Block containing a set of formatted lidar data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LidarDataEntry]:
        """List of lidar data entries."""
        pass
    def __init__(self,
        *,
        entries : typing.Optional[typing.Iterable[global___LidarDataEntry]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries",b"entries"]) -> None: ...
global___LidarData = LidarData

class RadarData(google.protobuf.message.Message):
    """Block containing a set of formatted radar data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RadarDataEntry]:
        """List of radar data entries."""
        pass
    def __init__(self,
        *,
        entries : typing.Optional[typing.Iterable[global___RadarDataEntry]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries",b"entries"]) -> None: ...
global___RadarData = RadarData

class CameraDataEntry(google.protobuf.message.Message):
    """A single formatted camera data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IMAGE_DATA_FIELD_NUMBER: builtins.int
    GROUND_TRUTH_DATA_FIELD_NUMBER: builtins.int
    BOUNDING_BOX_2D_FIELD_NUMBER: builtins.int
    CAMERA_LENS_OUTPUT_FIELD_NUMBER: builtins.int
    CAMERA_CUSTOM_DATA_OUTPUT_FIELD_NUMBER: builtins.int
    BOUNDING_BOX_3D_FIELD_NUMBER: builtins.int
    @property
    def image_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraImageData:
        """Image produced by the camera sensor."""
        pass
    @property
    def ground_truth_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraGroundTruthData:
        """Ground truth data produced for the camera sensor."""
        pass
    @property
    def bounding_box_2d(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.BoundingBox2D:
        """2D Bounding box produced."""
        pass
    @property
    def camera_lens_output(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraLensOutput:
        """Spectral irradiance map, which is the lens output of the camera sensor."""
        pass
    @property
    def camera_custom_data_output(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraImageData:
        """Custom data, which is custom data output of the camera sensor."""
        pass
    @property
    def bounding_box_3d(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.BoundingBox3D:
        """3D Bounding box produced."""
        pass
    def __init__(self,
        *,
        image_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraImageData] = ...,
        ground_truth_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraGroundTruthData] = ...,
        bounding_box_2d : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.BoundingBox2D] = ...,
        camera_lens_output : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraLensOutput] = ...,
        camera_custom_data_output : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.CameraImageData] = ...,
        bounding_box_3d : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.camera_output_data_pb2.BoundingBox3D] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bounding_box_2d",b"bounding_box_2d","bounding_box_3d",b"bounding_box_3d","camera_custom_data_output",b"camera_custom_data_output","camera_lens_output",b"camera_lens_output","ground_truth_data",b"ground_truth_data","image_data",b"image_data","output",b"output"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bounding_box_2d",b"bounding_box_2d","bounding_box_3d",b"bounding_box_3d","camera_custom_data_output",b"camera_custom_data_output","camera_lens_output",b"camera_lens_output","ground_truth_data",b"ground_truth_data","image_data",b"image_data","output",b"output"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["output",b"output"]) -> typing.Optional[typing_extensions.Literal["image_data","ground_truth_data","bounding_box_2d","camera_lens_output","camera_custom_data_output","bounding_box_3d"]]: ...
global___CameraDataEntry = CameraDataEntry

class LidarDataEntry(google.protobuf.message.Message):
    """A single formatted lidar data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POINT_CLOUD_DATA_FIELD_NUMBER: builtins.int
    WAVEFORM_DATA_FIELD_NUMBER: builtins.int
    CONTRIBUTION_DATA_FIELD_NUMBER: builtins.int
    LENS_OUTPUT_DATA_FIELD_NUMBER: builtins.int
    @property
    def point_cloud_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.PointCloudData:
        """Point cloud data produced by the lidar sensor."""
        pass
    @property
    def waveform_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.WaveformData:
        """Digital waveform data produced by the lidar sensor."""
        pass
    @property
    def contribution_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.ContributionData:
        """Contribution List produced for the lidar sensor."""
        pass
    @property
    def lens_output_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.LensOutputData:
        """Lens Output data produced by the lidar sensor."""
        pass
    def __init__(self,
        *,
        point_cloud_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.PointCloudData] = ...,
        waveform_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.WaveformData] = ...,
        contribution_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.ContributionData] = ...,
        lens_output_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.lidar_output_data_pb2.LensOutputData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["contribution_data",b"contribution_data","format",b"format","lens_output_data",b"lens_output_data","point_cloud_data",b"point_cloud_data","waveform_data",b"waveform_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["contribution_data",b"contribution_data","format",b"format","lens_output_data",b"lens_output_data","point_cloud_data",b"point_cloud_data","waveform_data",b"waveform_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["format",b"format"]) -> typing.Optional[typing_extensions.Literal["point_cloud_data","waveform_data","contribution_data","lens_output_data"]]: ...
global___LidarDataEntry = LidarDataEntry

class RadarDataEntry(google.protobuf.message.Message):
    """A single formatted radar data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RADAR_DATA_FIELD_NUMBER: builtins.int
    @property
    def radar_data(self) -> ansys.api.avxcelerate.sensors.v1.sensor_data.radar_output_data_pb2.RadarOutputData:
        """RadarOutputData"""
        pass
    def __init__(self,
        *,
        radar_data : typing.Optional[ansys.api.avxcelerate.sensors.v1.sensor_data.radar_output_data_pb2.RadarOutputData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["format",b"format","radar_data",b"radar_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["format",b"format","radar_data",b"radar_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["format",b"format"]) -> typing.Optional[typing_extensions.Literal["radar_data"]]: ...
global___RadarDataEntry = RadarDataEntry
