class References:
    @property
    def dovetails(self): ...
    def dovetails_of_end(self, extremity): ...
    @property
    def gaps(self): ...
    def gaps_of_end(self, extremity): ...
    @property
    def containments(self): ...
    @property
    def neighbours(self): ...
    @property
    def neighbours_L(self): ...
    @property
    def neighbours_R(self): ...
    def neighbours_of_end(self, extremity): ...
    @property
    def containers(self): ...
    @property
    def contained(self): ...
    @property
    def edges(self): ...
    def relations_to(self, segment, collection: str = 'edges'): ...
    def oriented_relations(self, orientation, oriented_segment, collection: str = 'edges'): ...
    def end_relations(self, extremity, segment_end, collection: str = 'edges'): ...
