from typing import Callable, Optional, Sequence
from qtpy.QtCore import Qt, Property, Slot, Signal
from qtpy.QtWidgets import QWidget, QVBoxLayout, QFrame, QLabel
from qtmui.material.styles import useTheme
from qtmui.hooks import useState
from qtmui.hooks import State
from ...material.controller import Controller
from ..rating.rating import Rating
from ...material.autocomplete.complete import Autocomplete
class RHFRating:
    def __init__(self, name, max: int, value: int, onChange: Optional[Callable], helperText: str, **kwargs): ...
    def _set_value(self, value): ...
    def stateSignal(self): ...
    def stateSignal(self, value): ...
    def state(self, state): ...