from weakref import ref
import random
from qtpy.QtGui import QPen, QPainter, QColor, QPixmap, QIcon
from qtpy.QtCore import Qt, QVariantAnimation, QRectF, QEasingCurve, QSize
from qtpy.QtWidgets import QApplication, QPushButton
from qtmui.material.styles import useTheme
class Arc:
    def __init__(self): ...
class LoadingIcon:
    def __init__(self, button: QPushButton, diameter, parent): ...
    def startAnime(self): ...
    def updatePixmap(self, value): ...
    def stopAnimation(self): ...