from typing import Literal, ClassVar


class MatesOrientation:
    Inward: ClassVar[MatesOrientation]

    def __init__(self, value: IntoMatesOrientation) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __hash__(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __lt__(self, other: object) -> bool: ...

    def __le__(self, other: object) -> bool: ...

    def __gt__(self, other: object) -> bool: ...

    def __ge__(self, other: object) -> bool: ...


IntoMatesOrientation = MatesOrientation | Literal["I"]
