# -*- coding: utf-8 -*-
translate_dict = {'accumulated_hectares': {'en': 'Accumulated hectares', 'es': 'Hectáreas acumuladas', 'pt': 'Hectares acumulados'},
 'adjust_dem_to_farm_extent': {'en': 'Adjust the DEM to the farm extent',
                               'es': 'Ajustar el DEM a la extensión del establecimiento',
                               'pt': 'Ajustar o DEM à extensão da fazenda'},
 'adjusted_average_yield': {'en': 'Adjusted Average Yield',
                            'es': 'Rendimiento Medio Ajustado',
                            'pt': 'Rendimento Médio Ajustado'},
 'adjusted_average_yield_by': {'en': 'Adjusted Average Yield by',
                               'es': 'Rendimiento Medio Ajustado por',
                               'pt': 'Rendimento Médio Ajustado por'},
 'affected_area': {'en': 'Area', 'es': 'Área', 'pt': 'Área'},
 'affected_area_description': {'en': 'Surface area affected by water presence, expressed in hectares.',
                               'es': 'Superficie afectada por la presencia de agua en superficie, expresada en '
                                     'hectáreas.',
                               'pt': 'Área afetada pela presença de água na superfície, expressa em hectares.'},
 'affected_prop': {'en': 'Proportion', 'es': 'Proporción', 'pt': 'Proporção'},
 'affected_prop_decription': {'en': 'The indicated value represents, in percentage terms, the proportion of the lot '
                                    'area where surface water has been detected.',
                              'es': 'El valor indicado representa, en términos porcentuales, la proporción de la '
                                    'superficie del lote en la que se ha detectado la presencia de agua en superficie.',
                              'pt': 'O valor indicado representa, em termos percentuais, a proporção da área do lote '
                                    'onde foi detectada a presença de água na superfície.'},
 'altimetry_map_description': {'en': 'This tool allows the creation of altimetry maps based on the SRTM (Shuttle Radar '
                                     'Topography Mission) Digital Elevation Model.',
                               'es': 'Esta herramienta permite crear mapas de altimetría, basados en el Modelo Digital '
                                     'de Elevación SRTM (Shuttle Radar Topography Mission).',
                               'pt': 'Esta ferramenta permite criar mapas de altimetria com base no Modelo Digital de '
                                     'Elevação SRTM (Shuttle Radar Topography Mission).'},
 'annual_distribution': {'en': 'Annual distribution of detections of surface with water presence',
                         'es': 'Distribución anual de detecciones de superficie con presencia de agua',
                         'pt': 'Distribuição anual de detecções de superfície com presença de água'},
 'area': {'en': 'Area', 'es': 'Área', 'pt': 'Área'},
 'area2': {'en': 'Area', 'es': 'Area', 'pt': 'Area'},
 'atmospheric_demand': {'en': 'Atmospheric demand', 'es': 'Demanda atmosférica', 'pt': 'Demanda atmosférica'},
 'atmospheric_demand_day': {'en': 'Atmospheric demand on',
                            'es': 'Demanda ambiental del día',
                            'pt': 'Demanda atmosférica do dia'},
 'atributes': {'en': 'Attributes', 'es': 'Atributos', 'pt': 'Atributos'},
 'available_images': {'en': 'Available images', 'es': 'Imágenes disponibles', 'pt': 'Imagens disponíveis'},
 'average': {'en': 'Average', 'es': 'Promedio', 'pt': 'Média'},
 'average_yield': {'en': 'Average Yield', 'es': 'Rendimiento Medio', 'pt': 'Rendimento Médio'},
 'avg_adjusted_yield': {'en': 'Average Adjusted Yield',
                        'es': 'Rinde Medio Ajustado',
                        'pt': 'Rendimento Médio Ajustado'},
 'avg_dry_yield': {'en': 'Average Dry Yield', 'es': 'Rinde Medio Seco', 'pt': 'Rendimento Médio Seco'},
 'avg_moisture': {'en': 'Average Moisture', 'es': 'Humedad Media', 'pt': 'Umidade Média'},
 'avg_speed': {'en': 'Average Speed', 'es': 'Velocidad Media', 'pt': 'Velocidade Média'},
 'avg_wet_yield': {'en': 'Average Wet Yield', 'es': 'Rinde Medio Húmedo', 'pt': 'Rendimento Médio Úmido'},
 'band_max_min': {'en': 'Maximum/Minimum Band', 'es': 'Banda Máximo/Mínimo', 'pt': 'Banda Máximo/Mínimo'},
 'bf_sunf': {'en': 'V6 to Flower Bud', 'es': 'V6 a Botón Floral', 'pt': 'V6 até Botão Floral'},
 'box_y_cv': {'en': 'Boxplot and coefficient of variation by field',
              'es': 'Boxplot y coeficiente de variación por lote',
              'pt': 'Boxplot e coeficiente de variação por lote'},
 'choose_option': {'en': 'Choose an option', 'es': 'Elije una opción', 'pt': 'Escolha uma opção'},
 'cleaning_option': {'en': 'Statistical cleaning by the Savitzky–Golay method',
                     'es': 'Limpieza estadistica por el método Savitzky–Golay ',
                     'pt': 'Limpeza estatística pelo método Savitzky–Golay'},
 'clear': {'en': 'Clear', 'es': 'Despejado', 'pt': 'Limpo'},
 'cloudy': {'en': 'Cloudy', 'es': 'Nublado', 'pt': 'Nublado'},
 'coef_de_var': {'en': 'Coef. of Var.', 'es': 'Coef. de Var.', 'pt': 'Coef. de Var.'},
 'color_palette': {'en': 'Color Palette', 'es': 'Paleta de colores', 'pt': 'Paleta de Cores'},
 'colour': {'en': 'Colour', 'es': 'Color', 'pt': 'Cor'},
 'comentarios': {'en': 'Comments', 'es': 'Comentarios', 'pt': 'Comentários'},
 'comma_separated_values': {'en': 'Comma-separated values',
                            'es': 'Valores separados por comas',
                            'pt': 'Valores separados por vírgulas'},
 'contour_lines': {'en': 'Contour lines', 'es': 'Curvas de nivel', 'pt': 'Linhas de contorno'},
 'critical_period': {'en': 'Critical Period', 'es': 'Período Crítico', 'pt': 'Período Crítico'},
 'crop': {'en': 'Crop', 'es': 'Cultivo', 'pt': 'Cultura'},
 'crop_select': {'en': 'Select crop', 'es': 'Selecciona cultivo', 'pt': 'Selecione o Cultura'},
 'crop_selected_warning': {'en': 'The selected plot does not have a crop assigned. Please assign a crop in 360 and try '
                                 'again',
                           'es': 'El lote seleccionado no tiene un cultivo asignado. Por favor, asigná un cultivo en '
                                 '360 y volvé a intentarlo',
                           'pt': 'O lote selecionado não tem uma cultura atribuída. Por favor, atribua uma cultura no '
                                 '360 e tente novamente'},
 'crop_visualization': {'en': 'The selected crop type is not yet available for visualization. If you wish, you can '
                              'send us your suggestion and we will take it into account for future updates.',
                        'es': 'El tipo de cultivo seleccionado aún no está disponible para visualización. Si lo '
                              'deseás, podés enviarnos tu sugerencia y la tendremos en cuenta para futuras '
                              'actualizaciones.',
                        'pt': 'O tipo de cultura selecionado ainda não está disponível para visualização. Se quiser, '
                              'você pode nos enviar sua sugestão e a levaremos em consideração para futuras '
                              'atualizações.'},
 'crops': {'en': 'Crops', 'es': 'Cultivos', 'pt': 'Culturas'},
 'cuadrante': {'en': 'quadrant', 'es': 'cuadrante', 'pt': 'quadrante'},
 'custom': {'en': 'Custom', 'es': 'Personalizado', 'pt': 'Personalizado'},
 'custom_filter': {'en': 'Custom Filter', 'es': 'Filtro personalizado', 'pt': 'Filtro personalizado'},
 'cv': {'en': 'Coefficient of Variation (%)',
        'es': 'Coeficiente de Variación (%)',
        'pt': 'Coeficiente de Variação (%)'},
 'cv_rank': {'en': 'NDVI Standard Deviation and CV Ranking',
             'es': 'Ranking por Desvío Estándar y CV de NDVI',
             'pt': 'Classificação de Desvio Padrão e CV do NDVI'},
 'daily_precipitation': {'en': 'Daily precipitation:',
                         'es': 'Precipitaciones diarias:',
                         'pt': 'Precipitações diárias:'},
 'daily_values': {'en': 'Daily values', 'es': 'Valores diarios', 'pt': 'Valores diários'},
 'dashboard_benchmarking_description': {'en': 'This dashboard allows a comparative analysis of the fields loaded on '
                                              'the 360 platform, through the analysis of the NDVI index.',
                                        'es': 'Este tablero permite hacer un análisis comparativo de los lotes '
                                              'cargados en la plataforma 360, mediante el análisis del índice NDVI.',
                                        'pt': 'Este painel permite uma análise comparativa dos campos carregados na '
                                              'plataforma 360, através da análise do índice NDVI.'},
 'dashboard_indice_promedio_description': {'en': 'This dashboard allows the evaluation of fields in an establishment '
                                                 'based on the mean of satellite indices between two given dates, '
                                                 'analyzing mean values and intrafield variability. Different indices '
                                                 '(NDVI, NDRE, NDMI, SAVI, EVI, and NDWI) can be selected within it.',
                                           'es': 'Este tablero permite evaluar los lotes de un establecimiento a '
                                                 'partir del promedio de índices satelitales entre dos fechas dadas, '
                                                 'analizando valores medios y variabilidad intralote. Dentro del '
                                                 'mismo, se pueden seleccionar diferentes índices (NDVI, NDRE, NDMI, '
                                                 'SAVI, EVI y NDWI).',
                                           'pt': 'Este painel permite avaliar os lotes de um estabelecimento com base '
                                                 'na média dos índices de satélite entre duas datas dadas, analisando '
                                                 'valores médios e variabilidade intratalhão. Diferentes índices '
                                                 '(NDVI, NDRE, NDMI, SAVI, EVI e NDWI) podem ser selecionados nele.'},
 'dashboard_not_yet_available': {'en': 'This dashboard is not yet available in this Domain',
                                 'es': 'Este tablero aún no está disponible en este Dominio',
                                 'pt': 'Este painel ainda não está disponível neste Domínio'},
 'dashboards': {'en': 'Dashboards', 'es': 'Tableros', 'pt': 'Painéis'},
 'data_daily': {'en': 'Daily frequency data', 'es': 'Datos de frecuencia diaria', 'pt': 'Dados de frequência diária'},
 'data_download': {'en': 'Data download', 'es': 'Descarga de datos', 'pt': 'Download de dados'},
 'data_hourly': {'en': 'Hourly frequency data',
                 'es': 'Datos de frecuencia horaria',
                 'pt': 'Dados de frequência horária'},
 'data_model': {'en': 'Data by model', 'es': 'Datos por modelo', 'pt': 'Dados por modelo'},
 'data_visualization': {'en': 'Data Visualization', 'es': 'Visualización de datos', 'pt': 'Visualização de dados'},
 'database_update': {'en': 'The database is updated every hour. If your farm still does not appear, try clearing the '
                           'dashboard cache by clicking on the three dots in the upper right corner.',
                     'es': 'La base de datos se actualiza cada hora. Si tu establecimiento sigue sin aparecer, intenta '
                           'borrar la caché del tablero haciendo clic en los tres puntos que se encuentran en la '
                           'esquina superior derecha.',
                     'pt': 'O banco de dados é atualizado a cada hora. Se sua fazenda ainda não aparecer, tente limpar '
                           'o cache do painel clicando nos três pontos no canto superior direito.'},
 'date': {'en': 'Date:', 'es': 'Fecha:', 'pt': 'Data:'},
 'date2': {'en': 'Date', 'es': 'Fecha', 'pt': 'Data'},
 'date_range': {'en': 'Date Range', 'es': 'Rango de fechas', 'pt': 'Intervalo de datas'},
 'date_warning': {'en': 'The start date cannot be later than the end date.',
                  'es': 'La fecha de inicio no puede ser posterior a la fecha de fin.',
                  'pt': 'A data de início não pode ser posterior à data de término.'},
 'date_warning2': {'en': 'The maximum range allowed is 240 days.',
                   'es': 'El rango máximo permitido es de 240 días.',
                   'pt': 'O intervalo máximo permitido é de 240 dias.'},
 'date_warning3': {'en': 'The minimum range allowed between two dates is 15 days.',
                   'es': 'El rango mínimo permitido entre dos fechas es de 15 días.',
                   'pt': 'O intervalo mínimo permitido entre duas datas é de 15 dias.'},
 'date_warning_365': {'en': 'The maximum range allowed is 365 days.',
                      'es': 'El rango máximo permitido es de 365 días.',
                      'pt': 'O intervalo máximo permitido é de 365 dias.'},
 'degree_day_ajust': {'en': 'Degree/day adjustments per stage',
                      'es': 'Ajustes de grados/día por etapa',
                      'pt': 'Ajustes de graus/dia por etapa'},
 'dem_interval': {'en': 'Interval between contour lines (m)',
                  'es': 'Intervalo entre curvas de nivel (m)',
                  'pt': 'Intervalo entre curvas de nível (m)'},
 'description': {'en': 'Description', 'es': 'Descripción', 'pt': 'Descrição'},
 'desde': {'en': 'From', 'es': 'Desde', 'pt': 'Desde'},
 'desvio_estandar': {'en': 'Standard Deviation', 'es': 'Desvío estándar', 'pt': 'Desvio padrão'},
 'detection_count': {'en': 'Detection count', 'es': 'Cantidad de detecciones', 'pt': 'Quantidade de detecções'},
 'detection_prob': {'en': 'Probability', 'es': 'Probabilidad', 'pt': 'Probabilidade'},
 'detections_percentage': {'en': 'Detections percentage',
                           'es': 'Porcentaje de detecciones',
                           'pt': 'Percentual de detecções'},
 'dom': {'en': 'Sun', 'es': 'Dom', 'pt': 'Dom'},
 'domain': {'en': 'Domain', 'es': 'Dominio', 'pt': 'Domínio'},
 'download': {'en': 'Download', 'es': 'Descargar', 'pt': 'Descarga'},
 'download_csv': {'en': 'Download CSV', 'es': 'Descargar CSV', 'pt': 'Baixar CSV'},
 'download_geojson': {'en': 'Download GeoJSON File', 'es': 'Descargar archivo GeoJSON', 'pt': 'Baixar Arquivo GeoJSON'},
 'download_geojsons': {'en': 'Download GeoJSON Files',
                       'es': 'Descargar archivos GeoJSON',
                       'pt': 'Baixar Arquivos GeoJSON'},
 'download_surface_water_map': {'en': 'Download surface water map',
                                'es': 'Descargar mapa de agua superficial',
                                'pt': 'Baixar mapa de água superficial'},
 'download_surface_water_map2': {'en': 'Allows the download of the surface water detection map in GeoJSON format, '
                                       'represented as polygons.',
                                 'es': 'Permite la descarga del mapa de detección de agua superficial en formato '
                                       'GeoJSON, representado como polígonos.',
                                 'pt': 'Permite o download do mapa de detecção de água superficial em formato GeoJSON, '
                                       'representado como polígonos.'},
 'drizzle': {'en': 'Drizzle', 'es': 'Llovizna', 'pt': 'Garoa'},
 'duration_pc': {'en': 'Duration of critical period (°C/day)',
                 'es': 'Duración del período crítico (°C/día)',
                 'pt': 'Duração do período crítico (°C/dia)'},
 'elevation_m': {'en': 'Elevation (m)', 'es': 'Elevación (m)', 'pt': 'Elevação (m)'},
 'end': {'en': 'End', 'es': 'Fin', 'pt': 'Fim'},
 'end_date': {'en': 'End date', 'es': 'Fecha de fin', 'pt': 'Data de término'},
 'end_pc': {'en': 'End of critical period', 'es': 'Fin período crítico', 'pt': 'Fim do período crítico'},
 'end_planting_date': {'en': 'End planting date', 'es': 'Fecha de fin de siembra', 'pt': 'Data de fim do plantio'},
 'enviromental_demand': {'en': 'Environmental demand', 'es': 'Demanda ambiental', 'pt': 'Demanda ambiental'},
 'error_generating_maps': {'en': 'Error generating the maps.',
                           'es': 'Error al generar los mapas.',
                           'pt': 'Erro ao gerar os mapas.'},
 'error_message_date_picker': {'en': 'Select start and end date',
                               'es': 'Seleccione una fecha de inicio y fin',
                               'pt': 'Selecione uma data de início e término'},
 'establishment': {'en': 'Establishment', 'es': 'Establecimiento', 'pt': 'Estabelecimento'},
 'exclude': {'en': 'Exclude', 'es': 'Excluir', 'pt': 'Excluir'},
 'experimental_preview': {'en': 'Experimental Preview',
                          'es': 'Vista Previa Experimental',
                          'pt': 'Pré-visualização Experimental'},
 'extreme_max': {'en': 'Days with average temperatures above 35°C:',
                 'es': 'Días con temperaturas promedio superiores a 35°C:',
                 'pt': 'Dias com temperaturas médias acima de 35°C:'},
 'extreme_max_days': {'en': 'Number of days with average temperatures above 35°C:',
                      'es': 'Cantidad de días con temperaturas promedio superiores a 35°C:',
                      'pt': 'Quantidade de dias com temperaturas médias acima de 35°C:'},
 'extreme_min': {'en': 'Days with average temperatures below 2°C:',
                 'es': 'Días con temperaturas promedio inferiores a 2°C:',
                 'pt': 'Dias com temperaturas médias abaixo de 2°C:'},
 'extreme_min_days': {'en': 'Number of days with average temperatures below 2°C:',
                      'es': 'Cantidad de días con temperaturas promedio inferiores a 2°C:',
                      'pt': 'Quantidade de dias com temperaturas médias abaixo de 2°C:'},
 'extreme_temp': {'en': 'Extreme temperatures', 'es': 'Temperaturas extremas', 'pt': 'Temperaturas extremas'},
 'farm': {'en': 'Farm', 'es': 'Establecimiento', 'pt': 'Fazenda'},
 'farm_stats': {'en': 'Statistics by Field', 'es': 'Estadísticas por lote', 'pt': 'Estatísticas por lote'},
 'farms': {'en': 'Farms', 'es': 'Establecimientos', 'pt': 'Fazendas'},
 'field': {'en': 'Field', 'es': 'Lote', 'pt': 'Lote'},
 'field_description': {'en': 'Only the fields where water presence has been detected in at least one of their pixels '
                             'during the period covered by the database are listed. The establishment as a whole is '
                             'included first, considered as a single unit.',
                       'es': 'Se listan únicamente los lotes en los que se ha detectado la presencia de agua en al '
                             'menos uno de sus píxeles durante el período abarcado por la base de datos. En primer '
                             'lugar, se incluye el establecimiento completo considerado como una única unidad.',
                       'pt': 'Apenas os lotes onde foi detectada a presença de água em pelo menos um de seus pixels '
                             'durante o período coberto pelo banco de dados são listados. O estabelecimento como um '
                             'todo é incluído primeiro, considerado como uma única unidade.'},
 'field_name_gdf': {'en': 'Field', 'es': 'Lote', 'pt': 'Lote'},
 'fields': {'en': 'Fields', 'es': 'Lotes', 'pt': 'Lotes'},
 'fields_and_crops_dashboard_description': {'en': 'This dashboard provides a detailed view and analysis of the '
                                                  'composition of fields and crops registered in the 360 platform. It '
                                                  'also allows for the assessment of planting progress through the '
                                                  'analysis of planting date data.',
                                            'es': 'Este tablero ofrece una visión detallada y permite el análisis de '
                                                  'la composición de lotes y cultivos registrados en la plataforma '
                                                  '360. Además, facilita la evaluación del progreso de la siembra '
                                                  'mediante el análisis de los datos correspondientes a las fechas de '
                                                  'siembra.',
                                            'pt': 'Este painel oferece uma visão detalhada e permite a análise da '
                                                  'composição de lotes e culturas registradas na plataforma 360. Além '
                                                  'disso, facilita a avaliação do progresso do plantio por meio da '
                                                  'análise dos dados de datas de plantio.'},
 'fields_without_crops': {'en': 'Fields without crops', 'es': 'Lotes sin cultivos', 'pt': 'Lotes sem cultivos'},
 'fields_without_hybrids_or_varieties': {'en': 'Fields without hybrids/varieties',
                                         'es': 'Lotes sin híbridos/variedades',
                                         'pt': 'Lotes sem híbridos/variedades'},
 'fields_without_sowing_date': {'en': 'Fields without sowing date',
                                'es': 'Lotes sin fecha de siembra',
                                'pt': 'Lotes sem data de plantio'},
 'filling_potatoe': {'en': 'Flowering to Tuber Filling (BBCH 60–80)',
                     'es': 'Floración a Llenado de tubérculos (BBCH 60–80)',
                     'pt': 'Florescimento até Enchimento dos tubérculos (BBCH 60–80)'},
 'flag_leaf_wheat': {'en': 'Tillering to Flag Leaf Sheath (Z21–Z39)',
                     'es': 'Macollaje a Enc. Hoja bandera (Z21–Z39)',
                     'pt': 'Perfilhamento até a folha bandeira (Z21–Z39)'},
 'flood_count': {'en': 'Flood count', 'es': 'Cantidad de inundaciones', 'pt': 'Quantidade de inundações'},
 'flood_frequency': {'en': 'Flood frequency', 'es': 'Frecuencia de inundaciones', 'pt': 'Frequência de inundações'},
 'flood_metrics': {'en': 'Flood metrics', 'es': 'Métricas de inundaciones', 'pt': 'Métricas de inundações'},
 'floods_by_lot_and_year': {'en': 'Floods by lot and year',
                            'es': 'Inundaciones por lote y año',
                            'pt': 'Inundações por lote e ano'},
 'flower_canola': {'en': 'Flower Initiation to Flowering (BBCH 50–60)',
                   'es': 'Iniciación floral a Floración (BBCH 50–60)',
                   'pt': 'Início da floração até Florescimento (BBCH 50–60)'},
 'flower_corn': {'en': 'Flowering (R1)', 'es': 'Floración (R1)', 'pt': 'Florescimento (R1)'},
 'flower_init_canola': {'en': 'Rosette to Flower Initiation (BBCH 30–50)',
                        'es': 'Roseta a Iniciación floral (BBCH 30–50)',
                        'pt': 'Roseta até Início da floração (BBCH 30–50)'},
 'flower_peanut': {'en': 'Emergence to Flowering',
                   'es': 'Emergencia a Floración',
                   'pt': 'Emergência até Florescimento'},
 'flower_peggs_peanut': {'en': 'Flowering to Pegging',
                         'es': 'Floración a Clavado (pegs)',
                         'pt': 'Florescimento até Cravamento (pegs)'},
 'flower_potatoe': {'en': 'Vegetative Development to Flowering (BBCH 40–60)',
                    'es': 'Desarrollo vegetativo a Floración (BBCH 40–60)',
                    'pt': 'Desenvolvimento vegetativo até Florescimento (BBCH 40–60)'},
 'flower_sorghum': {'en': 'Flowering', 'es': 'Floración', 'pt': 'Florescimento'},
 'flower_sunf': {'en': 'Flower Bud to Flowering',
                 'es': 'Botón Floral a Floración',
                 'pt': 'Botão Floral até Florescimento'},
 'flower_wheat': {'en': 'Heading to Flowering (Z59–Z65)',
                  'es': 'Espigazón a Floración (Z59–Z65)',
                  'pt': 'Espigamento até Florescimento (Z59–Z65)'},
 'fog': {'en': 'Fog', 'es': 'Neblina', 'pt': 'Névoa'},
 'friday': {'en': 'Friday', 'es': 'Viernes', 'pt': 'Sexta-feira'},
 'fruit_peanut': {'en': 'Fruit filling', 'es': 'Llenado de frutos', 'pt': 'Enchimento de frutos'},
 'generate_altimetry_maps': {'en': 'Generate Altimetry Maps',
                             'es': 'Generar mapas de altimetría',
                             'pt': 'Gerar Mapas de Altimetria'},
 'generating_maps': {'en': 'Generating the maps...', 'es': 'Generando los mapas...', 'pt': 'Gerando os mapas...'},
 'grain_filling_corn': {'en': 'Grain filling (R2 to R5)',
                        'es': 'Llenado de granos (R2 a R5)',
                        'pt': ' enchimento de grãos (R2 a R5)'},
 'grain_filling_sorghum': {'en': 'Grain filling', 'es': 'Llenado de grano', 'pt': 'Enchimento de grãos'},
 'grain_filling_sunf': {'en': 'Flowering to Grain filling',
                        'es': 'Floración a Llenado de grano',
                        'pt': 'Florescimento até Enchimento de grãos'},
 'group': {'en': 'Group', 'es': 'Agrupar', 'pt': 'Agrupar'},
 'group_color': {'en': 'Group by color', 'es': 'Agrupar por color', 'pt': 'Agrupar por cor'},
 'grouping_selector': {'en': 'Grouping selector', 'es': 'Selector de agrupamiento', 'pt': 'Seletor de agrupamento'},
 'harvest_date': {'en': 'Harvest date', 'es': 'Fecha de cosecha', 'pt': 'Data de colheita'},
 'harvest_date_by': {'en': 'Harvest date by ', 'es': 'Fecha de cosecha por ', 'pt': 'Data de colheita por '},
 'harvest_progress': {'en': 'Harvest progress', 'es': 'Avance de cosecha', 'pt': 'Progresso da colheita'},
 'hasta': {'en': 'Until', 'es': 'Hasta', 'pt': 'Até'},
 'heading_wheat': {'en': 'Flag Leaf to Heading (Z39–Z59)',
                   'es': 'Hoja bandera a Espigazón (Z39–Z59)',
                   'pt': 'Folha bandeira até Espigamento (Z39–Z59)'},
 'heatmap': {'en': 'Heatmap by Hectares', 'es': 'Heatmap por Hectáreas', 'pt': 'Heatmap por Hectares'},
 'heatmap_description': {'en': 'The heatmap uses a blue color scale to visualize the intensity of water detections on '
                               'the surface by lot over the years, providing a clear representation of the temporal '
                               'distribution of this phenomenon across different lots.',
                         'es': 'El heatmap emplea una escala de color azul para visualizar la intensidad de las '
                               'detecciones de agua en superficie por lote a lo largo de los años, permitiendo una '
                               'representación clara de la distribución temporal de este fenómeno en los distintos '
                               'lotes.',
                         'pt': 'O heatmap usa uma escala de cores azuis para visualizar a intensidade das detecções de '
                               'água na superfície por lote ao longo dos anos, proporcionando uma representação clara '
                               'da distribuição temporal desse fenômeno nos diferentes lotes.'},
 'heatmap_title': {'en': 'Annual water detections by field',
                   'es': 'Cantidad anual de detecciones de agua en superficie por lote',
                   'pt': 'Quantidade anual de detecções de agua na superfície por lote'},
 'heatmap_yield': {'en': 'Heatmap by Yield', 'es': 'Heatmap por Rinde', 'pt': 'Heatmap por Rendimento'},
 'hectares': {'en': 'Hectares', 'es': 'Hectáreas', 'pt': 'Hectares'},
 'hectares_by': {'en': 'Hectares by', 'es': 'Hectáreas por', 'pt': 'Hectares por'},
 'hectares_per_date': {'en': 'Hectares per seeding date',
                       'es': 'Hectáreas por fecha de siembra',
                       'pt': 'Hectares por data de semeadura'},
 'hectares_per_harvest_date': {'en': 'Hectares per harvest date',
                               'es': 'Hectáreas por fecha de cosecha',
                               'pt': 'Hectares por data de colheita'},
 'hidric_risk_description': {'en': 'This interactive panel provides tools to analyze, for each field on a farm,'
                                    ' the detection of surface water presence using satellite imagery.',
                             'es': 'Este panel interactivo ofrece una herramienta para analizar, para cada lote de un '
                                   'establecimiento, la detección de la presencia de agua en superficie mediante el '
                                   'uso de imágenes satelitales.',
                             'pt': 'Este painel interativo oferece uma ferramenta para analisar, para cada lote de um '
                                   'estabelecimento, a detecção da presença de água na superfície por meio de imagens '
                                   'de satélite.'},
 'high_temp': {'en': 'Temperatures >35°C', 'es': 'Temperaturas >35°C', 'pt': 'Temperaturas >35°C'},
 'histogram_description': {'en': 'This histogram shows the annual distribution, expressed as a percentage, of total '
                                 'surface water detections. It provides a detailed view of how water observations are '
                                 'distributed throughout the year, allowing for the identification of patterns and '
                                 'trends in water presence during different periods.',
                           'es': 'Este histograma muestra la distribución anual, expresada en porcentaje, de las '
                                 'detecciones totales de agua en superficie. Este gráfico proporciona una visión '
                                 'detallada de cómo se distribuyen las observaciones de agua a lo largo del año, '
                                 'permitiendo identificar patrones y tendencias en la presencia de agua en diferentes '
                                 'períodos.',
                           'pt': 'Este histograma mostra a distribuição anual, expressa em percentual, das detecções '
                                 'totais de água na superfície. Este gráfico fornece uma visão detalhada de como as '
                                 'observações de água são distribuídas ao longo do ano, permitindo identificar padrões '
                                 'e tendências na presença de água durante diferentes períodos.'},
 'historical_climate_analysis': {'en': 'Historical climate analysis',
                                 'es': 'Análisis histórico del clima',
                                 'pt': 'Análise histórica do clima'},
 'hour': {'en': 'Hour', 'es': 'Hora', 'pt': 'Hora'},
 'humidity': {'en': 'Humidity', 'es': 'Humedad', 'pt': 'Umidade'},
 'hybrid_varieties': {'en': 'Hybrids / Varieties', 'es': 'Híbridos / Variedades', 'pt': 'Híbridos / Variedades'},
 'hybrid_variety': {'en': 'Hybrid / Variety', 'es': 'Híbrido / Variedad', 'pt': 'Híbrido / Variedade'},
 'hydric_risk': {'en': 'Hydric risk', 'es': 'Riesgo hídrico', 'pt': 'Risco hídrico'},
 'include': {'en': 'Include', 'es': 'Incluir', 'pt': 'Incluir'},
 'index': {'en': 'Index', 'es': 'Índice', 'pt': 'Índice'},
 'invert_selection_for': {'en': 'Invert selection for', 'es': 'Invertir selección para', 'pt': 'Inverter seleção para'},
 'jan_dec_2018': {'en': 'Jan-Dec 2018', 'es': 'Ene-Dic 2018', 'pt': 'Jan-Dez 2018'},
 'jan_dec_2019': {'en': 'Jan-Dec 2019', 'es': 'Ene-Dic 2019', 'pt': 'Jan-Dez 2019'},
 'jan_dec_2020': {'en': 'Jan-Dec 2020', 'es': 'Ene-Dic 2020', 'pt': 'Jan-Dez 2020'},
 'jan_dec_2021': {'en': 'Jan-Dec 2021', 'es': 'Ene-Dic 2021', 'pt': 'Jan-Dez 2021'},
 'jan_dec_2022': {'en': 'Jan-Dec 2022', 'es': 'Ene-Dic 2022', 'pt': 'Jan-Dez 2022'},
 'jan_dec_2023': {'en': 'Jan-Dec 2023', 'es': 'Ene-Dic 2023', 'pt': 'Jan-Dez 2023'},
 'jue': {'en': 'Thu', 'es': 'Jue', 'pt': 'Qui'},
 'kriged_map': {'en': 'Kriged map', 'es': 'Mapa krigeado', 'pt': 'Mapa krigado'},
 'labels': {'en': 'Labels', 'es': 'Etiquetas', 'pt': 'Rótulos'},
 'language': {'en': 'Language', 'es': 'Idioma', 'pt': 'Idioma'},
 'last_15_days': {'en': 'Last 15 Days', 'es': 'Últimos 15 Días', 'pt': 'Últimos 15 Dias'},
 'last_180_days': {'en': 'Last 180 Days', 'es': 'Últimos 180 Días', 'pt': 'Últimos 180 Dias'},
 'last_30_days': {'en': 'Last 30 Days', 'es': 'Últimos 30 Días', 'pt': 'Últimos 30 Dias'},
 'last_365_days': {'en': 'Last 365 Days', 'es': 'Últimos 365 Días', 'pt': 'Últimos 365 Dias'},
 'last_60_days': {'en': 'Last 60 Days', 'es': 'Últimos 60 Días', 'pt': 'Últimos 60 Dias'},
 'last_7_days': {'en': 'Last 7 Days', 'es': 'Últimos 7 Días', 'pt': 'Últimos 7 Dias'},
 'last_90_days': {'en': 'Last 90 Days', 'es': 'Últimos 90 Días', 'pt': 'Últimos 90 Dias'},
 'last_djf': {'en': 'Last DJF (Dec-Feb)', 'es': 'Último DEF (Dic-Feb)', 'pt': 'Último DEF (Dez-Fev)'},
 'last_jja': {'en': 'Last JJA (Jun-Aug)', 'es': 'Último JJA (Jun-Ago)', 'pt': 'Último JJA (Jun-Ago)'},
 'last_mam': {'en': 'Last MAM (Mar-May)', 'es': 'Último MAM (Mar-May)', 'pt': 'Último MAM (Mar-Mai)'},
 'last_son': {'en': 'Last SON (Sept-Nov)', 'es': 'Último SON (Sep-Nov)', 'pt': 'Último SON (Set-Nov)'},
 'leaf_sorghum': {'en': 'Emergence to 5 leaves', 'es': 'Emergencia a 5 hojas', 'pt': 'Emergência até 5 folhas'},
 'logout': {'en': 'Logout', 'es': 'Cerrar Sesión', 'pt': 'Sair'},
 'low_temp': {'en': 'Temperatures < 2°C', 'es': 'Temperaturas < 2°C', 'pt': 'Temperaturas < 2°C'},
 'lower_fence': {'en': 'Lower fence', 'es': 'Limite inferior', 'pt': 'Limite inferior'},
 'lun': {'en': 'Mon', 'es': 'Lun', 'pt': 'Seg'},
 'machinery': {'en': 'Machinery', 'es': 'Maquinaria', 'pt': 'Maquinário'},
 'map_d': {'en': 'Map', 'es': 'Mapa', 'pt': 'mapa'},
 'map_d2': {'en': 'Download map of flooded areas',
            'es': 'Descargar mapa de areas inundadas',
            'pt': 'Descarga mapa das áreas alagadas'},
 'map_pixels_water_detected': {'en': 'The map shows the pixels where the presence of surface water was detected at '
                                     'least once during the period covered by the database.',
                               'es': 'El mapa presenta los píxeles en los que se detectó la presencia de agua '
                                     'superficial al menos una vez durante el período cubierto por la base de datos.',
                               'pt': 'O mapa apresenta os pixels onde a presença de água superficial foi detectada '
                                     'pelo menos uma vez durante o período coberto pelo banco de dados.'},
 'map_select_fields': {'en': 'Map of Selected FIelds',
                       'es': 'Mapa de Lotes Seleccionados',
                       'pt': 'Mapa dos Lotes Selecionados'},
 'map_type_selector': {'en': 'Map type selector', 'es': 'Selector de tipo de mapa', 'pt': 'Seletor de tipo de mapa'},
 'mapped_hectares': {'en': 'Mapped hectares', 'es': 'Hectáreas mapeadas', 'pt': 'Hectares mapeadas'},
 'mar': {'en': 'Tue', 'es': 'Mar', 'pt': 'Ter'},
 'maturity_canola': {'en': 'Filling to maturity (BBCH 70–89)',
                     'es': 'Llenado a madurez (BBCH 70–89)',
                     'pt': 'Enchimento até maturação (BBCH 70–89)'},
 'maturity_corn': {'en': 'Physiological maturity (R6)',
                   'es': 'Madurez fisiológica (R6)',
                   'pt': 'Maturidade fisiológica (R6)'},
 'maturity_peanut': {'en': 'Physiological maturity', 'es': 'Madurez fisiológica', 'pt': 'Maturidade fisiológica'},
 'maturity_potatoe': {'en': 'Filling to Maturity (BBCH 80–89)',
                      'es': 'Llenado a madurez (BBCH 80–89)',
                      'pt': 'Enchimento até Maturidade (BBCH 80–89)'},
 'maturity_sorghum': {'en': 'Physiological maturity', 'es': 'Madurez fisiológica', 'pt': 'Maturidade fisiológica'},
 'maturity_sunf': {'en': 'Filling to physiological maturity',
                   'es': 'Llenado a madurez fisiológica',
                   'pt': 'Enchimento até maturidade fisiológica'},
 'maturity_wheat': {'en': 'Grain filling to maturity (Z65–Z89)',
                    'es': 'Llenado de grano a madurez (Z65–Z89)',
                    'pt': 'Enchimento de grãos até a maturação (Z65–Z89)'},
 'maximo': {'en': 'Maximum', 'es': 'Máximo', 'pt': 'Máximo'},
 'maximum': {'en': 'Maximum', 'es': 'Máximo', 'pt': 'Máximo'},
 'mean': {'en': 'Mean', 'es': 'Media', 'pt': 'Média'},
 'mean_masculine': {'en': 'Mean', 'es': 'Medio', 'pt': 'Média'},
 'median': {'en': 'Median', 'es': 'Mediana', 'pt': 'Mediana'},
 'mediana': {'en': 'Median', 'es': 'Mediana', 'pt': 'Mediana'},
 'metrics': {'en': 'Metrics', 'es': 'Métricas', 'pt': 'Métricas'},
 'mie': {'en': 'Wed', 'es': 'Mié', 'pt': 'Qua'},
 'minimo': {'en': 'Minimum', 'es': 'Mínimo', 'pt': 'Mínimo'},
 'minimum': {'en': 'Minimum', 'es': 'Mínimo', 'pt': 'Mínimo'},
 'models_mean': {'en': 'Average of climate models',
                 'es': 'Promedio de modelos climáticos',
                 'pt': 'Média dos modelos climáticos'},
 'moisture': {'en': 'Moisture (%)', 'es': 'Humedad (%)', 'pt': 'Umidade (%)'},
 'moisture_tooltip': {'en': 'Moisture', 'es': 'Humedad', 'pt': 'Umidade)'},
 'monday': {'en': 'Monday', 'es': 'Lunes', 'pt': 'Segunda-feira'},
 'monitor': {'en': 'Monitor', 'es': 'Monitor', 'pt': 'Monitor'},
 'month': {'en': 'Month', 'es': 'Mes', 'pt': 'Mês'},
 'monthly_acumulated': {'en': 'Monthly accumulated precipitation:',
                        'es': 'Precipitaciones acumuladas mensualmente:',
                        'pt': 'Precipitações acumuladas mensalmente:'},
 'monthly_recurrence': {'en': 'Recurrence', 'es': 'Recurrencia', 'pt': 'Recorrência'},
 'multiseleccion_establecimieto': {'en': 'Selection of fields from more than one farm',
                                   'es': 'Selección de lotes de más de un establecimiento',
                                   'pt': 'Seleção de lotes de mais de um estabelecimento'},
 'ndvi_boxplot': {'en': 'NDVI BOXPLOT', 'es': 'Boxplot de NDVI', 'pt': 'Boxplot NDVI'},
 'ndvi_date': {'en': 'NDVI data by date', 'es': 'Datos NDVI por fecha', 'pt': 'Dados NDVI por data'},
 'ndvi_heatmap': {'en': 'NDVI Heatmap', 'es': 'Heatmap de NDVI ', 'pt': 'Heatmap NDVI'},
 'ndvi_integral': {'en': 'NDVI Integral', 'es': 'Integral de NDVI', 'pt': 'Integral de NDVI'},
 'ndvi_integral_prom': {'en': 'Average NDVI integral',
                        'es': 'Integral de NDVI promedio',
                        'pt': 'Integral médio do NDVI'},
 'ndvi_integral_rank': {'en': 'NDVI Integral', 'es': 'Integral de NDVI', 'pt': 'Integral do NDVI'},
 'ndvi_results': {'en': 'Interpolated NDVI Results',
                  'es': 'Resultados de NDVI Interpolado',
                  'pt': 'Resultados NDVI Interpolado'},
 'ndvi_sd': {'en': 'NDVI Standard Deviation', 'es': 'Desvío Estándar de NDVI', 'pt': 'Desvio Padrão do NDVI'},
 'ndvi_sd_rank': {'en': 'NDVI Standard Deviation ', 'es': 'Desvío Estándar de NDVI', 'pt': 'Desvio Padrão do NDVI'},
 'ndvi_serie': {'en': 'NDVI Time Series', 'es': 'Serie Temporal NDVI', 'pt': 'Série Temporal do NDVI'},
 'ndvi_serie_prom': {'en': 'Average NDVI Time Series',
                     'es': 'Serie Temporal NDVI Promedio',
                     'pt': 'Série Temporal Média de NDVI'},
 'no_chart_generated': {'en': 'No chart was generated for the establishment.',
                        'es': 'No se generó un gráfico para el establecimiento.',
                        'pt': 'Nenhum gráfico foi gerado para o estabelecimento.'},
 'no_grouping': {'en': 'No group', 'es': 'No agrupar', 'pt': 'Não agrupar'},
 'no_hight_temp': {'en': 'No days with temperatures above 35°C were found',
                   'es': 'No se encontraron días con temperaturas mayores a 35°C',
                   'pt': 'Não foram encontrados dias com temperaturas acima de 35°C'},
 'no_low_temp': {'en': 'No days with temperatures below 2°C were found',
                 'es': 'No se encontraron días con temperaturas menores a 2°C',
                 'pt': 'Não foram encontrados dias com temperaturas abaixo de 2°C'},
 'no_surface_water_lots': {'en': 'No lots with surface water detected.',
                           'es': 'No se detectaron lotes con presencia de agua superficial.',
                           'pt': 'Não foram detectados lotes com presença de água superficial.'},
 'not_asigned': {'en': '-Not assigned-', 'es': '-No asignado-', 'pt': '-No asignado-'},
 'not_detecctions': {'en': 'No detections', 'es': 'Sin detecciones', 'pt': 'Nenhuma detecção'},
 'ongoing': {'en': 'On going', 'es': 'En curso', 'pt': 'Em andamento'},
 'only_no_date': {'en': 'Only Without Date', 'es': 'Solo Sin Fecha', 'pt': 'Somente Sem Data'},
 'operator': {'en': 'Operator', 'es': 'Operador', 'pt': 'Operador'},
 'out_range_seeding_date': {'en': 'The planting date for the selected field is outside the analyzed time range',
                            'es': 'La fecha de siembra del lote seleccionado se encuentra fuera del intervalo temporal '
                                  'analizado',
                            'pt': 'A data de plantio do lote selecionado está fora do intervalo temporal analisado'},
 'partly_cloudy': {'en': 'Partly cloudy', 'es': 'Parcialmente nublado', 'pt': 'Parcialmente nublado'},
 'pegging_peanut': {'en': 'Pegging to Start of Filling',
                    'es': 'Clavado a Inicio de Llenado',
                    'pt': 'Cravamento até Início do Enchimento'},
 'percentage': {'en': 'Percentage', 'es': 'Porcentaje', 'pt': 'Porcentagem'},
 'permanent_water': {'en': 'Permanent water', 'es': 'Agua permanente', 'pt': 'Agua permanente'},
 'phenological_plot': {'en': 'Crop phenological stages according to accumulated thermal time',
                       'es': 'Etapas fenológicas del cultivo según tiempo térmico acumulado',
                       'pt': 'Estágios fenológicos da cultura conforme o tempo térmico acumulado'},
 'phenological_title': {'en': 'Phenological evolution of the crop',
                        'es': 'Evolución fenológica del cultivo',
                        'pt': 'Evolução fenológica da cultura'},
 'platform_width': {'en': 'Platform Width', 'es': 'Ancho de Labor', 'pt': 'Largura da Plataforma'},
 'pod_filling_canola': {'en': 'Flowering to Pod filling (BBCH 60–70)',
                        'es': 'Floración a Llenado de vainas (BBCH 60–70)',
                        'pt': 'Florescimento até Enchimento de vagens (BBCH 60–70)'},
 'point_map_by_field_according_to': {'en': 'Map by Field According to',
                                     'es': 'Mapa de lotes según',
                                     'pt': 'Mapa por Campo Segundo'},
 'point_map_by_layer_according_to': {'en': 'Point Map by Layer According to',
                                     'es': 'Mapa de puntos por capa según',
                                     'pt': 'Mapa de Pontos por Camada Segundo'},
 'points': {'en': 'Points', 'es': 'Puntos', 'pt': 'Pontos'},
 'polygons': {'en': 'Polygons', 'es': 'Polígonos', 'pt': 'Polígonos'},
 'por_lote': {'en': 'by field', 'es': 'por lote', 'pt': 'por lote'},
 'pre_flower_sorghum': {'en': '5 leaves to pre-flowering',
                        'es': '5 hojas a prefloración',
                        'pt': '5 folhas até pré-florescimento'},
 'precipitation': {'en': 'Precipitation', 'es': 'Precipitaciones', 'pt': 'Precipitações'},
 'precipitation_day': {'en': 'Precipitation on', 'es': 'Precipitación del día', 'pt': 'Precipitação do dia'},
 'precipitation_probability': {'en': 'Precip. probability',
                               'es': 'Prob. de precipitaciones',
                               'pt': 'Prob. de precipitação'},
 'precipitation_resume': {'en': 'Precipitation record by periods',
                          'es': 'Registro de precipitaciones por periodos',
                          'pt': 'Registro de precipitações por períodos'},
 'pressure': {'en': 'Pressure', 'es': 'Presión', 'pt': 'Pressão'},
 'probability': {'en': 'Probability', 'es': 'Probabilidad', 'pt': 'Probabilidade'},
 'probability_description': {'en': 'The indicated value represents the probability of detecting the presence of '
                                   'surface water, calculated based on all analyzed observations.',
                             'es': 'El valor indicado representa la probabilidad de detección de la presencia de agua '
                                   'en superficie, calculada en función de todas las observaciones analizadas.',
                             'pt': 'O valor indicado representa a probabilidade de detecção da presença de água na '
                                   'superfície, calculada com base em todas as observações analisadas.'},
 'production': {'en': 'Production', 'es': 'Rinde Total', 'pt': 'Produção Total'},
 'promedio_entre': {'en': 'mean between', 'es': 'promedio entre', 'pt': 'média entre'},
 'proximamente': {'en': 'Coming Soon!', 'es': 'Próximamente!', 'pt': 'Em Breve!'},
 'quantil_1': {'en': 'First Quartile', 'es': 'Quantil 1', 'pt': 'Primeiro Quartil'},
 'quantil_3': {'en': 'Third Quartile', 'es': 'Quantil 3', 'pt': 'Terceiro Quartil'},
 'r1_soybean': {'en': 'V3 to R1 (Flowering)', 'es': 'V3 a R1 (Floración)', 'pt': 'V3 até R1 (Florescimento)'},
 'r3_soybean': {'en': 'R1 to R3 (Fruit)', 'es': 'R1 a R3 (Fruto)', 'pt': 'R1 até R3 (Fruto)'},
 'r5_soybean': {'en': 'R3 to R5 (Grain filling)',
                'es': 'R3 a R5 (Llenado grano)',
                'pt': 'R3 até R5 (Enchimento de grãos)'},
 'r7_soybean': {'en': 'R5 to R7 (Maturity)', 'es': 'R5 a R7 (Madurez)', 'pt': 'R5 até R7 (Maturação)'},
 'rain': {'en': 'Rain', 'es': 'Lluvia', 'pt': 'Chuva'},
 'range': {'en': 'Range', 'es': 'Rango', 'pt': 'Intervalo'},
 'raw_data_option': {'en': 'Raw data', 'es': 'Datos sin procesar', 'pt': 'Dados não trarados'},
 'raw_map': {'en': 'Raw map', 'es': 'Mapa crudo', 'pt': 'Mapa bruto'},
 'recurrence_decription': {'en': 'The graph represents the months in which surface water was detected in at least one '
                                 'of the pixels that make up the analyzed lot area, during the period covered by the '
                                 'database.',
                           'es': 'La gráfica representa los meses en los cuales se detectó la presencia de agua en al '
                                 'menos uno de los píxeles que componen el área del lote analizado, durante el período '
                                 'abarcado por la base de datos.',
                           'pt': 'O gráfico representa os meses em que foi detectada a presença de água em pelo menos '
                                 'um dos pixels que compõem a área do lote analisado, durante o período coberto pela '
                                 'base de dados.'},
 'remaining_time': {'en': 'Approximate remaining time: ',
                    'es': 'Tiempo restante aproximado: ',
                    'pt': 'Tempo restante aproximado'},
 'requested_by': {'en': 'Requested by: ', 'es': 'Solicitado por: ', 'pt': 'Solicitado por: '},
 'rosette_canola': {'en': 'Emergence to Rosette (BBCH 10–30)',
                    'es': 'Emergencia a Roseta (BBCH 10–30)',
                    'pt': 'Emergência até Roseta (BBCH 10–30)'},
 'sab': {'en': 'Sat', 'es': 'Sáb', 'pt': 'Sáb'},
 'saturday': {'en': 'Saturday', 'es': 'Sábado', 'pt': 'Sábado'},
 'season': {'en': 'Season', 'es': 'Campaña', 'pt': 'Safra'},
 'seasonal_water': {'en': 'Seasonal water', 'es': 'Agua estacional', 'pt': 'Agua sazonal'},
 'seed_date_filter': {'en': 'Filter by sowing date',
                      'es': 'Filtrar por fecha de siembra',
                      'pt': 'Filtrar por data de semeadura'},
 'seeding_date': {'en': 'Seeding Date', 'es': 'Fecha de siembra', 'pt': 'Data de Semeadura'},
 'seeding_date_by': {'en': 'Seeding Date by ', 'es': 'Fecha de siembra por ', 'pt': 'Data de Semeadura por '},
 'seeding_progress': {'en': 'Seeding progress', 'es': 'Avance de siembra', 'pt': 'Progresso da semeadura'},
 'seleccion_unica_establecimiento': {'en': 'Selection of a complete farm',
                                     'es': 'Selección de un establecimiento completo',
                                     'pt': 'Seleção de um estabelecimento completo'},
 'select_all': {'en': 'Select all', 'es': 'Seleccionar todo', 'pt': 'Selecionar tudo'},
 'select_date_range': {'en': 'Date range', 'es': ' Rango de fechas', 'pt': 'Intervalo de datas'},
 'select_date_range_analysis': {'en': 'Analysis date range',
                                'es': ' Rango de fechas de análisis',
                                'pt': 'Intervalo de datas de análise'},
 'select_date_range_bench': {'en': 'Analysis date range',
                             'es': ' Rango de fechas de análisis',
                             'pt': 'Intervalo de datas de análise'},
 'select_date_range_crops': {'en': 'Sowing date range',
                             'es': ' Rango de fechas de siembra',
                             'pt': 'Faixa de datas de semeadura'},
 'select_date_range_yield': {'en': 'Harvest date range',
                             'es': ' Rango de fechas de cosecha',
                             'pt': 'Faixa de datas de colheita'},
 'select_fields': {'en': 'Selected Fields', 'es': 'Lotes Seleccionados', 'pt': 'Lotes Selecionados'},
 'select_grouping_field': {'en': 'Select a grouping field:',
                           'es': 'Seleccione un campo de agrupamiento:',
                           'pt': 'Selecione um campo de agrupamento:'},
 'select_model': {'en': 'Select a model', 'es': 'Selecciona un modelo', 'pt': 'Selecione um modelo'},
 'select_warning': {'en': 'You must select a field to continue',
                    'es': 'Debe seleccionar un lote para continuar',
                    'pt': 'Você deve selecionar um campo para continuar'},
 'select_yield_layer_warning': {'en': 'You must select a yield layer to continue',
                                'es': 'Debe seleccionar una capa de rindes para continuar',
                                'pt': 'Você deve selecionar uma camada de rendimento para continuar'},
 'selected_date_range': {'en': 'Selected Date Range:',
                         'es': 'Rango de Fechas Seleccionado:',
                         'pt': 'Intervalo de Datas Seleccionado:'},
 'selected_establishment_map': {'en': 'Selected establishment map',
                                'es': 'Mapa del establecimiento seleccionado',
                                'pt': 'Mapa do estabelecimento selecionado'},
 'serie_demanda_ambiental': {'en': 'Time series of ET0 and VPD',
                             'es': 'Serie temporal de ET0 y VPD',
                             'pt': 'Série temporal de ET0 e VPD'},
 'snow': {'en': 'Snow', 'es': 'Nieve', 'pt': 'Neve'},
 'soil_moisture': {'en': 'Soil moisture', 'es': 'Humedad del suelo', 'pt': 'Umidade do solo'},
 'soil_moisture_0_9_cm': {'en': 'Soil moisture 0 to 9 cm',
                          'es': 'Humedad del suelo 0 a 9 cm',
                          'pt': 'Umidade do solo 0 a 9 cm'},
 'soil_moisture_27_81_cm': {'en': 'Soil moisture 27 to 81 cm',
                            'es': 'Humedad del suelo 27 a 81 cm',
                            'pt': 'Umidade do solo 27 a 81 cm'},
 'soil_moisture_9_27_cm': {'en': 'Soil moisture 9 to 27 cm',
                           'es': 'Humedad del suelo 9 a 27 cm',
                           'pt': 'Umidade do solo 9 a 27 cm'},
 'soil_moisture_evolution_depths': {'en': 'Soil moisture evolution at different depths',
                                    'es': 'Evolución de la humedad del suelo en distintas profundidades',
                                    'pt': 'Evolução da umidade do solo em diferentes profundidades'},
 'soil_moisture_map_saocom': {'en': 'Soil moisture map SAOCOM',
                              'es': 'Mapa humedad del suelo SAOCOM',
                              'pt': 'Mapa de umidade do solo SAOCOM'},
 'soil_temp': {'en': 'Soil temperature evolution 0 to 6 cm',
               'es': 'Evolución de la temperatura del suelo 0 a 6 cm',
               'pt': 'Evolução da temperatura do solo de 0 a 6 cm'},
 'soil_temp2': {'en': 'Soil temperature', 'es': 'Temperatura del suelo', 'pt': 'Temperatura do solo'},
 'soil_type': {'en': 'Select a soil type', 'es': 'Selecciona un tipo de suelo', 'pt': 'Selecione um tipo de solo'},
 'soil_water_content_avg_50cm': {'en': 'Volumetric water content in the soil as an average up to 50 cm depth',
                                 'es': 'Contenido volumétrico de agua en el suelo como promedio hasta los 50 cm de '
                                       'profundidad',
                                 'pt': 'Conteúdo volumétrico de água no solo como média até 50 cm de profundidade'},
 'sowing_emergence': {'en': 'Sowing to Emergence (VE)',
                      'es': 'Siembra a Emergencia (VE)',
                      'pt': 'Semeadura à Emergência (VE)'},
 'sowing_emergence2': {'en': 'Sowing to Emergence', 'es': 'Siembra a Emergencia', 'pt': 'Semeadura à Emergência'},
 'stage': {'en': 'Stage', 'es': 'Etapa', 'pt': 'Etapa'},
 'start': {'en': 'Start', 'es': 'Inicio', 'pt': 'Início'},
 'start_date': {'en': 'Start date', 'es': 'Fecha de inicio', 'pt': 'Data de inicio'},
 'start_pc': {'en': 'Start of critical period', 'es': 'Inicio período crítico', 'pt': 'Início do período crítico'},
 'start_pc2': {'en': 'Start of critical period (°C/day)',
               'es': 'Inicio del período crítico (°C/día)',
               'pt': 'Início do período crítico (°C/dia)'},
 'start_planting_date': {'en': 'Start planting date',
                         'es': 'Fecha de inicio de siembra',
                         'pt': 'Data de início do plantio'},
 'storm': {'en': 'Storm', 'es': 'Tormenta', 'pt': 'Tempestade'},
 'sunday': {'en': 'Sunday', 'es': 'Domingo', 'pt': 'Domingo'},
 'surface_water_map': {'en': 'Surface water map', 'es': 'Mapa de agua superficial', 'pt': 'Mapa de água superficial'},
 'temp_avg_min_max': {'en': 'Average, minimum and maximum daily temperatures',
                      'es': 'Temperaturas promedio, mínimas y máximas diarias',
                      'pt': 'Temperaturas médias, mínimas e máximas diárias'},
 'temperature': {'en': 'Temperature', 'es': 'Temperatura', 'pt': 'Temperatura'},
 'temperature_2m': {'en': 'Average temperature', 'es': 'Temperatura media', 'pt': 'Temperatura média'},
 'temperature_day': {'en': 'Temperature on', 'es': 'Temperatura del día', 'pt': 'Temperatura do dia'},
 'temperature_maxima': {'en': 'Maximum temperature', 'es': 'Temperatura máxima', 'pt': 'Temperatura máxima'},
 'temperature_minima': {'en': 'Minimum temperature', 'es': 'Temperatura mínima', 'pt': 'Temperatura mínima'},
 'text_to_search_whithin': {'en': 'Text to search within',
                            'es': 'Texto a buscar dentro de',
                            'pt': 'Texto a procurar dentro de'},
 'thursday': {'en': 'Thursday', 'es': 'Jueves', 'pt': 'Quinta-feira'},
 'tillering_wheat': {'en': 'Emergence to Tillering (Z10–Z21)',
                     'es': 'Emergencia a Macollaje (Z10–Z21)',
                     'pt': 'Emergência ao Perfilhamento (Z10–Z21)'},
 'title': {'en': 'Fields and Crops Dashboard',
           'es': 'Tablero de Lotes y Cultivos',
           'pt': 'Painel de Campos e Cultivos'},
 'title_benchmarking': {'en': 'Benchmarking Dashboard',
                        'es': 'Tablero de Benchmarking',
                        'pt': 'Painel de Benchmarking'},
 'title_indice_promedio': {'en': 'Mean and variability index Dashboard',
                           'es': 'Tablero de Indice promedio y variabilidad',
                           'pt': 'Painel de Índice de média e variabilidade'},
 'title_yield': {'en': 'Yield Dashboard', 'es': 'Tablero de Rindes', 'pt': 'Painel de Rendimento'},
 'tooltip_raw': {'en': 'The data used to create the graph was previously filtered using the cloud mask provided by the '
                       'European Space Agency (ESA). This process ensures the elimination of data influenced by '
                       'cloudiness, thus guaranteeing the precision and reliability of the results presented.',
                 'es': 'Los datos utilizados en la confección del gráfico fueron previamente filtrados empleando la '
                       'máscara de nubes proporcionada por la Agencia Espacial Europea (ESA). Este proceso asegura la '
                       'eliminación de datos influenciados por la nubosidad, garantizando así la precisión y '
                       'confiabilidad de los resultados presentados.',
                 'pt': 'Os dados utilizados para criar o gráfico foram previamente filtrados utilizando a máscara de '
                       'nuvem fornecida pela Agência Espacial Europeia (ESA). Este processo garante a eliminação dos '
                       'dados influenciados pela nebulosidade, garantindo assim a precisão e confiabilidade dos '
                       'resultados apresentados.'},
 'tooltip_sg': {'en': 'The Savitzky–Golay method performs additional statistical filtering on the data after applying '
                      'the ESA cloud mask.',
                'es': 'El método Savitzky–Golay realiza un filtrado estadistico adicional sobre los datos tras la '
                      'aplicación de la máscara de nubes de la ESA.',
                'pt': 'O método Savitzky-Golay realiza uma filtragem estatística  adicional nos dados após a aplicação '
                      'da máscara de nuvem ESA.'},
 'tooltip_sg2': {'en': 'Before plotting, additional data processing was carried out using the Savitzky-Golay method. '
                       'This method applies statistical filtering on data already cleaned with the European Space '
                       'Agency (ESA) cloud mask, thus improving the smoothness and precision of the analyzed time '
                       'series.',
                 'es': 'Antes de la elaboración del gráfico, se llevó a cabo un procesamiento adicional de los datos '
                       'mediante el método Savitzky-Golay. Este método aplica un filtrado estadístico sobre los datos '
                       'ya depurados con la máscara de nubes de la Agencia Espacial Europea (ESA), mejorando así la '
                       'suavidad y la precisión de las series temporales analizadas.',
                 'pt': 'Antes da plotagem, foi realizado processamento adicional de dados pelo método Savitzky-Golay. '
                       'Este método aplica filtragem estatística em dados já limpos com a máscara de nuvem da Agência '
                       'Espacial Europeia (ESA), melhorando assim a suavidade e a precisão das séries temporais '
                       'analisadas.'},
 'total_precipitation': {'en': 'Total precipitation for the analysis period:',
                         'es': 'Precipitaciones totales para el periodo de análisis:',
                         'pt': 'Precipitações totais para o período de análise:'},
 'trend': {'en': 'Trend', 'es': 'Tendencia', 'pt': 'Tendência'},
 'trend_curve': {'en': 'Trend curve', 'es': 'Curva de tendencia', 'pt': 'Curva de tendência'},
 'tt_dia': {'en': 'TT (°C/day)', 'es': 'TT (°C/día)', 'pt': 'TT (°C/dia)'},
 'tuesday': {'en': 'Tuesday', 'es': 'Martes', 'pt': 'Terça-feira'},
 'type_crop': {'en': 'Crop Group', 'es': 'Grupo de Cultivo', 'pt': 'Grupo de Cultura'},
 'type_crop_warning': {'en': 'You can only select one group of crops',
                       'es': 'Solo puedes seleccionar un grupo de cultivos',
                       'pt': 'Você só pode selecionar um grupo de culturas'},
 'upper_fence': {'en': 'Upper fence', 'es': 'Limite superior', 'pt': 'Limite superior'},
 'used_dates': {'en': 'Used dates', 'es': 'Fechas utilizadas', 'pt': 'Datas utilizadas'},
 'v3_soybean': {'en': 'Emergence to V3', 'es': 'Emergencia a V3', 'pt': 'Emergência até V3'},
 'v6_sunf': {'en': 'Emergence to V6', 'es': 'Emergencia a V6', 'pt': 'Emergência até V6'},
 'values_for': {'en': 'Values for', 'es': 'Valores para', 'pt': 'Valores para'},
 'varianza': {'en': 'Variance', 'es': 'Varianza', 'pt': 'Variância'},
 'veg_corn': {'en': 'Vegetative (V1 to VT)', 'es': 'Vegetativo (V1 a VT)', 'pt': 'Vegetativo (V1 a VT)'},
 'veg_potatoe': {'en': 'Emergence to Vegetative Development (BBCH 10–40)',
                 'es': 'Emergencia a Desarrollo vegetativo (BBCH 10–40)',
                 'pt': 'Emergência até Desenvolvimento vegetativo (BBCH 10–40)'},
 'ver_mas': {'en': 'see more...', 'es': 'ver más...', 'pt': 'ver mais...'},
 'vertical_exaggeration': {'en': 'Vertical exaggeration', 'es': 'Exageración vertical', 'pt': 'Exageração vertical'},
 'vie': {'en': 'Fri', 'es': 'Vie', 'pt': 'Sex'},
 'warning_fs': {'en': 'No fields have been found that match the parameters selected in the filter. We suggest you '
                      'adjust the parameters to obtain other results.',
                'es': 'No se han encontrado lotes que coincidan con los parámetros seleccionados en el filtro. Le '
                      'sugerimos ajustar los parámetros para obtener otros resultados.',
                'pt': 'Não foram encontrados lotes que correspondam aos parâmetros selecionados no filtro. Sugerimos '
                      'que você ajuste os parâmetros para obter outros resultados.'},
 'warning_seeding_date': {'en': 'The selected plot does not have a sowing date assigned, please assign a date in 360 '
                                'and try again',
                          'es': 'El lote seleccionado no posee fecha de siembra asignada, por favor asigne una fecha '
                                'en 360 y vuelva a intentarlo',
                          'pt': 'O lote selecionado não possui data de plantio atribuída, por favor atribua uma data '
                                'no 360 e tente novamente'},
 'water_classes': {'en': 'Water classes', 'es': 'Clases de agua', 'pt': 'Classes de agua'},
 'water_detected': {'en': 'Water detected', 'es': 'Agua detectada', 'pt': 'Água detectada'},
 'weather': {'en': 'Weather', 'es': 'Clima', 'pt': 'Clima'},
 'weather_forecast': {'en': 'Weather Forecast', 'es': 'Pronóstico del Tiempo', 'pt': 'Previsão do Tempo'},
 'wednesday': {'en': 'Wednesday', 'es': 'Miércoles', 'pt': 'Quarta-feira'},
 'week': {'en': 'Week', 'es': 'Semana', 'pt': 'Semana'},
 'weekly_acumulated': {'en': 'Weekly accumulated precipitation:',
                       'es': 'Precipitaciones acumuladas semanalmente:',
                       'pt': 'Precipitações acumuladas semanalmente:'},
 'weighted_yield': {'en': 'Weighted Yield', 'es': 'Rendimiento Ponderado', 'pt': 'Rendimento Ponderado'},
 'weighted_yield_by': {'en': 'Weighted Yield by', 'es': 'Rendimiento Ponderado por', 'pt': 'Rendimento Ponderado por'},
 'wind': {'en': 'Wind', 'es': 'Viento', 'pt': 'Vento'},
 'workspace': {'en': 'Work Space', 'es': 'Espacio de Trabajo', 'pt': 'Espaço de Trabalho'},
 'workspaces': {'en': 'Work spaces', 'es': 'Espacios de trabajo', 'pt': 'Espaços de trabalho'},
 'year': {'en': 'Year', 'es': 'Año', 'pt': 'Ano'},
 'yield_dashboard_description': {'en': 'This dashboard allows for a comparative analysis of the yield layers loaded '
                                       'into the 360 platform. Additionally, it facilitates the evaluation of harvest '
                                       'progress through the analysis of data related to harvest dates and mapped '
                                       'hectares.',
                                 'es': 'Este tablero permite hacer un análisis comparativo de las capas de rindes '
                                       'cargadas en la plataforma 360. Además, facilita la evaluación del progreso de '
                                       'cosecha mediante el análisis de los datos correspondientes a las fechas de '
                                       'cosechas y hectáreas mapeadas.',
                                 'pt': 'Este painel permite uma análise comparativa das camadas de rendimentos '
                                       'carregadas na plataforma 360. Além disso, facilita a avaliação do progresso da '
                                       'colheita através da análise dos dados referentes às datas de colheita e às '
                                       'hectares mapeadas.'},
 'yield_layer': {'en': 'Yield layer', 'es': 'Capa de Rinde', 'pt': 'Camada de Rendimento'},
 'yield_layers': {'en': 'Yield layers', 'es': 'Capas de rindes', 'pt': 'Camadas de Rendimento'},
 'yield_layers_without_crops': {'en': 'Layers without crops', 'es': 'Capas sin cultivos', 'pt': 'Camadas sem cultivos'},
 'yield_layers_without_harvest_date': {'en': 'Layers without harvest date',
                                       'es': 'Capas sin fecha de cosecha',
                                       'pt': 'Camadas sem data de colheita'},
 'yield_layers_without_hybrids_or_varieties': {'en': 'Layers without hybrids/varieties',
                                               'es': 'Capas sin híbridos/variedades',
                                               'pt': 'Camadas sem híbridos/variedades'},
 'yield_scale': {'en': 'Yield from scale', 'es': 'Rinde de balanza', 'pt': 'Rendimento com scala'},
 'zone': {'en': 'Zone', 'es': 'Ambiente', 'pt': 'Ambiente'},
 'zone_type': {'en': 'Zone type', 'es': 'Tipo de ambiente', 'pt': 'Tipo de ambiente'}}
