import sys
from qtpy.QtWidgets import QApplication, QPushButton, QVBoxLayout, QMainWindow, QWidget
from qtpy.QtCore import QObject, Property, Signal, Slot
class WidgetModel:
    def __init__(self, data): ...
    def get_data(self): ...
    def set_data(self, value): ...