"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dg_mol_track_client.types import BaseModel
from dg_mol_track_client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteCompoundByIDV1CompoundsCorporateCompoundIDDeleteRequestTypedDict(TypedDict):
    corporate_compound_id: str


class DeleteCompoundByIDV1CompoundsCorporateCompoundIDDeleteRequest(BaseModel):
    corporate_compound_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
