"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dg_mol_track_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserBaseTypedDict(TypedDict):
    email: str
    first_name: str
    last_name: str
    is_active: NotRequired[bool]
    is_service_account: NotRequired[bool]


class UserBase(BaseModel):
    email: str

    first_name: str

    last_name: str

    is_active: Optional[bool] = False

    is_service_account: Optional[bool] = False
