"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from intuned_client.types import BaseModel
from intuned_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetAuthSessionGlobalsTypedDict(TypedDict):
    workspace_id: NotRequired[str]
    r"""Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?"""


class GetAuthSessionGlobals(BaseModel):
    workspace_id: Annotated[
        Optional[str],
        pydantic.Field(alias="workspaceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?"""


class GetAuthSessionRequestTypedDict(TypedDict):
    project_name: str
    r"""Your project name. It is the name you provide when creating a project."""
    auth_session_id: str
    r"""Authentication session ID. You can obtain it from the Auth Sessions tab in your project details."""


class GetAuthSessionRequest(BaseModel):
    project_name: Annotated[
        str,
        pydantic.Field(alias="projectName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Your project name. It is the name you provide when creating a project."""

    auth_session_id: Annotated[
        str,
        pydantic.Field(alias="authSessionId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Authentication session ID. You can obtain it from the Auth Sessions tab in your project details."""


GetAuthSessionType = Literal[
    "CREDENTIALS",
    "RECORDER",
    "RUNTIME",
]


GetAuthSessionStatus = Literal[
    "PENDING",
    "READY",
    "EXPIRED",
]


class GetAuthSessionResponseTypedDict(TypedDict):
    r"""Authentication session details"""

    id: str
    r"""The unique identifier for the authentication session"""
    type: GetAuthSessionType
    status: GetAuthSessionStatus


class GetAuthSessionResponse(BaseModel):
    r"""Authentication session details"""

    id: str
    r"""The unique identifier for the authentication session"""

    type: GetAuthSessionType

    status: GetAuthSessionStatus
