# Asset Core status
ASSET_CORE_STATUS_MOVEDTODSU = 2 # MovedToDataStorageUnit

# Asset validation status
ASSET_VALIDATION_STATUS_ERROR = 0
ASSET_VALIDATION_STATUS_PENDINGVALIDATION = 1
ASSET_VALIDATION_STATUS_INPROGRESS = 2
ASSET_VALIDATION_STATUS_VALIDATED = 3

# Settings
SETTINGS_SAMPLING_MAX_ERROR_PERCENTAGE = 'SamplingMaxErrorPercentage'
SETTINGS_SAMPLING_ROW_COUNT_THRESHOLD = 'RowCountThresholdForSampling'
SETTINGS_SAMPLING_PERCENTAGE = 'SamplingPercentage'

# Validation results
VALIDATION_RESULT_DATA_ROWS_FAILED_PERCENT = 'rows_failed_percent'
VALIDATION_RESULT_DATA_VALIDATIONS_FAILED = 'validations_failed'
VALIDATION_RESULT_DATA_REPORT = 'report'
VALIDATION_RESULT_DATA_ROWS_FAILED_IDS = 'rows_failed_ids'
VALIDATION_RESULT_DATA_ROWS_FAILED_COUNT = 'rows_failed_count'
VALIDATION_TRIGGERED_BY_DIP_EXECUTION = 0
VALIDATION_TRIGGERED_BY_ON_DEMAND_FULL_VALIDATION_BY_ENTITY = 1
VALIDATION_TRIGGERED_BY_ON_DEMAND_FULL_VALIDATION_BY_PROVIDER = 2
VALIDATION_TRIGGERED_BY_LANDING_INTAKE = 3

# Great Expectation attributes
GE_STATISTICS = 'validation_statistics'
GE_STATISTICS_UNSUCCESSFUL_EXPECTATIONS = 'unsuccessful_expectations'
GE_VALIDATION_RESULTS = 'results'
GE_VALIDATION_RESULTS_EXPECTATION_CONFIG = 'expectation_config'
GE_VALIDATION_RESULTS_EXPECTATION_CONFIG_TYPE = 'expectation_type'
GE_VALIDATION_RESULT = 'result'
GE_VALIDATION_RESULT_UNEXPECTED_VALUES = 'unexpected_index_list'

# Storage
STORAGE_DEFAULT_CONTAINER = 'data-quality-validations'
STORAGE_REPORTS_FOLDER = 'reports'
STORAGE_RESULTS_FOLDER = 'results'
STORAGE_VALIDATIONS_FOLDER = 'validations'
STORAGE_REPORTS_SUBFOLDER_BY_PROVIDER = 'ProviderReports'
STORAGE_REPORTS_SUBFOLDER_BY_ENTITY = 'EntityReports'
STORAGE_SITE_NAME_CONFIG = 'dq_storage_account_site'

# Databricks
DATABRICKS_TABLE_ERROR_COLUMN_NAME = 'SidraPassedValidation'
DATABRICKS_TABLE_ID_ASSET_COLUMN_NAME = 'SidraIdAsset'
DATABRICKS_TABLE_IS_DELETED_COLUMN_NAME = 'SidraIsDeleted'

# Secrets
SECRET_STORAGE_ACCOUNT_NAME = 'principal_storage_account_name'
SECRET_STORAGE_ACCOUNT_KEY = 'principal_storage_account_key'
SECRET_CLIENT_ID = 'client_id'
SECRET_CLIENT_SECRET = 'client_secret'
SECRET_API_URL = 'api_url'
SECRET_DATABRICKS_SCOPE = 'service_data_quality'
SECRET_API_SCOPE = 'scope'

# Report index generation
INDEX_TEMPLATE_PATH = './report_index_template.html'
PLACEHOLDER_HEADER = 'SECTION1BLOCK1_HEADER'
PLACEHOLDER_DATA = 'SECTION1BLOCK2_1DATAHERE'
INDEX_REPORT_FILE_NAME = 'index.html'
ZIP_REPORT_FILE_NAME = 'data_quality_report'
ICON_SUCCESS = '<i class="fas fa-check-circle text-success ge-success-icon" ></i>'
ICON_FAILED = '<i class="fas fa-times text-danger ge-failed-icon" ></i>'
RESULT_TEXT_SUCCESS = 'Success'
RESULT_TEXT_FAILED = 'Failed'
DATETIME_LONG_FORMAT = '%Y-%m-%d %H:%M:%S %Z'
DATETIME_SHORT_FORMAT = '%Y%m%d%H%M%S'
PLACEHOLDER_ICON_RESULT = '[VALIDATION_ICON_RESULT]'
PLACEHOLDER_RUN_TIME_LONG_FORMAT = '[VALIDATION_RUN_TIME_LONG_FORMAT]'
PLACEHOLDER_RUN_TIME_SORT = '[VALIDATION_RUN_TIME_SORT]'
PLACEHOLDER_RUN_NAME = '[VALIDATION_RUN_NAME]'
PLACEHOLDER_DATASOURCE_NAME = '[VALIDATION_DATASOURCE_NAME]'
PLACEHOLDER_EXPECTATION_SUITE_NAME = '[VALIDATION_EXPECTATION_SUITE_NAME]'
PLACEHOLDER_RUN_TIME_SHORT_FORMAT = '[VALIDATION_RUN_TIME_SHORT_FORMAT]'
PLACEHOLDER_RESULT_TEXT = '[VALIDATION_RESULT_TEXT]'
SECTION_TEMPLATE = f"{{'validation_success': '<span class=\"ge-index-page-table-validation-links-item\" >{PLACEHOLDER_ICON_RESULT}</span>', 'run_time': '{PLACEHOLDER_RUN_TIME_LONG_FORMAT}', '_run_time_sort': {PLACEHOLDER_RUN_TIME_SORT}, 'run_name': '{PLACEHOLDER_RUN_NAME}', 'datasource_name': '{PLACEHOLDER_DATASOURCE_NAME}', '_datasource_name_sort': '{PLACEHOLDER_DATASOURCE_NAME}', 'expectation_suite_name': '{PLACEHOLDER_EXPECTATION_SUITE_NAME}', '_expectation_suite_name_sort': '{PLACEHOLDER_EXPECTATION_SUITE_NAME}', '_table_row_link_path': 'validations/{PLACEHOLDER_EXPECTATION_SUITE_NAME}/{PLACEHOLDER_RUN_NAME}/{PLACEHOLDER_RUN_TIME_SHORT_FORMAT}/{PLACEHOLDER_RUN_NAME}.html', '_validation_success_text': '{PLACEHOLDER_RESULT_TEXT}'}}"