import pandas as pd
from iode import variables as variables

def df_to_ws(df_input: pd.DataFrame, time_axis_name: str = 'time'): ...
def ws_to_df(vars_pattern: str = '*', vars_axis_name: str = 'vars', time_axis_name: str = 'time', time_as_floats: bool = False) -> pd.DataFrame: ...
