# coding: utf-8

"""
    vivnfm/vi-vnfm.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubevim_vivnfm_client.models.virtual_network_interface_data import VirtualNetworkInterfaceData

class TestVirtualNetworkInterfaceData(unittest.TestCase):
    """VirtualNetworkInterfaceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VirtualNetworkInterfaceData:
        """Test VirtualNetworkInterfaceData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VirtualNetworkInterfaceData`
        """
        model = VirtualNetworkInterfaceData()
        if include_optional:
            return VirtualNetworkInterfaceData(
                network_id = kubevim_vivnfm_client.models.identifier.Identifier(
                    value = '', ),
                subnet_id = kubevim_vivnfm_client.models.identifier.Identifier(
                    value = '', ),
                network_port_id = kubevim_vivnfm_client.models.identifier.Identifier(
                    value = '', ),
                type_virtual_nic = 'BRIDGE',
                type_configuration = [
                    ''
                    ],
                bandwidth = 1.337,
                acceleration_capability = [
                    ''
                    ],
                metadata = kubevim_vivnfm_client.models.metadata.Metadata(
                    fields = {
                        'key' : ''
                        }, )
            )
        else:
            return VirtualNetworkInterfaceData(
                type_virtual_nic = 'BRIDGE',
        )
        """

    def testVirtualNetworkInterfaceData(self):
        """Test VirtualNetworkInterfaceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
