"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "cribl-control-plane"
__version__: str = "0.2.1rc8"
__openapi_doc_version__: str = "4.15.0-alpha.1762249156162-b384ad31"
__gen_version__: str = "2.731.6"
__user_agent__: str = "speakeasy-sdk/python 0.2.1rc8 2.731.6 4.15.0-alpha.1762249156162-b384ad31 cribl-control-plane"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
