from _typeshed import Incomplete
from android.graphics import BitmapFactory as BitmapFactory
from java import cast as cast
from java.util import List as List
from org.telegram.messenger import DispatchQueue, R as R, SendMessagesHelper as SendMessagesHelper
from org.telegram.tgnet import TLObject as TLObject, TLRPC
from typing import Any

STAGE_QUEUE: str
GLOBAL_QUEUE: str
CACHE_CLEAR_QUEUE: str
SEARCH_QUEUE: str
PHONE_BOOK_QUEUE: str
THEME_QUEUE: str
EXTERNAL_NETWORK_QUEUE: str
PLUGINS_QUEUE: str

def get_queue_by_name(queue_name: str) -> DispatchQueue | None: ...
def run_on_queue(fn: callable, queue_name: str = ..., delay: int = 0): ...

class RequestCallback(Incomplete):
    def __init__(self, fn: callable) -> None: ...
    def run(self, response: TLObject, error: TLRPC.TL_error): ...

def send_request(request: Any, fn: callable) -> int: ...
def get_last_fragment(): ...
def get_account_instance(): ...
def get_messages_controller(): ...
def get_contacts_controller(): ...
def get_media_data_controller(): ...
def get_connections_manager(): ...
def get_location_controller(): ...
def get_notifications_controller(): ...
def get_messages_storage(): ...
def get_send_messages_helper(): ...
def get_file_loader(): ...
def get_secret_chat_helper(): ...
def get_download_controller(): ...
def get_notifications_settings(): ...
def get_notification_center(): ...
def get_media_controller(): ...
def get_user_config(): ...
def send_message(params: dict): ...
def send_text(peer: int, text: str, **kwargs): ...
def send_photo(peer: int, file_path: str, caption: str = '', high_quality: bool = False, **kwargs): ...
def send_document(peer: int, file_path: str, caption: str = '', **kwargs): ...
def send_video(peer: int, file_path: str, caption: str = '', **kwargs): ...
def send_audio(peer: int, file_path: str, caption: str = '', **kwargs): ...
def edit_message(message_obj: Any, text: str | None = None, file_path: str | None = None, with_spoiler: bool = False, **kwargs): ...

class NotificationCenterDelegate(Incomplete):
    def __init__(self) -> None: ...
    def didReceivedNotification(self, id: int, account: int, args: None): ...
