# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LocationFixQuality.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'LocationFixQuality.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18LocationFixQuality.proto\x12\x07keelson\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n\x12LocationFixQuality\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x08\x66ix_type\x18\x02 \x01(\x0e\x32#.keelson.LocationFixQuality.FixType\"\x90\x01\n\x07\x46ixType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07INVALID\x10\x01\x12\n\n\x06\x46IX_NO\x10\x02\x12\n\n\x06\x46IX_2D\x10\x03\x12\n\n\x06\x46IX_3D\x10\x04\x12\n\n\x06GPS_DR\x10\x05\x12\r\n\tTIME_ONLY\x10\x06\x12\x0b\n\x07\x44R_ONLY\x10\x07\x12\x0f\n\x0b\x46IX_3D_DGPS\x10\x08\x12\x0e\n\nFIX_3D_RTK\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LocationFixQuality_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONFIXQUALITY']._serialized_start=71
  _globals['_LOCATIONFIXQUALITY']._serialized_end=340
  _globals['_LOCATIONFIXQUALITY_FIXTYPE']._serialized_start=196
  _globals['_LOCATIONFIXQUALITY_FIXTYPE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
