from iode import HighToLowType as HighToLowType, IodeType as IodeType, LowToHighMethod as LowToHighMethod, LowToHighType as LowToHighType, comments as comments, equations as equations, identities as identities, lists as lists, scalars as scalars, tables as tables, variables as variables
from typing import Any

def ws_content(pattern: str | list[str] = '*', obj_type: int = ...) -> list[str]: ...
def ws_content_cmt(pattern: str | list[str] = '*') -> list[str]:
    """Returns the list of comment names corresponding to the given pattern"""
def ws_content_eqs(pattern: str | list[str] = '*') -> list[str]:
    """Returns the list of equation names corresponding to the given pattern"""
def ws_content_idt(pattern: str | list[str] = '*') -> list[str]:
    """Returns the list of identity names corresponding to the given pattern"""
def ws_content_lst(pattern: str | list[str] = '*') -> list[str]: ...
def ws_content_scl(pattern: str | list[str] = '*') -> list[str]: ...
def ws_content_tbl(pattern: str | list[str] = '*') -> list[str]: ...
def ws_content_var(pattern: str | list[str] = '*') -> list[str]: ...
def ws_clear_all() -> None:
    """Clear all WS"""
def ws_clear(filetype: int):
    """Clear WS of the given filetype (COMMENTS..VARIABLES)"""
def ws_clear_cmt() -> None: ...
def ws_clear_eqs() -> None: ...
def ws_clear_idt() -> None: ...
def ws_clear_lst() -> None: ...
def ws_clear_scl() -> None: ...
def ws_clear_tbl() -> None: ...
def ws_clear_var() -> None: ...
def ws_load(filename: str, filetype: int) -> Any:
    """Load an IODE file and return the number of read objects"""
def ws_load_cmt(filename: str): ...
def ws_load_eqs(filename: str) -> int: ...
def ws_load_idt(filename: str) -> int: ...
def ws_load_lst(filename: str) -> int: ...
def ws_load_scl(filename: str) -> int: ...
def ws_load_tbl(filename: str) -> int: ...
def ws_load_var(filename: str) -> int: ...
def ws_save(filename: str, filetype: int):
    """Save the current IODE workspace of a given type"""
def ws_save_cmt(filename: str):
    """Save the current comment workspace"""
def ws_save_eqs(filename: str):
    """Save the current equation workspace"""
def ws_save_idt(filename: str):
    """Save the current identity workspace"""
def ws_save_lst(filename: str):
    """Save the current list workspace"""
def ws_save_scl(filename: str):
    """Save the current scalar workspace"""
def ws_save_tbl(filename: str):
    """Save the current table workspace"""
def ws_save_var(filename: str): ...
def ws_htol(filename: str, varlist, series_type: int): ...
def ws_htol_last(filename: str, varlist): ...
def ws_htol_mean(filename: str, varlist): ...
def ws_htol_sum(filename: str, varlist): ...
def ws_ltoh(filename: str, varlist, series_type, method: int | str): ...
def ws_ltoh_flow(filename: str, varlist, method: int | str = ...): ...
def ws_ltoh_stock(filename: str, varlist, method: int | str = ...): ...
