from qtpy.QtWidgets import QApplication, QWidget, QLabel, QVBoxLayout, QPushButton
from qtpy.QtGui import QPixmap, QPainter, QPen, QBrush
from qtpy.QtCore import Qt, QSize
def widget_to_pixmap(widget): ...
class ExampleWidget:
    def __init__(self): ...
class PixmapWidget:
    def __init__(self): ...
    def paintEvent(self, event): ...