from qtpy.QtCore import Qt, QRectF, QEasingCurve, QPropertyAnimation, QParallelAnimationGroup, QSequentialAnimationGroup, Property
from qtpy.QtGui import QColor, QPen, QPainter, QFont
from qtpy.QtWidgets import QProgressBar
from .progress_bar import ProgressBar
from ...common.font import setFont
from ...common.style_sheet import themeColor, isDarkTheme
class ProgressRing:
    def __init__(self, parent, useAni): ...
    def getStrokeWidth(self): ...
    def setStrokeWidth(self, w: int): ...
    def _drawText(self, painter: QPainter, text: str): ...
    def paintEvent(self, e): ...
class IndeterminateProgressRing:
    def __init__(self, parent, start): ...
    def startAngle(self): ...
    def startAngle(self, angle: int): ...
    def spanAngle(self): ...
    def spanAngle(self, angle: int): ...
    def getStrokeWidth(self): ...
    def setStrokeWidth(self, w: int): ...
    def start(self): ...
    def stop(self): ...
    def lightBarColor(self): ...
    def darkBarColor(self): ...
    def setCustomBarColor(self, light, dark): ...
    def setCustomBackgroundColor(self, light, dark): ...
    def paintEvent(self, e): ...