"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "compass_api_sdk"
__version__: str = "1.3.1"
__openapi_doc_version__: str = "0.0.1"
__gen_version__: str = "2.737.0"
__user_agent__: str = "speakeasy-sdk/python 1.3.1 2.737.0 0.0.1 compass_api_sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
