from biobit.core.loc import IntoOrientation, IntoChainInterval


class NMS:
    def __init__(self) -> None: ...

    def set_fecutoff(self, fecutoff: float) -> NMS: ...

    def set_group_within(self, group_within: int) -> NMS: ...

    def set_slopfrac(self, slopfrac: float) -> NMS: ...

    def set_sloplim(self, minslop: int, maxslop: int) -> NMS: ...

    def set_sensitivity(self, sensitivity: float) -> NMS: ...

    def add_regions(
            self, orientation: IntoOrientation, uniform_baseline: bool, regions: list[IntoChainInterval]
    ) -> NMS: ...
