from __future__ import annotations
import asyncio
from functools import lru_cache
from fractions import Fraction
from typing import Optional, Union, Callable
from qtpy.QtWidgets import QLabel, QGraphicsDropShadowEffect, QHBoxLayout, QFrame, QSizePolicy
from qtpy.QtGui import QColor, QPixmap
from qtpy.QtCore import QSize, QThreadPool, QTimer
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from ..widget_base import PyWidgetBase
class Image:
    def __init__(self, key: str, ratio: str, src: str, sx: Optional[Union[str, dict]], height: Optional[int], width: Optional[int], size: Optional[QSize], *args, **kwargs): ...
    def _init_ui(self): ...
    def _set_stylesheet(self, component_styled): ...
    def showEvent(self, e): ...
    def setShadowEffect(self, blurRadius, offset, color): ...
    def resizeEvent(self, event): ...