wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA427.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA464.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA484.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA505.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA527.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA574.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA624.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA679.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA709.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA738.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA767.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/IA827.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/NB711.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/NB816.SuprimeCam.pb
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/irac_ch1.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/irac_ch2.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/irac_ch3.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/irac_ch4.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/B_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/V_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/g_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/r_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/i_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/z_subaru.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/suprime_FDCCD_z.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/u_megaprime_sagem.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/y_HSC.txt
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/Y_uv.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/J_uv.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/H_uv.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/K_uv.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/wircam_H.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/wircam_Ks.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/galex1500.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/galex2500.res
wget -nc https://sites.astro.caltech.edu/~afaisst/files/cosmos_filter/mips24.res

wget -nc https://ftp.iap.fr/pub/from_users/hjmcc/COSMOS2015/COSMOS2015_Laigle+.header
