from pathlib import Path

__all__ = ['get_client_dir_path', 'get_client_logs_dir_path', 'get_console_dir_path', 'get_proxy_tls_cert_path', 'get_proxy_tls_key_path', 'get_client_session_logs_dir_path', 'get_default_settings_path', 'get_admin_client_dir_path', 'get_admin_client_logs_dir_path']

def get_client_dir_path() -> Path: ...
def get_client_logs_dir_path() -> Path: ...
def get_client_session_logs_dir_path() -> Path: ...
def get_console_dir_path() -> Path: ...
def get_proxy_tls_cert_path() -> Path: ...
def get_proxy_tls_key_path() -> Path: ...
def get_default_settings_path() -> Path: ...
def get_admin_client_dir_path() -> Path: ...
def get_admin_client_logs_dir_path() -> Path: ...
