# GeosunBaseTransformLib7.pyi - 自动生成的类型存根文件
# 生成时间: 2025-11-04 16:37:12
# 函数数量: 20 | 类数量: 2 | 方法数量: 14

from typing import Any, Optional

# 导入语句
from pyproj import Transformer, CRS
from typing import Tuple, Union, List, Optional
import numpy as np

# 模块级函数
def normalize_angle(angle: float) -> Any: ...
def geosun_euler_to_rotation_matrix(roll: float, pitch: float, yaw: float) -> Any: ...
def rotation_matrix_to_geosun_euler(R: np.ndarray) -> Any: ...
def standard_euler_to_rotation_matrix(roll: float, pitch: float, yaw: float) -> Any: ...
def rotation_matrix_to_standard_euler(R: np.ndarray) -> Any: ...
def rotation_matrix_to_quaternion(R: np.ndarray) -> Any: ...
def quaternion_to_rotation_matrix(q: Union[list, np.ndarray]) -> Any: ...
def rotation_matrix_to_axis_angle(R: np.ndarray) -> Any: ...
def axis_angle_to_rotation_matrix(axis: np.ndarray, angle: float) -> Any: ...
def geosun_euler_to_quaternion(roll: float, pitch: float, yaw: float) -> Any: ...
def quaternion_to_geosun_euler(q: Union[list, np.ndarray]) -> Any: ...
def geosun_euler_to_axis_angle(roll: float, pitch: float, yaw: float) -> Any: ...
def axis_angle_to_geosun_euler(axis: np.ndarray, angle: float) -> Any: ...
def standard_euler_to_quaternion(roll: float, pitch: float, yaw: float) -> Any: ...
def quaternion_to_standard_euler(q: Union[list, np.ndarray]) -> Any: ...
def standard_euler_to_axis_angle(roll: float, pitch: float, yaw: float) -> Any: ...
def axis_angle_to_standard_euler(axis: np.ndarray, angle: float) -> Any: ...
def interpolate_pos(pos_data: List[Tuple], gps_time: float, euler_type: str = 'geosun') -> Any: ...
def enh_to_lidar() -> Any: ...
def lidar_to_enh() -> Any: ...

# 类定义
class ExtrinsicParam:
    def __matmul__(self, other: 'ExtrinsicParam') -> Any: ...
    def __repr__(self) -> Any: ...
    @classmethod
    def from_homogeneous_matrix(cls, T: np.ndarray) -> Any: ...
    def inverse(self) -> Any: ...
    def transform_point(self, point: Union[list, np.ndarray]) -> Any: ...
    def inverse_transform_point(self, point: Union[list, np.ndarray]) -> Any: ...
    def get_homogeneous_matrix(self) -> Any: ...
    def get_axis_angle(self) -> Any: ...
    def get_axis_angle_degrees(self) -> Any: ...
    def get_quaternion(self) -> Any: ...
    def get_geosun_euler(self) -> Any: ...
    def get_standard_euler(self) -> Any: ...

class CoordinateConverter:
    def enh_to_ecef(self, enh_point: Union[list, np.ndarray]) -> Any: ...
    def ecef_to_enh(self, ecef_point: Union[list, np.ndarray]) -> Any: ...

