from qtpy.QtGui import QPixmap, QPainter, QColor
from qtpy.QtWidgets import QWidget
from ...common.style_sheet import isDarkTheme
class HorizontalSeparator:
    def __init__(self, parent, w, h): ...
    def setSize(self, w, h): ...
    def paintEvent(self, e): ...
class VerticalSeparator:
    def __init__(self, parent, w, h): ...
    def setSize(self, w, h): ...
    def paintEvent(self, e): ...