from qtpy.QtCore import QEasingCurve, QPropertyAnimation, Qt, QTimer, Signal, QSize, QPoint, QRectF
from qtpy.QtGui import QPainter
from qtpy.QtWidgets import QLabel, QWidget, QToolButton, QGraphicsOpacityEffect
from qtpy.QtSvgWidgets import QSvgWidget
from ...common import FluentStyleSheet, isDarkTheme, Theme
from ...common.icon import FluentIcon
class StateCloseButton:
    def __init__(self, parent): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def paintEvent(self, e): ...
class StateToolTip:
    def __init__(self, title, content, parent): ...
    def __initWidget(self): ...
    def __initLayout(self): ...
    def __setQss(self): ...
    def setTitle(self, title: str): ...
    def setContent(self, content: str): ...
    def setState(self, isDone): ...
    def __onCloseButtonClicked(self): ...
    def __fadeOut(self): ...
    def __rotateTimerFlowSlot(self): ...
    def getSuitablePos(self): ...
    def paintEvent(self, e): ...