from radkit_common.access.exceptions import InvalidDomainError as InvalidDomainError

def validate_domains(domains: list[str]) -> list[str]: ...
def match_domains(domain: str, domains: list[str], allow_global_wildcard: bool = True) -> bool: ...
