from biobit.core.loc import IntoOrientation, IntoChainInterval


class RNAPileup:
    def __init__(self) -> None: ...

    def set_sensitivity(self, sensitivity: float) -> RNAPileup: ...

    def set_control_baseline(self, control_baseline: float) -> RNAPileup: ...

    def set_min_signal(self, min_signal: float) -> RNAPileup: ...

    def add_control_model(
            self, orientation: IntoOrientation, regions: list[IntoChainInterval], uniform_baseline: bool,
            winsizes: list[int]
    ) -> RNAPileup: ...
