# Generated by Django 5.1.7 on 2025-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_ai', '0002_alter_aitranslatorsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitranslatorsettings',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text="Give instructions to the AI about the style, how to translate certain things or other informations about the website you're translating.", verbose_name='Style prompt'),
        ),
    ]
