# coding: utf-8

"""
Public API

This is an API that exposes public api functionality

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.autoscaler_kind import AutoscalerKind
from openapi_client.models.over_provisioned_cluster_grouped_data import (
    OverProvisionedClusterGroupedData,
)
from typing import Optional, Set
from typing_extensions import Self


class OverProvisionedClusterSupportingData(BaseModel):
    """
    OverProvisionedClusterSupportingData
    """  # noqa: E501

    autoscaler_komodor_uid: StrictStr = Field(alias="autoscalerKomodorUid")
    autoscaler_kind: AutoscalerKind = Field(alias="autoscalerKind")
    potential_cpu_savings: Union[StrictFloat, StrictInt] = Field(
        description="The potential CPU savings in CPU Cores - by weekly average",
        alias="potentialCPUSavings",
    )
    potential_memory_savings: StrictInt = Field(
        description="The potential Memory savings in GiB - by weekly average",
        alias="potentialMemorySavings",
    )
    potential_savings: Union[StrictFloat, StrictInt] = Field(
        description="The potential savings in USD - by weekly average",
        alias="potentialSavings",
    )
    data_by_node_types: Dict[str, OverProvisionedClusterGroupedData] = Field(
        description="mapping of node types to their data", alias="dataByNodeTypes"
    )
    data_by_node_pool: Optional[Dict[str, OverProvisionedClusterGroupedData]] = Field(
        default=None,
        description="mapping of node pools to their data",
        alias="dataByNodePool",
    )
    violating_cpu_percentage: Optional[StrictInt] = Field(
        default=None, alias="violatingCPUPercentage"
    )
    violating_memory_percentage: Optional[StrictInt] = Field(
        default=None, alias="violatingMemoryPercentage"
    )
    cpu_capacity: StrictInt = Field(alias="cpuCapacity")
    memory_capacity: StrictInt = Field(alias="memoryCapacity")
    __properties: ClassVar[List[str]] = [
        "autoscalerKomodorUid",
        "autoscalerKind",
        "potentialCPUSavings",
        "potentialMemorySavings",
        "potentialSavings",
        "dataByNodeTypes",
        "dataByNodePool",
        "violatingCPUPercentage",
        "violatingMemoryPercentage",
        "cpuCapacity",
        "memoryCapacity",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OverProvisionedClusterSupportingData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in data_by_node_types (dict)
        _field_dict = {}
        if self.data_by_node_types:
            for _key_data_by_node_types in self.data_by_node_types:
                if self.data_by_node_types[_key_data_by_node_types]:
                    _field_dict[_key_data_by_node_types] = self.data_by_node_types[
                        _key_data_by_node_types
                    ].to_dict()
            _dict["dataByNodeTypes"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in data_by_node_pool (dict)
        _field_dict = {}
        if self.data_by_node_pool:
            for _key_data_by_node_pool in self.data_by_node_pool:
                if self.data_by_node_pool[_key_data_by_node_pool]:
                    _field_dict[_key_data_by_node_pool] = self.data_by_node_pool[
                        _key_data_by_node_pool
                    ].to_dict()
            _dict["dataByNodePool"] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OverProvisionedClusterSupportingData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "autoscalerKomodorUid": obj.get("autoscalerKomodorUid"),
                "autoscalerKind": obj.get("autoscalerKind"),
                "potentialCPUSavings": obj.get("potentialCPUSavings"),
                "potentialMemorySavings": obj.get("potentialMemorySavings"),
                "potentialSavings": obj.get("potentialSavings"),
                "dataByNodeTypes": (
                    dict(
                        (_k, OverProvisionedClusterGroupedData.from_dict(_v))
                        for _k, _v in obj["dataByNodeTypes"].items()
                    )
                    if obj.get("dataByNodeTypes") is not None
                    else None
                ),
                "dataByNodePool": (
                    dict(
                        (_k, OverProvisionedClusterGroupedData.from_dict(_v))
                        for _k, _v in obj["dataByNodePool"].items()
                    )
                    if obj.get("dataByNodePool") is not None
                    else None
                ),
                "violatingCPUPercentage": obj.get("violatingCPUPercentage"),
                "violatingMemoryPercentage": obj.get("violatingMemoryPercentage"),
                "cpuCapacity": obj.get("cpuCapacity"),
                "memoryCapacity": obj.get("memoryCapacity"),
            }
        )
        return _obj
